"""Ordered governance testcase section: approvals."""
from __future__ import annotations


# ===========================================================================
# governance/approval.md — AUTH-4 approval lifecycle invariants (implement/07 4, 06 1)
# ===========================================================================
_APV_PRE = [
    "Namespace " + NS + "apv-<case_id>-<worker_id>; approval queue seeded from fixtures/offline/governance.json.",
    "Operator identities and roles resolved from the fixture operator registry; every decision goes through POST /api/v1/approvals/{id}/decision, the only approval route.",
]
_APV_STEPS_TAIL = "Re-read the approval record and the immutable audit rows to confirm the decision was recorded once with the operator identity."

_add(
    case(
        "GOV-APV-DOUBLE-DECISION", "Concurrent decisions: exactly one wins, the loser receives 409 and changes nothing",
        APPROVAL_SUITE, "governance", ["SCR-003", "AUTH-4", "NFR-007", "TC-E2E-002"],
        ["entity:Approval", "stage:APPROVAL"], "baseline", "P0", "critical",
        "Two operators (or one double-click) both succeed, so the campaign executes once and is also cancelled, or two conflicting decisions are both recorded.",
        [GOV_FX],
        _APV_PRE + ["APV-CAMP-15 is AWAITING_HUMAN with payload_hash recorded and no prior decision."],
        {"concurrent_requests": [
             {"operator_id": "OP-APPROVER-T1", "decision": "APPROVE", "reason": "Reviewed evidence."},
             {"operator_id": "OP-SECOND-T1", "decision": "CANCEL", "reason": "Campaign postponed."}],
         "dispatch": "both submitted before either response is awaited"},
        [("Submit APPROVE and CANCEL concurrently against APV-CAMP-15",
          "Exactly one returns HTTP 200 with its status; the other returns 409 with a conflict reason and no status change."),
         ("Read the final approval record",
          "The record holds exactly one terminal status (APPROVED or CANCELLED) with one decided_at and one operator identity."),
         ("Read the audit rows",
          "One decision audit row exists for the winner; the loser has a rejected-decision row and no execution row."),
         ("Check the adapter and reservation ledger",
          "If APPROVE won, exactly one send and no reservation release; if CANCEL won, zero sends and reservations released - never both outcomes.")],
        ["The approval reaches exactly one terminal state; there is no interleaved outcome.",
         "Exactly one decision audit row carries a status change; the loser is recorded as a conflict, not as a decision.",
         "Side effects match the winning decision alone: one send xor full reservation release.",
         "The losing operator receives an explicit 409, never a silent no-op."],
        ["Recording both decisions and letting the last writer win.",
         "Executing after a concurrent cancel committed.",
         "Returning 200 to both callers so both operators believe they acted."],
        ["Both HTTP responses with correlation ids.",
         "Final approval record and the decision audit rows.",
         "Adapter and reservation ledger snapshots."],
        ["Delete " + NS + " approval rows; restore the reservation ledger to its fixture state and report the simulated send as non-recallable."],
        "Real approval state machine and persistence under test with a deterministic barrier that releases both requests together; the adapter is the substituted boundary. No sleeps: the barrier is a latch.",
        refs=[IMPL07, API06],
    ),
    case(
        "GOV-APV-STALE-PAYLOAD", "Stale review: a payload changed after review cannot be approved by hash match",
        APPROVAL_SUITE, "governance", ["SCR-003", "AUTH-4", "BR-010", "NFR-008"],
        ["entity:Approval", "entity:Evidence", "stage:APPROVAL"], "baseline", "P0", "critical",
        "The reviewer approves a 10 percent discount while the stored payload now carries 40 percent, so an unreviewed commercial commitment executes under an approval that was given for something else.",
        [GOV_FX],
        _APV_PRE + ["The operator script loads APV-CAMP-15 and captures payload_hash at review time."],
        {"review_snapshot_hash": "sha256:7b1f0a1e2d3c4b5a6f70819a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e",
         "mutation": {"field": "discount_rate", "from": 0.15, "to": 0.40, "at": "after review, before decision"},
         "decision": {"decision": "APPROVE", "operator_id": "OP-APPROVER-T1", "reason": "Approved as reviewed."}},
        [("Load the approval item and record the reviewed payload_hash",
          "The client receives the payload and its hash from the server, not from local storage."),
         ("Mutate the stored payload discount to 0.40 while the item is still AWAITING_HUMAN",
          "The stored payload_hash changes accordingly; the item remains AWAITING_HUMAN."),
         ("Submit APPROVE carrying the reviewed hash",
          "The decision is refused with a stale/conflict response; the item stays AWAITING_HUMAN and nothing executes."),
         ("Refresh and approve the current payload explicitly",
          "The refreshed decision succeeds and the released payload carries the 0.40 discount that was actually reviewed in the refreshed view.")],
        ["An approval whose reviewed hash differs from the stored payload is refused; no execution occurs on the stale decision.",
         "The refusal does not mutate the item state, so the work is not lost.",
         "The released payload after refresh equals the stored payload at release time.",
         "Both the reviewed and the mutated hash are retained for the audit trail."],
        ["Matching on approval id alone and ignoring the payload hash.",
         "Silently releasing the mutated payload because the item id matched.",
         "Deleting the mutated payload so the history looks clean."],
        ["Refusal response with both hashes.",
         "Approval record history showing the hash change and the later decision.",
         "Released payload copy matched against the reviewed hash."],
        ["Delete " + NS + " approval rows after exporting the hash history."],
        "Real approval hash binding under test; the mutation is applied through the supported sandbox payload update path so the hash genuinely changes. No UI-only mock: the check runs server-side.",
        refs=[IMPL07, API06],
    ),
    case(
        "GOV-APV-EXPIRY", "Expiry TTL: an expired approval cannot be approved or silently executed",
        APPROVAL_SUITE, "governance", ["SCR-003", "AUTH-4", "NFR-008", "NFR-004"],
        ["entity:Approval", "stage:APPROVAL"], "baseline", "P0", "critical",
        "A month-old approval is reused to release a campaign whose prices, consent and inventory have all changed, executing a commitment nobody currently endorses.",
        [GOV_FX],
        _APV_PRE + ["APV-T2-CAMP carries expires_at 2026-01-15T10:00:00Z, exactly the frozen clock."],
        {"expired_item": {"approval_id": "APV-T2-CAMP", "expires_at": "2026-01-15T10:00:00Z"},
         "decision_before": {"decision": "APPROVE", "operator_id": "OP-APPROVER-T2", "reason": "Approve before expiry."},
         "decision_after": {"decision": "APPROVE", "operator_id": "OP-APPROVER-T2", "reason": "Approve after expiry."}},
        [("Approve one second before the expiry instant using the injected clock",
          "HTTP 200 with status APPROVED; the item is released once."),
         ("Attempt to approve a second item after its expiry instant has passed",
          "The decision is refused with an expired status response; the item moves to an expired terminal state rather than executing."),
         ("Advance the clock further and inspect the queue",
          "The expired item is no longer actionable and no automatic execution has occurred for it.")],
        ["The expiry boundary is evaluated against server time; at exactly expires_at the item is no longer approvable.",
         "An expired approval never executes, and expiry is terminal rather than silently renewed.",
         "The expired item's terminal state is recorded in the audit trail with the expiry instant used.",
         "Expiry does not delete the reviewed payload, so the audit trail remains complete."],
        ["Extending the TTL automatically when an operator opens the item.",
         "Falling back to execution when the expiry check errors.",
         "Treating an expired item as cancelled and releasing its reservations without recording why."],
        ["Decision responses before and after expiry with the evaluated instants.",
         "Approval record terminal states and audit rows.",
         "Queue listing after clock advancement."],
        ["Delete " + NS + " approval rows after exporting the expiry audit evidence."],
        "Time is injected at the approval service boundary so the boundary is exact; the service itself, not the test, decides approvability.",
        refs=[IMPL07, API06],
    ),
    case(
        "GOV-APV-WRONG-TENANT", "Tenant isolation: an operator from another tenant cannot decide, and no item state changes",
        APPROVAL_SUITE, "governance", ["SCR-003", "NFR-006", "AUTH-4", "NFR-001"],
        ["entity:Approval"], "baseline", "P0", "critical",
        "An operator of tenant T2 approves a T1 campaign, which is both a cross-tenant control failure and an unreviewed commercial commitment.",
        [GOV_FX, TENANTS_FX],
        _APV_PRE + ["APV-CAMP-15 belongs to T1; the acting session is authenticated as OP-APPROVER-T2 in tenant T2."],
        {"request": {"method": "POST", "path": "/api/v1/approvals/APV-CAMP-15/decision",
                     "headers": {"x-tenant-id": "22222222-2222-2222-2222-222222222222"},
                     "body": {"decision": "APPROVE", "operator_id": "OP-APPROVER-T2", "reason": "Cross-tenant attempt."}},
         "item_tenant": "11111111-1111-1111-1111-111111111111"},
        [("Submit the decision with the T2 session against the T1 item",
          "The gateway refuses with 403 or 404; the response body reveals no T1 payload fields."),
         ("Read the T1 item state",
          "Status is still AWAITING_HUMAN with the same payload_hash and no decided_at."),
         ("Attempt the same request with the tenant header forged to T1",
          "The forged header does not grant access because the session's verified tenant is authoritative; refusal repeats."),
         ("Read the audit rows",
          "The cross-tenant attempts are recorded with the acting tenant and the target item, and no execution row exists.")],
        ["Zero state changes on the foreign item; the payload hash and status are byte-identical before and after.",
         "No T1 payload field is disclosed in the refusal response.",
         "A forged tenant header cannot override the verified session tenant.",
         "Each refused attempt is audited with the mismatch, so the control failure is visible if it ever succeeds."],
        ["Resolving the item by id alone without a tenant predicate.",
         "Leaking the target payload in an error message.",
         "Trusting the client-supplied tenant header over the verified session."],
        ["Refusal responses for both attempts (redacted).",
         "T1 item state and payload hash before/after.",
         "Audit rows with the acting and target tenants."],
        ["Delete " + NS + " refusal audit copies after export; the T1 item is left in its original pending state or cancelled through a legitimate T1 operator."],
        "Real tenant-scoped authorization and gateway middleware under test; the tenant contexts are separate authenticated sessions. The forged-header probe is issued at the HTTP boundary, not inside the service.",
        refs=[IMPL07, SRS],
    ),
    case(
        "GOV-APV-ROLE-DENIED", "Role control: an operator without the approver role cannot decide or see the payload",
        APPROVAL_SUITE, "governance", ["SCR-003", "NFR-001", "AUTH-4"],
        ["entity:Approval"], "baseline", "P0", "critical",
        "Any authenticated user of the tenant can approve high-risk financial actions, so the approval gate becomes decorative.",
        [GOV_FX],
        _APV_PRE + ["OP-VIEWER-T1 holds role VIEWER with an empty decisions list; APV-CAMP-15 is pending in the same tenant."],
        {"viewer_read": {"method": "GET", "path": "/api/v1/approvals/APV-CAMP-15", "operator_id": "OP-VIEWER-T1"},
         "viewer_decide": {"method": "POST", "path": "/api/v1/approvals/APV-CAMP-15/decision",
                           "body": {"decision": "APPROVE", "operator_id": "OP-VIEWER-T1", "reason": "LGTM"}}},
        [("Read the item as the VIEWER operator",
          "The response either omits the item or returns it without the privileged payload fields, and it never exposes the signature context."),
         ("Submit an APPROVE decision as the VIEWER operator",
          "HTTP 403 with a role error; the item remains AWAITING_HUMAN and no execution occurs."),
         ("Submit the same decision as OP-APPROVER-T1",
          "HTTP 200 with status APPROVED, proving the refusal was role-based and not a broken endpoint.")],
        ["The role check is enforced server-side; a VIEWER decision is refused with 403 and zero state change.",
         "The refusal does not leak the risk payload or budget figures.",
         "The authorized operator still succeeds, so the control blocks without breaking the workflow.",
         "The refused attempt is audited with the operator id and the missing permission."],
        ["Enforcing the role only in the UI so an API call bypasses it.",
         "Returning 200 with the decision silently ignored.",
         "Blocking all operators including the approver role."],
        ["403 response body for the viewer decision.",
         "Item state before/after plus the successful authorized decision.",
         "Audit rows for both attempts."],
        ["Delete the " + NS + " approval rows; simulated send is reported as non-recallable."],
        "Real role enforcement at the gateway and service layers; role data sourced from the fixture registry so the matrix is data-driven rather than hardcoded.",
        refs=[IMPL07, SRS],
    ),
    case(
        "GOV-APV-EXECUTION-GAP", "Approval is not execution: APPROVED does not mean the external side effect already happened",
        APPROVAL_SUITE, "governance", ["SCR-003", "AUTH-4", "BR-006", "TC-E2E-008", "NFR-003"],
        ["entity:Approval", "entity:Execution", "stage:EXECUTION"], "blueprint", "P0", "critical",
        "The UI marks the campaign as done when the decision is registered, so an operator stops watching a job that later fails in the adapter and the customer never receives the message.",
        [GOV_FX],
        _APV_PRE + ["The mock EMAIL adapter is scripted to fail the first dispatch attempt with 503 and succeed on retry."],
        {"decision": {"decision": "APPROVE", "operator_id": "OP-APPROVER-T1", "reason": "Reviewed."},
         "adapter_script": [{"attempt": 1, "result": "503"}, {"attempt": 2, "result": "200"}]},
        [("Submit APPROVE and observe the immediate response",
          "The response status is APPROVED with a task id; it does not claim the message was delivered."),
         ("Observe the first dispatch attempt failing",
          "The execution record shows failed with the upstream 503 preserved; the run is not marked completed."),
         ("Let the retry run with the same effect_key",
          "The retry succeeds and exactly one external send is recorded with one receipt."),
         ("Read the run and task records at each stage",
          "Distinct states are visible: approval APPROVED, execution failed then succeeded, task completed only after the receipt.")],
        ["Approval status and execution status are different fields and disagree while the job is failing.",
         "A 503 is never reported to the operator as a successful send.",
         "The retry reuses the effect_key, so the eventual delivery is single, not duplicated.",
         "The task only reaches completed after a verified receipt exists."],
        ["Setting task status completed when the decision is registered.",
         "Reporting success on the queue acknowledgement rather than the provider response.",
         "Creating a second external send on retry."],
        ["Decision response, execution records for both attempts, and the final receipt.",
         "Adapter log with the 503 and the later 200 plus the single effect_key."],
        ["Delete " + NS + " task and execution rows; the single simulated send is reported as non-recallable."],
        "Real approval-to-execution handoff and retry logic under test; the adapter is the substituted boundary and its script makes the failure deterministic.",
        refs=[IMPL07, IMPL08],
    ),
    case(
        "GOV-APV-CONSENT-REVOKED", "Revoked consent between review and release suppresses the approved send",
        APPROVAL_SUITE, "governance", ["SCR-003", "BR-004", "TC-E2E-007", "NFR-008"],
        ["entity:Consent", "entity:Approval", "channel:EMAIL"], "baseline", "P0", "critical",
        "An operator approval is treated as overriding the consent check, so a customer who opted out an hour ago receives the approved campaign.",
        [GOV_FX, CONSENT_FX],
        _APV_PRE + ["cust-a holds EMAIL marketing consent granted at review time; the campaign targets only cust-a in this scenario."],
        {"revoke": {"customer_id": "cust-a", "channel": "EMAIL", "purpose": "marketing", "at": "after approval, before dispatch"},
         "decision": {"decision": "APPROVE", "operator_id": "OP-APPROVER-T1", "reason": "Approved for send."},
         "audience": 1},
        [("Approve the single-recipient campaign",
          "Status becomes APPROVED and the task is queued for dispatch."),
         ("Revoke cust-a EMAIL marketing consent before dispatch runs",
          "The consent record becomes revoked with a revocation timestamp."),
         ("Let the dispatch run",
          "The send is suppressed at dispatch; the EMAIL adapter counter stays at 0 and the recipient is recorded as suppressed."),
         ("Read the approval and suppression records",
          "The approval remains APPROVED and records the reviewer, while the execution records the suppression with the consent snapshot - approval and consent are independent controls.")],
        ["Human approval never substitutes for consent: the suppressed action produces zero external sends.",
         "The suppression is attributed to the specific recipient and channel, not only to the campaign.",
         "The approval record is not rewritten to rejected; the two controls are recorded separately and both are auditable.",
         "The campaign can still be dispatched to any other recipient who holds a valid grant, so the block is scoped, not global."],
        ["Treating an operator approval as consent.",
         "Dropping the entire campaign because one recipient lost consent.",
         "Retrying the suppressed recipient in a loop."],
        ["Approval record with reviewer fields.",
         "Execution suppression record with the consent snapshot and recipient.",
         "Adapter counter log for the EMAIL channel."],
        ["Restore the cust-a consent fixture row and delete " + NS + " approval and execution rows."],
        "Real consent evaluation at dispatch time and real approval persistence under test; the channel adapter is the substituted boundary with a per-recipient counter.",
        refs=[IMPL07, IMPL08],
    ),
    case(
        "GOV-APV-FORGED-TICKET", "Forged approval: a self-declared approval ticket cannot release a prepared action",
        APPROVAL_SUITE, "governance", ["SCR-003", "AUTH-4", "BR-007", "BR-010", "NFR-001"],
        ["entity:Approval", "entity:Action"], "blueprint", "P0", "critical",
        "A prepared high-risk action is released with a hand-written approval identifier in the payload, bypassing the approval centre entirely.",
        [GOV_FX],
        _APV_PRE + ["No approval exists for the run; the payload will claim one."],
        {"proposals": [
             {"label": "fabricated id", "ticket": "APV-FAKE-999", "signature": None},
             {"label": "correct id, no signature", "ticket": "APV-CAMP-15", "signature": None},
             {"label": "correct id, forged signature", "ticket": "APV-CAMP-15", "signature": "hmac-sha256:deadbeef"},
             {"label": "correct id, no operator decision recorded", "ticket": "APV-T2-CAMP", "signature": None}]},
        [("Attempt to release the action with each of the four claimed tickets",
          "All four are refused: the approval is resolved server-side and must exist with a matching signature and a recorded operator decision."),
         ("Inspect the refusal reasons",
          "Each refusal names the specific deficiency (unknown ticket, missing signature, signature mismatch, undecided item)."),
         ("Verify no external effect",
          "The adapter counter is 0 for all four attempts and no task reaches completed.")],
        ["An approval reference supplied by the caller is verified against server state; it is never trusted as evidence.",
         "All four forgeries are refused with distinguishable reasons and zero external effects.",
         "A signature is validated cryptographically, so an arbitrary string cannot pass.",
         "An approval item that exists but was never decided cannot release anything."],
        ["Trusting a caller-provided approval id.",
         "Comparing signatures with a non-constant-time equality that leaks validity.",
         "Falling back to execution when signature verification throws."],
        ["Four refusal records with reasons.",
         "Adapter counter showing zero calls.",
         "Server-side approval resolution log for each claimed ticket."],
        ["Delete " + NS + " attempt records; leave the genuine pending items untouched."],
        "Real signature verification and approval resolution under test. Signatures are generated with a test key held outside the repository; no key material is written to fixtures.",
        prereq=["A test signing key must be provisioned outside the repository (sandbox secret store); the case is BLOCKED_PREREQUISITE without it rather than substituting a fake verification."],
        refs=[IMPL07, IMPL08],
    ),
    case(
        "GOV-APV-NO-SIXTH-DECISION", "Decision enum is closed: no sixth action and no alternate execution route exists",
        APPROVAL_SUITE, "governance", ["SCR-003", "AUTH-4", "API-001", "NFR-007"],
        ["entity:Approval"], "blueprint", "P1", "high",
        "An undocumented decision value or a hidden execute route lets an operator force execution without any of the five controlled decisions, so no control is left.",
        [GOV_FX],
        _APV_PRE + ["APV-CAMP-15 is pending; the gateway route table is enumerable for the tenant."],
        {"direct_decision": {"method": "POST", "path": "/api/v1/approvals/APV-CAMP-15/decision",
                             "body": {"decision": "FORCE_EXECUTE", "operator_id": "OP-APPROVER-T1", "reason": "ship it"}},
         "execute_route": {"method": "POST", "path": "/api/v1/approvals/APV-CAMP-15/execute",
                           "body": {"operator_id": "OP-APPROVER-T1"}},
         "task_edit_route": {"method": "PATCH", "path": "/api/v1/tasks/task-camp-15",
                             "body": {"status": "queued", "operator_id": "OP-APPROVER-T1"}}},
        [("Submit the unknown decision value",
          "HTTP 400 with a validation error listing the five accepted values; the item remains AWAITING_HUMAN."),
         ("Call the undocumented execute route",
          "HTTP 404 or 405; no execution is triggered."),
         ("Attempt to bypass the gate by editing the task status directly",
          "The write is refused and the task state is unchanged; no execution is triggered."),
         ("Confirm the legitimate path still works",
          "A proper APPROVE decision still releases the task, proving the refusals are not a broken endpoint.")],
        ["The decision enum is closed to the five documented values; unknown values are rejected without state change.",
         "No alternate route executes a prepared AUTH-4 action; the documented decision route is the only release path.",
         "Task-state mutation cannot substitute for a decision.",
         "Adapter counter is 0 during all three bypass attempts and 1 after the legitimate decision."],
        ["Registering a debug or admin execute route that survives to production.",
         "Accepting an unknown decision as APPROVE by falling through a switch default.",
         "Allowing a direct task status write to release the payload."],
        ["Three refusal responses with status codes.",
         "Route inventory for the tenant gateway.",
         "Adapter counter log across the attempts."],
        ["Delete " + NS + " approval and task rows; the single simulated send is reported as non-recallable."],
        "Real gateway routing and validation under test; the route inventory is produced from the running gateway rather than from source text, so a hidden route would be detected.",
        refs=[API06, IMPL07],
    ),
    case(
        "GOV-APV-QUEUE-INTEGRITY", "Queue integrity: pending count, ordering and aging match the underlying records",
        APPROVAL_SUITE, "governance", ["SCR-003", "SCR-001", "SRS-17", "NFR-002"],
        ["entity:Approval", "stage:APPROVAL"], "extension", "P1", "high",
        "The dashboard badge and the approval queue disagree, so items silently age past their TTL or operators work on a stale list.",
        [GOV_FX],
        _APV_PRE + ["Three items exist for T1: one pending within TTL, one pending close to TTL, one expired. T2 has one pending item."],
        {"seeded": [{"approval_id": "APV-CAMP-15", "expires_at": "2026-01-15T10:10:00Z", "tenant": "T1"},
                    {"approval_id": "APV-REFUND-450", "expires_at": "2026-01-15T10:25:00Z", "tenant": "T1"},
                    {"approval_id": "APV-OLD-1", "expires_at": "2026-01-15T09:00:00Z", "tenant": "T1"},
                    {"approval_id": "APV-T2-CAMP", "expires_at": "2026-01-15T10:00:00Z", "tenant": "T2"}]},
        [("Fetch the T1 approval queue and the SCR-001 approval_pending indicator",
          "Both report the same actionable count (2) and the expired item is excluded or explicitly marked expired, not counted as actionable."),
         ("Check the ordering",
          "Items are ordered by expiry ascending so the soonest-to-expire appears first."),
         ("Fetch the T1 queue again as an operator and confirm tenant scoping",
          "No T2 item appears in the T1 listing."),
         ("Drive the clock past the second item's expiry and refresh",
          "The actionable count drops to 1 and the newly expired item is shown as expired rather than disappearing without trace.")],
        ["Dashboard indicator and queue listing derive from the same records: counts agree exactly (2, then 1).",
         "Expired items never count as actionable but remain visible with a terminal marker.",
         "Ordering is deterministic by expiry so the most urgent item is first.",
         "Tenant scoping is exact: zero foreign items in the listing."],
        ["Computing the badge from a different query than the list.",
         "Hiding expired items so aging is invisible.",
         "Including another tenant's items to inflate the queue."],
        ["Queue payload and SCR-001 indicator values at both clock points.",
         "Ordered listing with expiry timestamps.",
         "Expired item states."],
        ["Delete " + NS + " approval rows after export."],
        "Real queue query and dashboard projection under test; the clock is injected so aging is deterministic and both surfaces are read from live queries rather than cached copies.",
        refs=[IMPL07, SRS],
    ),
)
