"""Ordered governance testcase section: asm."""
from __future__ import annotations


# ===========================================================================
# governance/asm.md — ASM-001..ASM-005: an unlocked assumption fails closed
# (SRS 26, SRS 28 handoff step 1, implement/09 pilot entry conditions)
# ===========================================================================
_ASM_PRE = [
    "Namespace " + NS + "asm-<case_id>-<worker_id>; the assumption registry is read from fixtures/offline/governance.json assumptions and no lock may be granted, forged, cached or edited inside the run.",
    "Frozen clock " + CLOCK + "; the harness records exactly one outcome per dependent capability - EXECUTED, BLOCKED_PREREQUISITE or SKIP_ASM_<n> - and refuses to re-label a skip as PASS.",
]
_ASM_AUTO = ("The policy-parameter resolver, the PEP and the run-report writer run as real code under test; the unlocked assumption is "
             "configuration, not a substituted boundary. The oracle is the run-report status plus the adapter effect counters, so a "
             "capability that executes while its assumption is unlocked fails the case instead of passing it.")
_ASM_SCOPE = ("Capabilities that do not depend on the unlocked assumption run in the same pass, so the case can distinguish "
              "'blocked because the lock is missing' from 'everything was switched off'.")

_add(
    case(
        "GOV-ASM-001", "ASM-001 unlocked: live connector work is SKIP_ASM_001 while offline and unit work still runs",
        ASM_SUITE, "governance", ["ASM-001", "NFR-001", "TC-E2E-006", "SRS-02"],
        ["entity:Agent", "stage:ACTION", "channel:EMAIL"], "baseline", "P0", "critical",
        "A connector is enabled on the strength of an implicit assumption, so the platform sends to real recipients before the production connector allowlist exists and the first real message is the incident.",
        [GOV_FX, ENV_EXAMPLE],
        _ASM_PRE + ["assumptions.ASM-001.locked is false and no production connector allowlist artifact exists in the repository or the run environment.",
                    "One live-connector capability and two independent capabilities (an offline mock journey and an authority unit case) are registered in the same run plan."],
        {"assumptions": {"ASM-001": {"locked": False, "owner": "Product/IT",
                                     "locks": ["production connector allowlist"],
                                     "blocks": ["live channel dispatch"],
                                     "does_not_block": ["offline mock journeys", "authority unit cases"]}},
         "capabilities": [
             {"label": "live channel dispatch", "depends_on": ["ASM-001"], "expected_status": "SKIP_ASM_001"},
             {"label": "offline mock journey", "depends_on": [], "expected_status": "EXECUTED"},
             {"label": "authority unit case", "depends_on": [], "expected_status": "EXECUTED"}],
         "env_example": {"ASM_001_CONNECTOR_LOCK": "not_set", "note": "fixtures/live/env.example is a checklist, not an approval"}},
        [("Read the assumption registry and resolve ASM-001 for the run",
          "ASM-001 is reported unlocked with owner Product/IT; the live-connector capability is marked dependent and cannot be entered."),
         ("Attempt to start the live channel dispatch",
          "The capability is refused before any connector call and is reported SKIP_ASM_001; no credential is loaded and the provider call counter stays 0."),
         ("Run the two capabilities that do not depend on ASM-001",
          "The offline mock journey and the authority unit case both execute and report EXECUTED in the same run."),
         ("Attempt to have the skip counted as a pass",
          "The run report keeps SKIP_ASM_001 as its own status; a summary that reports the gate as passed is rejected because a skipped capability is neither PASS nor FAIL.")],
        ["The live-connector capability never executes while ASM-001 is unlocked: provider call counter is 0 and no credential was read.",
         "The dependent capability is reported SKIP_ASM_001, which is distinct from PASS and from FAIL, and no summary may collapse it into either.",
         "The two independent capabilities still execute in the same run, so the missing lock is scoped rather than a global stop.",
         "No run path can set assumptions.ASM-001.locked to true: the registry is read-only for the run and the lock can only come from the owner outside the platform."],
        ["Granting the connector lock from agent input, a request header or a test fixture.",
         "Substituting a mock connector and reporting the live capability as passed.",
         "Blocking the offline mock journey and authority unit cases because a live lock is missing."],
        ["Assumption registry snapshot showing ASM-001 unlocked with its owner.",
         "Run-report rows for the three capabilities with SKIP_ASM_001 / EXECUTED / EXECUTED.",
         "Provider call counter proving zero live dispatches."],
        ["Delete " + NS + " run-report rows; no provider state was created, so nothing has to be retired."],
        _ASM_AUTO + " " + _ASM_SCOPE,
        prereq=["The production connector allowlist (ASM-001, owner Product/IT) is not locked; live connector execution is unavailable and any attempt to report it PASS is a defect in the report, not a result."],
        refs=[IMPL09, IMPL08, SRS],
    ),
    case(
        "GOV-ASM-002", "ASM-002 unlocked: KPI targets are BLOCKED_PREREQUISITE while formulas and safety invariants stay testable",
        ASM_SUITE, "governance", ["ASM-002", "NFR-002", "SRS-20"],
        ["kpi:Policy Violation Rate", "stage:OUTCOME"], "baseline", "P1", "critical",
        "A target is invented to make a dashboard look green, so the pilot is declared successful against a number nobody approved and the real baseline is never bought.",
        [GOV_FX],
        _ASM_PRE + ["assumptions.ASM-002.locked is false and no approved baseline or target set exists; the KPI dictionary figures in fixtures/offline/governance.json kpi_dataset are labelled synthetic test configuration.",
                    "The KPI evaluation run is configured to separate formula correctness from target compliance."],
        {"assumptions": {"ASM-002": {"locked": False, "owner": "Business",
                                     "locks": ["KPI baseline and targets"],
                                     "blocks": ["pass/fail KPI target assertions"],
                                     "does_not_block": ["formula evaluation", "safety invariants"]}},
         "evaluations": [
             {"label": "formula arithmetic", "kind": "FORMULA", "expected_status": "EXECUTED"},
             {"label": "target compliance", "kind": "TARGET", "expected_status": "BLOCKED_PREREQUISITE"},
             {"label": "zero-tolerance safety invariant", "kind": "SAFETY_INVARIANT", "expected_status": "EXECUTED"}],
         "proposed_target_invented": False},
        [("Evaluate the KPI formulas against the synthetic dataset",
          "Every metric is computed and reported with its window, unit and source; the run is EXECUTED because formulas do not need a target."),
         ("Attempt the target-compliance evaluation",
          "It is reported BLOCKED_PREREQUISITE naming ASM-002 and owner Business; no pass/fail verdict is issued and no target value is displayed."),
         ("Check the two zero-tolerance safety invariants",
          "Policy Violation Rate and Duplicate Execution are still evaluated and must be exactly 0, because a safety invariant is not a baseline-dependent target."),
         ("Attempt to publish a target figure from the synthetic dataset",
          "The publication is refused: a synthetic figure cannot become an approved target, and the report labels the value as test configuration only.")],
        ["Target compliance is BLOCKED_PREREQUISITE, never PASS and never a substituted number; the blocker names ASM-002 and its owner.",
         "Formula evaluation and the two zero-tolerance invariants still run, so the missing baseline does not disable measurement safety.",
         "No target value appears anywhere in the report as an approved commitment; the synthetic figures stay labelled as test configuration.",
         "The safety invariants remain hard requirements: they are not relaxed, weighted by sample size, or deferred to a later baseline."],
        ["Inventing a target so the pilot reads as successful.",
         "Reporting a blocked target evaluation as a pass because the formula ran.",
         "Treating a synthetic dashboard figure as an approved target after the fact."],
        ["Run-report rows for the three evaluations with their statuses.",
         "Assumption registry snapshot showing ASM-002 unlocked with owner Business.",
         "KPI dictionary extract showing which metrics depend on a target and which are safety invariants."],
        ["Delete " + NS + " evaluation rows after export."],
        _ASM_AUTO,
        prereq=["The KPI baseline and targets (ASM-002, owner Business) are not locked, so a pass/fail KPI target verdict is BLOCKED_PREREQUISITE; only formulas and safety invariants may be evaluated."],
        refs=[ANALYTICS, IMPL09, SRS],
    ),
    case(
        "GOV-ASM-003", "ASM-003 unlocked: the synthetic 0.15 discount and 5000 audience are not an approved discount policy",
        ASM_SUITE, "governance", ["ASM-003", "NFR-008", "BR-002", "AUTH-4"],
        ["entity:Campaign", "stage:APPROVAL", "kpi:Campaign Revenue"], "baseline", "P3", "critical",
        "A number that was written down only to exercise boundary arithmetic is promoted into an autonomous discount limit, so the AI grants discounts nobody approved and margin is lost quietly at scale.",
        [GOV_FX],
        _ASM_PRE + ["assumptions.ASM-003.locked is false; policy_parameters.T1_UNLOCKED has maxAutonomousDiscountRate, maxAutonomousRefundAmount and maxAutonomousAudienceSize all null.",
                    "policy_parameters.T1_SYNTHETIC_TEST_LOCK additionally holds 0.15, 5000 and a 500 TWD refund figure, and is explicitly marked 'NOT an owner approval' in the fixture."],
        {"assumptions": {"ASM-003": {"locked": False, "owner": "Business/Finance",
                                     "locks": ["max autonomous discount rate", "max campaign audience"],
                                     "blocks": ["autonomous discount and broadcast"],
                                     "does_not_block": ["AUTH-0..AUTH-2 reads", "FAQ replies"]}},
         "policy_parameters_considered": {"T1_UNLOCKED": {"maxAutonomousDiscountRate": None,
                                                          "maxAutonomousAudienceSize": None},
                                          "T1_SYNTHETIC_TEST_LOCK": {"maxAutonomousDiscountRate": 0.15,
                                                                     "maxAutonomousAudienceSize": 5000}},
         "requests": [
             {"label": "autonomous discount quote", "discount_rate": 0.10, "skill": "skill.sales.check_price",
              "expected_status": "BLOCKED_PREREQUISITE"},
             {"label": "campaign broadcast", "audience_size": 5000, "skill": "skill.mkt.dispatch_campaign",
              "expected_status": "BLOCKED_PREREQUISITE"},
             {"label": "price read for a customer", "skill": "skill.sales.check_price",
              "expected_status": "EXECUTED"}]},
        [("Resolve the discount and audience limits for tenant T1",
          "Both limits resolve to undefined because ASM-003 is unlocked; the synthetic test values are labelled as test configuration and are not used as limits."),
         ("Attempt a 0.10 autonomous discount quote",
          "The discount is refused with BLOCKED_PREREQUISITE naming ASM-003; the refusal is not silently converted into a human-approval path with the synthetic limit as the threshold."),
         ("Attempt a campaign broadcast to the 5000-address synthetic audience",
          "The broadcast is refused before any audience is materialised or dispatched; the synthetic audience size is not treated as an approved ceiling."),
         ("Run an AUTH-0 read in the same pass",
          "The price read executes normally, proving the missing ASM-003 lock blocks only the dependent discount and broadcast capabilities.")],
        ["With ASM-003 unlocked, zero autonomous discounts and zero campaign dispatches occur; the adapter counters are 0.",
         "The synthetic values 0.15, 5000 and 500 TWD are never reported as approved limits, thresholds or production policy, and never appear in a customer-facing message.",
         "The refusal is typed BLOCKED_PREREQUISITE naming ASM-003 and owner Business/Finance, so an operator can tell it apart from a policy denial under a locked limit.",
         "Read-only AUTH-0..AUTH-2 capabilities continue to work in the same pass."],
        ["Promoting a synthetic fixture value into an approved policy parameter.",
         "Treating 'no limit configured' as 'no limit applies' and granting the discount.",
         "Falling back to the T2 tenant's configured limits for a T1 request."],
        ["Refusal records for the discount and broadcast with the ASM-003 reason.",
         "Policy-parameter resolution trace showing null limits and the synthetic values kept separate.",
         "Adapter counters and the successful AUTH-0 read as the scoping contrast."],
        ["Delete " + NS + " refusal rows; no audience snapshot was created and nothing was dispatched."],
        _ASM_AUTO,
        prereq=["The discount and promotion thresholds (ASM-003, owner Business/Finance) are not locked, so autonomous discount and broadcast are BLOCKED_PREREQUISITE and the fixture's 0.15 / 5000 figures may not be used as limits."],
        refs=[ANALYTICS, IMPL08, SRS],
    ),
    case(
        "GOV-ASM-004", "ASM-004 unlocked: autonomous refund is blocked and 500 TWD is not an approved refund cap",
        ASM_SUITE, "governance", ["ASM-004", "AUTH-4", "FR-CS-002", "NFR-008"],
        ["entity:Approval", "stage:APPROVAL", "entity:Service Case"], "baseline", "P1", "critical",
        "Refund types that require human approval are guessed from an illustrative amount, so money leaves the business on an AI decision nobody authorised and the loss is only visible at reconciliation.",
        [GOV_FX, ORDERS_FX],
        _ASM_PRE + ["assumptions.ASM-004.locked is false and the list of refund/compensation types requiring approval is empty, so the required approval set is unknown rather than empty.",
                    "The fixture carries a synthetic 500 TWD figure inside T1_SYNTHETIC_TEST_LOCK that is explicitly not an owner approval; ORD-A-1 exists in the offline order fixture."],
        {"assumptions": {"ASM-004": {"locked": False, "owner": "Finance/Operations",
                                     "locks": ["refund and compensation types requiring approval"],
                                     "blocks": ["autonomous refund"],
                                     "does_not_block": ["order status lookup", "case management"]}},
         "refunds": [{"label": "autonomous refund", "order_id": "ORD-A-1", "amount_twd": 450.0,
                      "skill": "skill.care.initiate_return", "expected_status": "BLOCKED_PREREQUISITE"},
                     {"label": "order status lookup", "order_id": "ORD-A-1",
                      "skill": "skill.care.lookup_order", "expected_status": "EXECUTED"},
                     {"label": "case note", "skill": "skill.care.manage_case", "expected_status": "EXECUTED"}],
         "synthetic_cap_twd": 500.0},
        [("Resolve the refund types that require approval",
          "The registry reports the required set as unknown because ASM-004 is unlocked; an unknown set is treated as 'all refunds require approval', not as 'none'."),
         ("Attempt an autonomous 450 TWD refund on ORD-A-1",
          "The refund is refused with BLOCKED_PREREQUISITE naming ASM-004; it is not auto-approved on the grounds that 450 is below the synthetic 500 TWD figure."),
         ("Check the order lookup and the case note",
          "Both execute and the case records the blocked refund attempt with its reason, so the customer conversation is not abandoned."),
         ("Attempt to raise the synthetic 500 TWD figure into an approved cap",
          "The attempt is refused and the value remains labelled as synthetic test configuration in the report.")],
        ["Zero refunds and zero payment reversals execute while ASM-004 is unlocked; the payment adapter counter is 0.",
         "An unknown approval set fails closed: the platform escalates to a human instead of inferring that no approval is needed.",
         "The 500 TWD synthetic figure is never used as an approval threshold, a cap or a policy statement, and never appears in a customer-facing message.",
         "Order lookup and case management continue to work, and the blocked attempt is visible in the case history with its reason."],
        ["Treating an empty or unknown approval list as 'no approval required'.",
         "Auto-approving a refund below a figure taken from a synthetic fixture.",
         "Deleting the blocked attempt from the case so the customer sees an unexplained refusal."],
        ["Refusal record for the refund with the ASM-004 reason and the approver requirement.",
         "Payment adapter counter showing zero reversals.",
         "Case history excerpt showing the blocked attempt plus the successful lookup."],
        ["Delete " + NS + " case and refusal rows; no money moved, so no provider reversal is needed."],
        _ASM_AUTO,
        prereq=["The refund/compensation types requiring approval (ASM-004, owner Finance/Operations) are not locked, so autonomous refund is BLOCKED_PREREQUISITE and the synthetic 500 TWD figure is not a cap."],
        refs=[IMPL08, SRS],
    ),
    case(
        "GOV-ASM-005", "ASM-005 unlocked: Customer 360 fields without a storage decision are not persisted long term",
        ASM_SUITE, "governance", ["ASM-005", "FR-C360-002", "NFR-006", "SRS-16"],
        ["memory:Customer Context", "entity:Customer", "stage:CONTEXT"], "baseline", "P0", "critical",
        "Fields nobody approved for long-term storage are persisted anyway, so sensitive profile data accumulates without a legal basis and a later deletion request cannot be satisfied.",
        [GOV_FX, CUST_FX],
        _ASM_PRE + ["assumptions.ASM-005.locked is false and the list of Customer 360 fields allowed for long-term storage is empty, so allowed-set membership is unknown for every field.",
                    "A session-scoped lookup for cust-a is available and the run can inspect every key written to the durable store."],
        {"assumptions": {"ASM-005": {"locked": False, "owner": "Data/Legal/Product",
                                     "locks": ["Customer 360 fields allowed for long-term storage"],
                                     "blocks": ["long-term persistence of unlisted fields"],
                                     "does_not_block": ["session-scoped lookup"]}},
         "candidates": [{"label": "session-scoped profile read", "scope": "SESSION", "expected_status": "EXECUTED"},
                        {"label": "durable profile write", "scope": "LONG_TERM", "fields": ["customer_id", "lifetime_order_count"],
                         "expected_status": "BLOCKED_PREREQUISITE"},
                        {"label": "durable contact write", "scope": "LONG_TERM", "fields": ["customer_id", "channel_handle"],
                         "expected_status": "BLOCKED_PREREQUISITE"}]},
        [("Read the Customer 360 profile for cust-a inside the session",
          "The read succeeds and the data is held only for the session; nothing is written to the durable store."),
         ("Attempt to persist the two long-term write candidates",
          "Both writes are refused with BLOCKED_PREREQUISITE naming ASM-005, because allowed-set membership is unknown and an unknown set fails closed."),
         ("Inspect the durable store for keys written during the run",
          "No customer field rows were created; only namespace and audit keys exist, and the audit rows record the refused writes."),
         ("Attempt to store the fields after marking them as consented by the caller",
          "The refusal stands: a caller-supplied consent or verification flag cannot widen the allowed field set.")],
        ["Zero long-term customer-field rows are created while ASM-005 is unlocked; the durable store contains no customer profile data after the run.",
         "An unknown allowed-field set fails closed for every field, including fields that look harmless.",
         "Session-scoped lookup still works, so customer service is not disabled by the missing legal decision.",
         "No payload field, header or consent claim provided by the caller can widen the allowed set, and refused writes are audited rather than dropped."],
        ["Persisting customer fields 'temporarily' in a durable store and deleting them later.",
         "Treating a caller-asserted consent or verification_status payload as authority to store.",
         "Blocking session-scoped reads and breaking customer care as a side effect."],
        ["Durable-store key listing after the run showing no customer field rows.",
         "Refusal records for both write attempts with the ASM-005 reason.",
         "Audit rows for the refused writes plus the successful session-scoped read."],
        ["Delete " + NS + " session cache entries and refusal rows; confirm the durable store holds no customer field data."],
        _ASM_AUTO,
        prereq=["The Customer 360 long-term-storage field list (ASM-005, owner Data/Legal/Product) is not locked, so long-term persistence of unlisted fields is BLOCKED_PREREQUISITE while session-scoped lookup remains available."],
        refs=[IMPL08, SRS],
    ),
    case(
        "GOV-ASM-INDEPENDENCE", "All five assumptions unlocked at once: each dependency is blocked for its own reason",
        ASM_SUITE, "governance", ["ASM-001", "ASM-002", "ASM-003", "ASM-004", "ASM-005", "NFR-001"],
        ["entity:Agent", "stage:DECISION"], "blueprint", "P0", "critical",
        "One missing assumption is treated as a global outage, or five missing assumptions collapse into a single 'environment not ready' message, so nobody can tell which owner has to act and unrelated work is stopped for no reason.",
        [GOV_FX, ENV_EXAMPLE],
        _ASM_PRE + ["All five assumptions are unlocked simultaneously and each dependent capability is registered in one run plan.",
                    "A capability that depends on none of the five assumptions is also registered, so the run can prove the blocks are scoped."],
        {"assumptions": {"ASM-001": {"locked": False}, "ASM-002": {"locked": False}, "ASM-003": {"locked": False},
                         "ASM-004": {"locked": False}, "ASM-005": {"locked": False}},
         "capabilities": [
             {"label": "live channel dispatch", "depends_on": ["ASM-001"], "expected_status": "SKIP_ASM_001"},
             {"label": "KPI target verdict", "depends_on": ["ASM-002"], "expected_status": "BLOCKED_PREREQUISITE"},
             {"label": "autonomous discount", "depends_on": ["ASM-003"], "expected_status": "BLOCKED_PREREQUISITE"},
             {"label": "autonomous refund", "depends_on": ["ASM-004"], "expected_status": "BLOCKED_PREREQUISITE"},
             {"label": "long-term customer field write", "depends_on": ["ASM-005"], "expected_status": "BLOCKED_PREREQUISITE"},
             {"label": "authority unit case", "depends_on": [], "expected_status": "EXECUTED"}]},
        [("Resolve all five assumptions for the run",
          "Every one is reported unlocked with its owner, and each dependent capability carries the identifier of the assumption it needs."),
         ("Run the five dependent capabilities",
          "Each is blocked with its own reason naming its own assumption and owner; no capability reports a generic environment failure and none reports PASS."),
         ("Run the capability that depends on none of the assumptions",
          "It executes normally, proving the blocks are scoped per assumption rather than a global stop."),
         ("Attempt to unblock one capability by editing the registry from the run",
          "The registry write is refused and the capability stays blocked, so a lock can only come from the owning human outside the platform.")],
        ["Each of the five blockers is reported separately with its own assumption identifier and owner; no two capabilities share a blanket failure reason.",
         "A capability with no dependency executes while five assumptions are unlocked, so the fail-closed behaviour is scoped and does not become a tenant-wide outage.",
         "The skip for ASM-001 remains SKIP_ASM_001 rather than a blocked or passed status, and no dependent capability is summarised as PASS.",
         "No run path can flip an assumption to locked or persisted, which keeps the human owner in control of the decision."],
        ["Collapsing five blockers into one generic error.",
         "Disabling capabilities that depend on none of the unlocked assumptions.",
         "Letting the platform grant its own lock so the run can proceed."],
        ["Run-report rows for the six capabilities with their per-assumption reasons.",
         "Assumption registry snapshot for all five assumptions with owners.",
         "Registry write-attempt refusal record."],
        ["Delete " + NS + " run-report rows after export; the registry itself is left unchanged."],
        _ASM_AUTO + " " + _ASM_SCOPE,
        prereq=["All five assumptions are unlocked in this repository, so every dependent capability is SKIP_ASM_001 or BLOCKED_PREREQUISITE and only the independent capability may execute."],
        refs=[IMPL09, IMPL08, SRS],
    ),
)
