"""Ordered governance testcase section: authority."""
from __future__ import annotations


# ===========================================================================
# unit/authority.md — AUTH-0..AUTH-5 verdict model (SRS 12, implement/08 1.1)
# ===========================================================================
_AUTH_PRE = [
    "Namespace " + NS + "unit-auth-<case_id>-<worker_id>; no shared mutable state with other cases.",
    "PolicyEnforcementPoint loaded with fixtures/offline/governance.json skill_authority_registry and agents[]; clock frozen at " + CLOCK + ".",
]

_add(
    case(
        "UNIT-AUTH-0", "AUTH-0 Observe grant: verified read permitted, every mutating tool denied",
        AUTH_SUITE, "unit", ["AUTH-0", "BR-008", "NFR-001", "TC-E2E-006"],
        ["entity:Agent", "stage:DECISION"], "baseline", "P0", "critical",
        "An observe-only agent silently gains a write path and mutates customer data or sends a message while claiming to be read-only.",
        [GOV_FX, CUST_FX],
        _AUTH_PRE,
        {"agent_id": "SAL-01", "assigned_authority": "AUTH-0", "session_customer": "cust-a",
         "proposals": [
             {"skill": "skill.sales.retrieve_customer", "tool": "API-001.CustomerConnector", "payload": {"customer_id": "cust-a"}},
             {"skill": "skill.sales.check_price", "tool": "API-001.PricingConnector", "payload": {"sku_id": "SKU-OK"}},
             {"skill": "skill.sales.create_cart", "tool": "API-001.CartConnector", "payload": {"customer_id": "cust-a", "sku_id": "SKU-OK", "qty": 1}},
             {"skill": "skill.sales.send_message", "tool": "ADPT-EMAIL-001", "payload": {"customer_id": "cust-a", "template": "order_status"}}]},
        [("Authenticate SAL-01 and assert the enforcement context reports agentAssignedAuthority AUTH-0",
          "Context shows AUTH-0; authority is read from the server-side agent record, not the proposal."),
         ("Submit the two read proposals (retrieve_customer, check_price) in order",
          "Both return authorized=true with decisionCode PERMIT and the connector is called exactly twice."),
         ("Submit the two mutating proposals (create_cart, send_message)",
          "Both return authorized=false; the mutating connectors are never invoked (zero calls recorded at the connector test sink)."),
         ("Inspect the audit rows written for all four proposals",
          "Four rows exist; the two mutating rows carry authority AUTH-0 and execution_status denied, the two read rows carry success.")],
        ["Exactly 2 read connector calls and 0 mutating connector calls are observed at the connector test sink.",
         "Both mutating proposals return decisionCode DENY_* / authorized=false with rationale naming AUTH-0, not AUTH-5.",
         "No cart row and no outbound message row exists in the mock SoR after the run.",
         "Audit rows record execution_status denied for the rejected pair without fabricating an outcome field."],
        ["A write executed at AUTH-0 because the proposal declared a higher required authority.",
         "A denied read (over-blocking) that would break the AUTH-0 read path.",
         "Treating AUTH-0 as a lower rank that can be silently upgraded by the LLM."],
        ["PEP decision JSON for the 4 proposals (authorized, decisionCode, rationale).",
         "Connector test-sink call log with call counts and tool names, redacted.",
         "agentos.audit_records rows for the run (18 fields, customer pseudonymized)."],
        ["Delete the " + NS + " run namespace rows (audit retention copy exported first); leave pre-existing sandbox rows untouched."],
        "Real PEP interceptor and Business Rules Engine under test; API-001 connectors substituted by the offline mock SoR whose call log is the oracle. Deterministic: no sleeps, proposals submitted sequentially with awaited receipts.",
        refs=[SRS, IMPL08],
    ),
    case(
        "UNIT-AUTH-1", "AUTH-1 Recommend: hypothesis-only output, publishing recommendation denied",
        AUTH_SUITE, "unit", ["AUTH-1", "SAL-03", "BR-008", "NFR-001"],
        ["entity:Agent", "stage:HYPOTHESIS"], "baseline", "P0", "critical",
        "A recommend-only agent publishes a cross-sell recommendation to a customer channel, creating an outbound contact with no consent check and no approval.",
        [GOV_FX, CATALOG_FX],
        _AUTH_PRE,
        {"agent_id": "SAL-01", "assigned_authority": "AUTH-1", "session_customer": "cust-a",
         "recommendation": {"customer": "cust-a", "product": "SKU-OK", "reason": "repeat cycle reached",
                            "evidence": "ORD-A-1", "eligibility": "active", "confidence": 0.72, "expected_outcome": "repurchase"},
         "publish_attempt": {"channel": "EMAIL", "purpose": "marketing", "audience": 1}},
        [("Submit skill.sales.recommend_product for cust-a",
          "Returns authorized=true with decisionCode PERMIT and a payload whose status is hypothesis/recommendation, not action."),
         ("Attempt to publish the same recommendation to the EMAIL channel",
          "Enforcement returns authorized=false; no channel adapter is called."),
         ("Read the stored recommendation record and its audit row",
          "Recommendation is stored internally with customer, product, reason, evidence, eligibility, confidence and expected_outcome; audit authority is AUTH-1.")],
        ["The recommendation payload carries all seven contract fields and is marked as a proposal, never as an executed action.",
         "0 calls reach the EMAIL adapter test sink for the publish attempt.",
         "The audit row for the publish attempt records execution_status denied and authority AUTH-1.",
         "The stored recommendation is retrievable by the customer scope only (no cross-customer read)."],
        ["Silently upgrading AUTH-1 to an outbound send because the recommendation confidence is high.",
         "Storing a recommendation without a reason or without evidence.",
         "Recording a success outcome for a recommendation that was never accepted by the customer."],
        ["Stored recommendation record (seven fields) exported as JSON.",
         "PEP decision JSON for both proposals.",
         "Channel adapter test-sink log showing zero publish calls."],
        ["Remove the " + NS + " recommendation rows and namespace keys; retain the audit chain copy."],
        "Real PEP plus the recommendation contract under test; only the channel adapter is the substituted vendor boundary and it exposes a call counter used as the oracle. Frozen clock makes cycle arithmetic deterministic.",
        refs=[SRS, IMPL08],
    ),
    case(
        "UNIT-AUTH-2", "AUTH-2 Draft: draft stored in internal state store, outbound dispatch blocked",
        AUTH_SUITE, "unit", ["AUTH-2", "MKT-03", "BR-008", "NFR-001"],
        ["entity:Agent", "stage:PLAN", "channel:EMAIL"], "baseline", "P0", "critical",
        "Draft campaign copy is transmitted to a customer or ad network directly from the drafting skill, bypassing Brand Guardian review and approval.",
        [GOV_FX, KNOW_FX],
        _AUTH_PRE,
        {"agent_id": "MKT-05", "assigned_authority": "AUTH-2",
         "draft": {"campaign_id": "CMP-DRAFT-1", "channel": "EMAIL", "subject": "January restock",
                   "body": "Synthetic body referencing brand/voice.md and prohibited-claims.md"},
         "dispatch_attempt": {"channel": "EMAIL", "audience_size": 500}},
        [("Submit skill.mkt.generate_content for CMP-DRAFT-1",
          "Returns authorized=true, PERMIT, and the payload is written to the internal draft state store keyed by tenant and campaign."),
         ("Attempt to dispatch the draft to the EMAIL adapter",
          "Enforcement returns authorized=false; the outbound dispatch path is never entered."),
         ("Attempt a second dispatch through the connector directly (bypassing the PEP entry point)",
          "The gateway rejects the call before the adapter is reached; the adapter call counter stays at 0.")],
        ["Draft exists in the internal store with status draft and no provider message id.",
         "0 outbound calls at the EMAIL adapter test sink across both dispatch attempts.",
         "Audit contains one success row (draft) and two denied rows, all with authority AUTH-2.",
         "No customer-visible artifact exists for CMP-DRAFT-1."],
        ["Draft state being treated as a published campaign.",
         "A direct connector call succeeding when it did not come through the PEP.",
         "Counting a blocked dispatch as a delivered message."],
        ["Draft state-store object dump for the run namespace.",
         "Gateway rejection response bodies for the direct connector call.",
         "Adapter test-sink counter output."],
        ["Purge the " + NS + " draft state-store keys and namespace; keep audit rows."],
        "Real PEP and draft state store under test; the EMAIL adapter and the gateway allowlist are substituted boundaries whose call counters are the oracle. No timing dependence.",
        refs=[SRS, IMPL08],
    ),
    case(
        "UNIT-AUTH-3", "AUTH-3 Bounded Execute: in-cap action permitted, over-cap action routes to approval",
        AUTH_SUITE, "unit", ["AUTH-3", "BR-007", "BR-008", "NFR-008", "ASM-003"],
        ["entity:Agent", "stage:ACTION", "stage:APPROVAL"], "blueprint", "P0", "critical",
        "An agent executes an action above the tenant autonomy limit without human approval, or a within-limit action is wrongly blocked, breaking throughput or governance.",
        [GOV_FX],
        _AUTH_PRE + ["Synthetic test lock T1_SYNTHETIC_TEST_LOCK loaded (reminder cap 2, discount cap 0.15) purely to exercise boundary arithmetic; it is NOT an owner approval."],
        {"agent_id": "CS-01", "assigned_authority": "AUTH-3",
         "in_cap": {"skill": "skill.sales.send_message", "payload": {"purpose": "transactional", "reminder_count": 2, "customer_id": "cust-a"}},
         "over_cap": {"skill": "skill.sales.send_message", "payload": {"purpose": "marketing", "reminder_count": 3, "customer_id": "cust-a"}},
         "unknown_limit": {"skill": "skill.mkt.dispatch_campaign", "payload": {"audience_size": 12000}}},
        [("Submit the in-cap action (reminder_count 2 equals the synthetic cap)",
          "authorized=true with decisionCode PERMIT and the message is dispatched once."),
         ("Submit the over-cap action (reminder_count 3)",
          "authorized=false with decisionCode LIMIT_EXCEEDED; no additional dispatch occurs."),
         ("Submit the action whose governing limit is undefined (T1_UNLOCKED audience size)",
          "decisionCode REQUIRE_HUMAN_APPROVAL and an approval ticket id is returned; nothing is dispatched."),
         ("Read the audit rows for all three proposals",
          "Three rows with authority AUTH-3, statuses success / denied / denied, and the routed one carries an approval ticket reference.")],
        ["The boundary is inclusive: reminder_count 2 permits, reminder_count 3 does not.",
         "An undefined policy limit never means unlimited: the action is routed to approval rather than executed.",
         "Adapter dispatch counter is exactly 1 across all three actions.",
         "LIMIT_EXCEEDED and REQUIRE_HUMAN_APPROVAL are distinct decision codes on the two blocked actions."],
        ["Treating an unset limit as unlimited and executing the broadcast.",
         "Silently dropping the over-cap message instead of returning a typed decision and routing it.",
         "Reusing the within-cap action result as the over-cap result (mock echo)."],
        ["PEP decision JSON for the three proposals including decisionCode and approvalTicketId.",
         "Adapter dispatch counter and audit rows for the run.",
         "Approval queue snapshot showing exactly one new AWAITING_HUMAN item."],
        ["Cancel the created approval ticket through the sandbox approval API; delete the " + NS + " message rows."],
        "Real PEP boundary check with a tenant policy source; the message adapter is a substituted boundary exposing a counter. Synthetic lock is supplied through the policy source, never hardcoded in the rule engine.",
        prereq=["Owner-approved autonomy limits do not exist; this case runs only against the labelled synthetic test lock and must not be reported as policy acceptance."],
        refs=[SRS, IMPL08],
    ),
    case(
        "UNIT-AUTH-4", "AUTH-4 verdict: prepared action halts in awaiting_human and is not executed",
        AUTH_SUITE, "unit", ["AUTH-4", "BR-007", "SCR-003", "NFR-007", "TC-E2E-002"],
        ["entity:Agent", "entity:Approval", "stage:APPROVAL"], "baseline", "P0", "critical",
        "A refund or campaign classified AUTH-4 executes autonomously because the amount was below an assumed threshold, producing an unauthorized financial action.",
        [GOV_FX, ORDERS_FX],
        _AUTH_PRE + ["Approval APV-REFUND-450 exists in AWAITING_HUMAN with payload_hash recorded from its creation."],
        {"agent_id": "CS-01", "assigned_authority": "AUTH-3",
         "proposal": {"skill": "skill.care.initiate_return", "approval_id": "APV-REFUND-450",
                      "payload": {"order_id": "ORD-A-1", "refund_amount_twd": 450, "reason_code": "NOT_AS_DESCRIBED"}}},
        [("Submit the refund proposal whose skill requires AUTH-4",
          "Enforcement returns authorized=false with decisionCode REQUIRE_HUMAN_APPROVAL and a non-empty approvalTicketId."),
         ("Query the task and approval state immediately after the call",
          "Task state is awaiting_human and the approval state is AWAITING_HUMAN; the return connector has not been called."),
         ("Query the SoR for a return or refund transaction on ORD-A-1",
          "No refund transaction exists; ORD-A-1 remains in its original status SHIPPED.")],
        ["The action is trapped in awaiting_human and never reported as executed or completed.",
         "Zero calls to the returns/payment adapter for an undecided AUTH-4 action.",
         "The approval ticket records approver_id unset and signed_at unset, so no signed release exists.",
         "AUTH-4 is handled as a routing verdict: the audit row authority value is AUTH-4 while the agent assigned authority stays AUTH-3."],
        ["Executing before a signed human decision exists.",
         "Recording execution_status success while the task is still awaiting_human.",
         "Presenting AUTH-4 as a rank the agent has been granted."],
        ["PEP decision JSON plus the created approval ticket row.",
         "Mock SoR return/payment adapter call log showing zero refund calls.",
         "Task-state snapshot showing awaiting_human with signed_at null."],
        ["Cancel APV-REFUND-450 through the sandbox approval API and delete the " + NS + " task rows."],
        "Real PEP, business rules and approval-queue persistence under test; the returns adapter is substituted and exposes a call log. Condition-based wait on the task state, never a fixed sleep.",
        refs=[SRS, IMPL08, API06],
    ),
    case(
        "UNIT-AUTH-5", "AUTH-5 verdict: hard deny, never queued, security alert audited",
        AUTH_SUITE, "unit", ["AUTH-5", "BR-008", "NFR-001", "TC-E2E-006", "NFR-002"],
        ["entity:Agent", "stage:APPROVAL"], "baseline", "P0", "critical",
        "A prohibited action such as raw cross-tenant dataset export is queued for human approval and then approved, converting a terminal prohibition into a normal workflow.",
        [GOV_FX],
        _AUTH_PRE,
        {"agent_id": "MKT-05", "assigned_authority": "AUTH-3",
         "proposals": [
             {"skill": "skill.governance.raw_dataset_export", "payload": {"tenant_id": "11111111-1111-1111-1111-111111111111", "tables": ["customers"]}},
             {"skill": "skill.sales.check_price", "declared_authority": "AUTH-5", "payload": {"sku_id": "SKU-OK"}}],
         "approval_queue_before": 3},
        [("Submit the prohibited raw export proposal",
          "authorized=false with decisionCode DENY_PROHIBITED and a rationale naming the hard lock."),
         ("Submit a benign read whose payload self-declares required authority AUTH-5",
          "Same DENY_PROHIBITED verdict; the declared value is not treated as an approvable request."),
         ("Count approval-queue rows before and after both calls",
          "Queue count is unchanged (3), so neither action was routed to a human."),
         ("Read the security audit records for the run",
          "Two denied rows with a security violation marker and authority AUTH-5; no executed action row exists.")],
        ["denyCode is DENY_PROHIBITED and never REQUIRE_HUMAN_APPROVAL for an AUTH-5 class.",
         "Approval queue length delta is exactly 0 - a prohibited action is not a human decision waiting to happen.",
         "Both audit rows exist with execution_status denied and an alert/severity marker.",
         "No dataset export file or row set is produced."],
        ["Any code path that lets an operator approve an AUTH-5 action.",
         "Accumulating AUTH-3 privileges until the requirement is satisfied.",
         "Downgrading AUTH-5 to AUTH-4 so the action can be queued."],
        ["PEP decision JSON for both proposals with the security violation marker.",
         "Approval queue counts before and after (3 and 3).",
         "Audit rows plus the security alert emission record."],
        ["Delete the " + NS + " run rows and namespace keys; retain the alert record copy for evidence."],
        "Real PEP hard-lock branch and approval persistence under test; the dataset connector is a substituted boundary whose absence of output is asserted. No timing dependence.",
        refs=[SRS, IMPL08],
    ),
    case(
        "UNIT-AUTH-VERDICT-PRECEDENCE", "Verdict precedence: AUTH-5 deny and AUTH-4 route are evaluated before rank comparison",
        AUTH_SUITE, "unit", ["AUTH-4", "AUTH-5", "BR-008", "NFR-001"],
        ["entity:Agent", "stage:DECISION"], "blueprint", "P0", "critical",
        "A high-clearance agent (AUTH-3) outranks a denial so a prohibited or approval-gated action executes without human sign-off.",
        [GOV_FX],
        _AUTH_PRE + ["Rank table contains only the four autonomous levels AUTH-0..AUTH-3; AUTH-4 and AUTH-5 are absent by design."],
        {"agent": {"agent_id": "SAL-02", "assigned_authority": "AUTH-3"},
         "ordered_probes": [
             {"label": "AUTH-5 required by registry", "skill": "skill.governance.raw_dataset_export"},
             {"label": "AUTH-4 required by registry", "skill": "skill.sales.create_order"},
             {"label": "AUTH-3 required by registry", "skill": "skill.sales.send_message"},
             {"label": "AUTH-1 required but proposal declares AUTH-5", "skill": "skill.sales.recommend_product", "declared": "AUTH-5"}]},
        [("Evaluate probe 1 for the maximum-clearance autonomous agent",
          "Verdict is DENY_PROHIBITED even though the agent holds the highest autonomous rank."),
         ("Evaluate probe 2 for the same agent",
          "Verdict is REQUIRE_HUMAN_APPROVAL; the rank comparison is not reached and no execution occurs."),
         ("Evaluate probe 3 for the same agent",
          "Verdict is PERMIT because AUTH-3 is the top autonomous level and the skill requires AUTH-3."),
         ("Evaluate probe 4 where the proposal self-declares AUTH-5 for a low-risk skill",
          "Verdict is DENY_PROHIBITED; a self-declared prohibition is honoured as a deny, never silently dropped.")],
        ["Verdict order is deny, then approval-route, then numeric rank comparison for the four autonomous levels.",
         "The rank table has exactly four entries and contains neither AUTH-4 nor AUTH-5.",
         "Probe 3 is the only PERMIT; probes 1, 2 and 4 are DENY_PROHIBITED, REQUIRE_HUMAN_APPROVAL and DENY_PROHIBITED respectively.",
         "No probe with an AUTH-4 or AUTH-5 requirement produces an executed action."],
        ["Implementing AUTH-4/AUTH-5 as ranks 4 and 5 that a better-qualified agent can exceed.",
         "Falling through to PERMIT when the verdict branch is unknown.",
         "Recording an executed action for the approval-routed probe."],
        ["Four PEP decision JSON records in submission order.",
         "Exported rank table showing four entries.",
         "Audit rows for the four probes with authority and execution_status."],
        ["Delete the " + NS + " namespace records; no shared state to reset beyond it."],
        "Real PEP verdict ordering under test, driven through the public enforce() seam with the skill registry fixture. No external boundary is exercised, so no vendor substitute is needed.",
        refs=[IMPL08, SRS],
    ),
    case(
        "UNIT-AUTH-GRANT-REGISTRY", "Grant registry: only AUTH-0..AUTH-3 can be assigned to an agent",
        AUTH_SUITE, "unit", ["AUTH-4", "AUTH-5", "BR-008", "NFR-001"],
        ["entity:Agent"], "blueprint", "P1", "high",
        "An operator or migration script writes AUTH-4 or AUTH-5 into an agent record, permanently bypassing the approval gate or the hard lock.",
        [GOV_FX],
        _AUTH_PRE,
        {"grants": [
             {"agent_id": "SAL-02", "assigned_authority": "AUTH-0"},
             {"agent_id": "SAL-02", "assigned_authority": "AUTH-3"},
             {"agent_id": "SAL-02", "assigned_authority": "AUTH-4"},
             {"agent_id": "SAL-02", "assigned_authority": "AUTH-5"},
             {"agent_id": "SAL-02", "assigned_authority": "SUPERUSER"}]},
        [("Insert the two legal grants AUTH-0 and AUTH-3",
          "Both rows are accepted and the stored value round-trips unchanged."),
         ("Insert the AUTH-4 grant",
          "The write is rejected by the persistence constraint (checked at the database or repository boundary); the stored value for SAL-02 is unchanged."),
         ("Insert the AUTH-5 grant and the SUPERUSER grant",
          "Both writes are rejected; no row is persisted and the rejection names the constrained column."),
         ("Read back the agent record",
          "assigned_authority is still AUTH-3 from step 1 and no grant row above AUTH-3 exists.")],
        ["The persisted value set for assigned_authority is exactly {AUTH-0, AUTH-1, AUTH-2, AUTH-3}.",
         "AUTH-4 and AUTH-5 writes fail with a constraint error, not a silent coercion.",
         "Agent behaviour after the rejected writes still routes create_order to approval.",
         "No rejection is swallowed: each failure is observable to the caller."],
        ["Coercing an invalid grant to the nearest valid level so the write succeeds.",
         "Persisting AUTH-5 and relying on the PEP to catch it later.",
         "Allowing the rejection to be recorded as a successful grant."],
        ["Round-tripped agent records after each write attempt.",
         "Constraint violation messages for the three rejected grants.",
         "PEP verdict for create_order after the attempts, showing REQUIRE_HUMAN_APPROVAL."],
        ["Restore SAL-02 to the fixture value and remove " + NS + " grant rows."],
        "Real repository/constraint under test; no vendor substitute. Applies the same check whether the store is PostgreSQL or the in-process repository used offline.",
        refs=[IMPL08, SRS],
    ),
    case(
        "UNIT-AUTH-SELF-ASSERTED", "Server-side skill registry outranks a self-asserted authority in the payload",
        AUTH_SUITE, "unit", ["AUTH-4", "BR-008", "BR-009", "NFR-001"],
        ["entity:Agent", "entity:Skill"], "blueprint", "P0", "critical",
        "A model- or prompt-supplied authority claim downgrades an approval-gated skill so it executes autonomously.",
        [GOV_FX],
        _AUTH_PRE + ["Registry entry skill.sales.create_order requires AUTH-4; the proposal will claim AUTH-0."],
        {"agent_id": "SAL-02", "assigned_authority": "AUTH-3",
         "proposal": {"skill": "skill.sales.create_order", "required_authority": "AUTH-0",
                      "payload": {"customer_id": "cust-a", "sku_id": "SKU-OK", "qty": 1, "effect_key": "sha256:" + "a" * 64}}},
        [("Submit the proposal that declares a lower requirement than the registry holds",
          "The resolved requirement is AUTH-4 from the registry; verdict is REQUIRE_HUMAN_APPROVAL."),
         ("Repeat with a registry-missing skill whose declared requirement is AUTH-0",
          "The declared value is used, the autonomous rank comparison still applies, and the verdict is PERMIT only because the agent holds AUTH-3."),
         ("Repeat the first proposal with the registry entry removed",
          "Behaviour is documented and stable (declared value used), and no execution of a create_order occurs while the registry is unavailable.")],
        ["The resolved requirement always comes from the registry when present; the payload field is ignored.",
         "Verdict for the first probe is REQUIRE_HUMAN_APPROVAL and 0 order-creation calls reach the mock SoR.",
         "Removing the registry entry never results in an executed high-risk action."],
        ["Trusting proposal.required_authority for a skill the registry knows.",
         "Falling back to PERMIT when the registry lookup fails.",
         "Creating the order and asking for approval afterwards."],
        ["PEP decision JSON with the resolved requirement and its source (registry or proposal).",
         "Mock SoR order-creation call log showing zero calls.",
         "Audit row for the proposal with authority AUTH-4."],
        ["Delete " + NS + " order drafts and namespace keys."],
        "Real registry lookup and PEP under test. The registry is loaded from the fixture; removing an entry is a supported in-test mutation of the substituted registry boundary.",
        refs=[IMPL08, SRS],
    ),
    case(
        "UNIT-AUTH-DENY-AUDIT", "Denied action still produces an immutable audit row with denied status",
        AUTH_SUITE, "unit", ["AUTH-5", "NFR-002", "BR-008", "TC-E2E-006", "SRS-17"],
        ["entity:Agent", "entity:Evidence", "stage:EVIDENCE"], "baseline", "P0", "critical",
        "Denied actions leave no trace, so an attacker can probe authority boundaries and a later investigation cannot reconstruct what was attempted.",
        [GOV_FX, CUST_FX],
        _AUTH_PRE,
        {"agent_id": "MKT-05", "assigned_authority": "AUTH-3",
         "denied_proposal": {"skill": "skill.governance.raw_dataset_export", "payload": {"tables": ["customers", "orders"]}},
         "permitted_proposal": {"skill": "skill.sales.check_price", "payload": {"sku_id": "SKU-OK"}}},
        [("Submit the denied proposal and capture the run/correlation identifiers",
          "Response carries authorized=false, a decision code and a correlation id."),
         ("Submit the permitted read for the same agent",
          "Response carries authorized=true and the same correlation id family so the two rows can be linked."),
         ("Query the audit store for the run",
          "Exactly two rows exist: one denied and one success; the denied row has the full 18 domain fields populated as far as applicable, including trigger, skill, tool, authority AUTH-5 and timestamp."),
         ("Verify the denied row exposes no PII",
          "customer_or_entity_id is a pseudonym and no plaintext phone, name or address appears anywhere in the row.")],
        ["A denied action always yields an audit row with execution_status denied - never zero rows.",
         "The denied row records the attempted skill and tool, so the probe is reconstructable.",
         "Neither row contains plaintext PII: customer_or_entity_id is pseudonymized.",
         "Chain linkage holds: the denied row prev_hash equals the preceding row chain_hash for the tenant."],
        ["Skipping audit for denied requests to save write volume.",
         "Writing a success status for a denied request.",
         "Storing plaintext customer identifiers in the audit row."],
        ["Exported audit rows (18 fields) for the run namespace, redacted.",
         "PEP response bodies for both proposals.",
         "Chain verification output for the two rows."],
        ["Delete the " + NS + " run rows after exporting evidence; never delete pre-existing sandbox audit rows."],
        "Real audit writer plus hash-chain verifier under test. Verification recomputes SHA-256 over canonical JSON rather than trusting a stored flag.",
        refs=[IMPL08, SRS],
    ),
    case(
        "UNIT-AUTH-UNKNOWN-SKILL", "Unregistered skill: declared authority is used but the rank check still applies",
        AUTH_SUITE, "unit", ["BR-008", "NFR-001", "AUTH-3"],
        ["entity:Skill", "entity:Agent"], "blueprint", "P1", "high",
        "A newly deployed skill missing from the registry becomes an unrestricted execution path because the lookup returns nothing.",
        [GOV_FX],
        _AUTH_PRE + ["skill.sales.experimental_bundle is absent from the registry by construction."],
        {"agent_id": "SAL-01", "assigned_authority": "AUTH-1",
         "proposals": [
             {"skill": "skill.sales.experimental_bundle", "required_authority": "AUTH-1", "payload": {"customer_id": "cust-a"}},
             {"skill": "skill.sales.experimental_bundle", "required_authority": "AUTH-3", "payload": {"customer_id": "cust-a"}},
             {"skill": "skill.sales.experimental_bundle", "required_authority": "AUTH-4", "payload": {"customer_id": "cust-a"}}]},
        [("Submit the unregistered skill declaring AUTH-1 for an AUTH-1 agent",
          "Verdict is PERMIT and the call is recorded as registry-miss with declared authority used."),
         ("Submit the same unregistered skill declaring AUTH-3",
          "Verdict is DENY (authority boundary exceeded) because the agent holds AUTH-1."),
         ("Submit the same unregistered skill declaring AUTH-4",
          "Verdict is REQUIRE_HUMAN_APPROVAL; still no execution."),
         ("Inspect the audit rows",
          "Each row records that the authority source was the proposal, flagging the registry gap.")],
        ["The rank comparison applies to unregistered skills; only the source of the requirement changes.",
         "No unregistered skill executes above the agent assigned authority.",
         "Audit rows make the registry miss explicit so the gap is actionable.",
         "Exactly one of the three probes is permitted."],
        ["Fail-open to PERMIT for unknown skills.",
         "Silently treating an unknown skill as AUTH-0.",
         "Hiding the registry miss so it never reaches engineering."],
        ["PEP decision JSON for the three probes including the requirement source field.",
         "Audit rows for the run.",
         "Registry content dump proving the skill is absent."],
        ["Delete " + NS + " namespace rows."],
        "Real PEP with the fixture registry; the registry is an in-test substitute exposing add/remove so the miss is reproducible.",
        refs=[IMPL08, SRS],
    ),
    case(
        "UNIT-AUTH-5-CROSS-TENANT", "Cross-customer context access classified AUTH-5 is denied with a security alert",
        AUTH_SUITE, "unit", ["AUTH-5", "NFR-001", "NFR-006", "TC-E2E-006"],
        ["entity:Agent", "entity:Customer"], "baseline", "P0", "critical",
        "An agent reads another customer's or another tenant's data because the requested identifier differs from the session-bound verified identity.",
        [GOV_FX, CUST_FX],
        _AUTH_PRE + ["Session is server-verified as cust-a (tenant T1); cust-b belongs to the same tenant and cust-t2 to T2."],
        {"agent_id": "CS-01", "assigned_authority": "AUTH-3",
         "probes": [
             {"label": "session customer", "customer_id": "cust-a"},
             {"label": "same-tenant foreign customer", "customer_id": "cust-b"},
             {"label": "cross-tenant customer", "customer_id": "cust-t2", "tenant": "T2"}]},
        [("Request the session-bound customer profile",
          "Verdict is PERMIT and the returned profile belongs to cust-a."),
         ("Request cust-b profile inside the cust-a session",
          "Verdict is DENY_PROHIBITED; no cust-b field is returned in any response body."),
         ("Request cust-t2 profile",
          "Verdict is DENY_PROHIBITED and the tenant identifier mismatch is recorded."),
         ("Inspect the alerting path",
          "Each denial emits a security alert record and an audit row with the attempted target pseudonymized.")],
        ["Exactly one PERMIT; the two foreign reads are DENY_PROHIBITED.",
         "Zero occurrences of cust-b or cust-t2 attributes in every response body (asserted by scanning the serialized bodies).",
         "Two security alert records exist for the run, one per denied probe.",
         "No customer row is cached under the wrong session namespace."],
        ["Returning a generic error to the UI while internally loading the foreign profile.",
         "Trusting a customer_id supplied by the caller as the session identity.",
         "Recording the cross-tenant attempt only as a 404 without an audit or alert row."],
        ["PEP decision JSON for the three probes plus the serialized response bodies (redacted).",
         "Security alert records.",
         "Audit rows with pseudonymized targets."],
        ["Delete the " + NS + " session namespace and any cached profile rows."],
        "Real identity binding, PEP and audit under test; the customer store is the fixture-backed substitute. Assertion scans real serialized payloads rather than a mocked return value.",
        refs=[IMPL08, SRS],
    ),
    case(
        "UNIT-AUTH-FREQ-CAP", "AUTH-3 contact-frequency boundary returns LIMIT_EXCEEDED instead of silently dropping",
        AUTH_SUITE, "unit", ["AUTH-3", "BR-008", "NFR-008", "ASM-003"],
        ["entity:Action", "stage:ACTION"], "blueprint", "P1", "high",
        "A reminder storm contacts the same customer three or more times because the cap is applied as a soft drop rather than a typed refusal, or the cap silently blocks legitimate transactional messages.",
        [GOV_FX, CONSENT_FX],
        _AUTH_PRE + ["Synthetic cap maxAutonomousReminderCount=2 for T1 (design parameter, not an approved limit)."],
        {"agent_id": "SAL-02", "assigned_authority": "AUTH-3",
         "sequence": [
             {"purpose": "transactional", "template": "order_shipped", "customer_id": "cust-a"},
             {"purpose": "transactional", "template": "order_shipped", "customer_id": "cust-a"},
             {"purpose": "transactional", "template": "order_shipped", "customer_id": "cust-a"},
             {"purpose": "marketing", "template": "win_back", "customer_id": "cust-b"}]},
        [("Send two permitted transactional messages to cust-a",
          "Both return PERMIT and the adapter counter reaches 2."),
         ("Send a third transactional message to the same customer in the same window",
          "Verdict is LIMIT_EXCEEDED with a retry-after or window hint; the adapter counter stays at 2."),
         ("Send a marketing message to cust-b (opt-out in the consents fixture)",
          "Verdict is suppressed for consent, which is a different decision code from LIMIT_EXCEEDED so operators can tell the causes apart."),
         ("Read the audit rows",
          "Four rows: two success, one limit-exceeded, one consent-suppressed, each with a distinct decision code.")],
        ["The cap is enforced at exactly 2 within the window and the boundary is inclusive of the second message.",
         "LIMIT_EXCEEDED and consent suppression are distinguishable decision codes, not one generic error.",
         "Adapter counter is 2, never 3, proving the third message was not delivered.",
         "No message is silently dropped without an audit row and a typed verdict."],
        ["Counting a limit-blocked message as delivered.",
         "Applying the marketing consent check to transactional messages and breaking order notifications.",
         "Resetting the counter so a retry storm bypasses the cap."],
        ["PEP decision JSON for the four attempts.",
         "Adapter counter and the four audit rows.",
         "Consent evaluation result for cust-b."],
        ["Reset the " + NS + " reminder counters and delete the run namespace; no message was actually delivered."],
        "Real PEP limit check with the tenant policy source; the channel adapter is the substituted boundary and exposes the counter. Window arithmetic uses the frozen clock, not sleeps.",
        prereq=["Contact-frequency cap is a tenant policy parameter without an owner-approved value; the case is valid only against the labelled synthetic cap."],
        refs=[IMPL08, SRS],
    ),
    case(
        "UNIT-AUTH-VERDICT-MAP", "Verdict-to-audit mapping: each enforcement outcome lands on the right execution status",
        AUTH_SUITE, "unit", ["AUTH-0", "AUTH-4", "AUTH-5", "NFR-002", "SRS-17"],
        ["entity:Decision", "entity:Action", "stage:EVIDENCE"], "blueprint", "P1", "high",
        "Operators and auditors cannot tell whether an action was executed, refused or is waiting, so dashboards and post-incident reviews draw the wrong conclusion.",
        [GOV_FX],
        _AUTH_PRE,
        {"agent_id": "CS-01", "assigned_authority": "AUTH-3",
         "expected_mapping": {
             "PERMIT": "success", "DENY_PROHIBITED": "denied",
             "REQUIRE_HUMAN_APPROVAL": "denied", "LIMIT_EXCEEDED": "denied",
             "FAIL_CLOSED": "failed", "UNKNOWN_OUTCOME": "pending"},
         "probes": [
             {"skill": "skill.sales.check_price", "payload": {"sku_id": "SKU-OK"}},
             {"skill": "skill.governance.raw_dataset_export", "payload": {}},
             {"skill": "skill.care.initiate_return", "payload": {"order_id": "ORD-A-1"}},
             {"skill": "skill.sales.send_message", "payload": {"reminder_count": 9}}]},
        [("Submit the four probes and collect the four verdicts",
          "Verdicts are PERMIT, DENY_PROHIBITED, REQUIRE_HUMAN_APPROVAL and LIMIT_EXCEEDED respectively."),
         ("Read the four audit rows",
          "execution_status values are success, denied, denied, denied; APPROVAL-PENDING is represented as denied plus an approval reference, never as success."),
         ("Force a connector failure and an unknown-outcome timeout in two extra probes",
          "Failure maps to failed and unknown outcome maps to pending or a dedicated reconciliation state, never to success.")],
        ["Every verdict maps to exactly one execution_status and the mapping is total over the six outcomes.",
         "No probe produces success when it was not permitted and externally executed.",
         "REQUIRE_HUMAN_APPROVAL rows carry an approval ticket reference so the pause is traceable.",
         "The six mapping entries are enforceable as data, not hardcoded in the assertion (changing the fixture changes the expectation)."],
        ["Mapping an unknown outcome to success because the request returned 200.",
         "Collapsing denial and approval-pending into one status.",
         "Writing a success row for a probe that never reached a connector."],
        ["Verdict JSON and audit row pairs for all six probes.",
         "Connector call log showing which probes actually dispatched."],
        ["Delete " + NS + " run rows after exporting the mapping table."],
        "Real PEP verdict emission, audit mapping and reconciliation state machine under test; connector behaviour is substituted with an injectable failure/timeout stub. Deterministic clock drives the timeout.",
        refs=[IMPL08, SRS],
    ),
)
