"""Ordered governance testcase section: command_center."""
from __future__ import annotations


# ===========================================================================
# integration/command-center.md — SCR-001..SCR-005 (SRS 18, implement/07)
# ===========================================================================
_CC_PRE = [
    "Namespace " + NS + "scr-<case_id>-<worker_id>; the operator UI runs against the offline gateway and mock SSE/telemetry streams.",
    "Operator session bound to tenant T1 and an explicit operator_id from fixtures/offline/governance.json; frozen clock " + CLOCK + ".",
]
_CC_AUTO = ("Command Center React components and the gateway routes run as real code under test; ERP, channel and telemetry "
            "providers are replaced by the offline mock sinks whose call logs are the oracle. UI assertions use accessible "
            "roles and names rather than CSS classes, and stream waits are condition-based.")

_add(
    case(
        "INT-SCR-001", "SCR-001 Executive Dashboard: all ten baseline indicators with honest no-data semantics",
        CC_SUITE, "integration", ["SCR-001", "SRS-17", "NFR-002", "OBJ-001"],
        ["stage:OUTCOME"], "baseline", "P0", "critical",
        "An executive reads a dashboard that silently zero-fills a metric whose source is missing, concluding revenue collapsed or that a channel performs when it is simply unmeasured.",
        [GOV_FX, ORDERS_FX],
        _CC_PRE + ["Telemetry sink seeded with T1 revenue and AI-action aggregates; the CAC source is deliberately absent."],
        {"request": {"method": "GET", "path": "/api/v1/telemetry/executive", "tenant": "T1"},
         "seeded": {"revenue_twd": 250000, "leads": 120, "conversion_rate": 0.083, "active_campaigns": 4,
                    "ai_generated_revenue_twd": 62000, "cs_status": "NORMAL", "retention": 0.71,
                    "ai_actions": 1840, "approval_pending": 3, "abnormal_events": 1},
         "missing_source": "CAC"},
        [("Fetch the executive payload as an authenticated T1 operator",
          "Payload contains exactly the ten baseline indicators, each with its own value and a source/freshness marker."),
         ("Compare the returned values with the seeded aggregates",
          "The nine sourced indicators match the seeded values exactly (revenue 250000, leads 120, ai_actions 1840, approval_pending 3)."),
         ("Inspect the CAC indicator whose source feed was not seeded",
          "CAC is reported as NO_DATA with the missing source named; it is not 0 and not a computed guess."),
         ("Render the dashboard and re-read the indicators from the DOM",
          "Ten indicator labels are visible with an explicit no-data affordance on CAC.")],
        ["Exactly ten baseline indicators are present: Revenue, Leads, Conversion, Active Campaigns, AI Generated Revenue, CS status, Retention, AI Actions, Approval Pending, Abnormal Events.",
         "A metric with no source returns NO_DATA, never 0 and never a stale value without a timestamp.",
         "Each indicator carries a source and an observed-at timestamp so staleness is detectable by the reader.",
         "Seeded values round-trip exactly; no display rounding changes the stored aggregate."],
        ["Zero-filling an unavailable metric.",
         "Omitting the absent metric entirely so the dashboard looks complete.",
         "Blaming the missing metric on the upstream provider without surfacing the state."],
        ["Raw executive payload JSON with the NO_DATA marker.",
         "Dashboard screenshot plus the accessibility tree snapshot listing the ten labels.",
         "Telemetry sink log showing which sources were queried."],
        ["Clear the " + NS + " telemetry namespace keys; the mock sink data is restored to its fixture state."],
        _CC_AUTO,
        refs=[IMPL07, SRS],
    ),
    case(
        "INT-SCR-001-EMPTY", "SCR-001 empty state: a brand-new tenant shows explicit no-data, never zeros",
        CC_SUITE, "integration", ["SCR-001", "SRS-17"],
        ["stage:OUTCOME"], "extension", "P0", "high",
        "A newly onboarded tenant sees a wall of zeros and concludes the platform recorded a catastrophic drop instead of simply having no data yet.",
        [GOV_FX, TENANTS_FX],
        _CC_PRE + ["Tenant T2 has no events, orders or campaigns in the telemetry namespace."],
        {"request": {"method": "GET", "path": "/api/v1/telemetry/executive", "tenant": "T2"},
         "seed_state": "EMPTY_TENANT"},
        [("Fetch the executive payload for the empty tenant",
          "All ten indicators return NO_DATA with the reason no_events_in_window."),
         ("Render the dashboard",
          "Each indicator shows an empty-state affordance (dash plus explanatory label), and no indicator renders a numeric zero."),
         ("Ingest one purchase event for cust-t2 and refresh",
          "Revenue and AI Actions switch to real values while the remaining indicators stay NO_DATA.")],
        ["Zero indicators render numeric 0 while the tenant has no data.",
         "At least one explanatory label is present and its accessible name mentions that no data exists for the window.",
         "After ingesting a single event, only the indicators with a source change value; others remain NO_DATA rather than flipping to 0.",
         "The payload distinguishes an empty window from a missing source (different reason codes)."],
        ["Rendering 0 for an empty window so the chart draws a flat line.",
         "Showing sample or demonstration numbers on an empty tenant.",
         "Treating an empty tenant fetch as an error page."],
        ["Executive payload for the empty tenant with reason codes.",
         "Empty-state screenshot and accessibility tree snapshot.",
         "Post-ingest payload showing partial data."],
        ["Remove the " + NS + " event and telemetry keys for T2."],
        _CC_AUTO,
        refs=[IMPL07, SRS],
    ),
    case(
        "INT-SCR-001-ERROR", "SCR-001 error state: a failing metrics source surfaces an error, not stale numbers",
        CC_SUITE, "integration", ["SCR-001", "SRS-17", "NFR-004"],
        ["stage:OUTCOME"], "extension", "P0", "high",
        "A broken metrics feed leaves yesterday's numbers on screen with no warning, so leadership makes a decision on data they believe is live.",
        [GOV_FX],
        _CC_PRE + ["Synthetic values for the previous successful fetch are cached with an observed_at timestamp."],
        {"request": {"method": "GET", "path": "/api/v1/telemetry/executive", "tenant": "T1"},
         "failure_script": [{"call": 1, "result": "200_OK"},
                            {"call": 2, "result": "503_METRICS_UNAVAILABLE"},
                            {"call": 3, "result": "200_OK"}]},
        [("Perform the first fetch successfully and record the observed_at",
          "Payload carries fresh values and a timestamp."),
         ("Force the second fetch to fail with 503",
          "The dashboard enters an error/stale state: the last-known timestamp is shown and the values are marked stale, with the upstream error code available."),
         ("Release the fault and fetch again",
          "Fresh values replace the stale ones and the error state clears without a page reload.")],
        ["On failure the response never presents cached numbers as current: a staleness marker or error state is mandatory.",
         "The upstream error code 503 is preserved in the surface, not replaced by a generic message.",
         "Recovery clears the error state automatically and the new values are the seeded ones.",
         "No fabricated or interpolated value fills the gap."],
        ["Showing cached numbers with no staleness indicator.",
         "Recording the failed fetch as a successful dashboard load.",
         "Replacing an error with an empty chart that looks like zero activity."],
        ["Three fetch payloads with timestamps and error codes.",
         "Dashboard screenshots for the success, error and recovered states.",
         "Gateway log showing the upstream 503 was propagated."],
        ["Restore the mock metrics provider script and clear " + NS + " cache keys."],
        _CC_AUTO,
        refs=[IMPL07, SRS],
    ),
    case(
        "INT-SCR-001-ABNORMAL", "SCR-001 abnormal events: a spike raises a traceable alert, not a silent number",
        CC_SUITE, "integration", ["SCR-001", "SRS-17", "NFR-002"],
        ["stage:EVIDENCE"], "extension", "P1", "high",
        "An anomaly such as a policy-violation spike or a connector outage is displayed as a bare counter with no link to the runs behind it, so nobody can act.",
        [GOV_FX],
        _CC_PRE + ["Three abnormal events are seeded for T1: two denied authority attempts and one connector outage."],
        {"request": {"method": "GET", "path": "/api/v1/telemetry/executive", "tenant": "T1"},
         "seeded_abnormal": [
             {"severity": "HIGH", "kind": "AUTHORITY_DENY", "run_id": "run-gov-101"},
             {"severity": "HIGH", "kind": "AUTHORITY_DENY", "run_id": "run-gov-102"},
             {"severity": "MEDIUM", "kind": "CONNECTOR_OUTAGE", "run_id": "run-gov-103"}]},
        [("Fetch the dashboard payload",
          "abnormal_events reports 3 with severity breakdown HIGH 2 and MEDIUM 1."),
         ("Follow the drill-down for one HIGH event",
          "The underlying run is opened and its audit row shows the denied authority verdict with the attempted skill."),
         ("Resolve the connector outage and refresh after the alert is acknowledged",
          "The acknowledged event leaves the abnormal list while the two HIGH denials remain, and the count changes to 2.")],
        ["The abnormal counter equals the seeded count and is decomposable by severity and kind.",
         "Each event links to a concrete run identifier that resolves to a real audit row.",
         "Acknowledgement changes the visible abnormal count without deleting the underlying audit records.",
         "High-severity denials are never auto-suppressed by a bulk acknowledge."],
        ["Counting anomalies without any route to the evidence.",
         "Deleting audit rows to clear the alert badge.",
         "Acknowledging all severities with one control."],
        ["Dashboard payload with the event list.",
         "Drill-down audit row for one HIGH event.",
         "Before/after counts with the acknowledgement record."],
        ["Remove the " + NS + " telemetry and acknowledgement rows; audit records for the seeded runs are retained."],
        _CC_AUTO,
        refs=[IMPL07, SRS],
    ),
    case(
        "INT-SCR-002", "SCR-002 Agent Operations: live status, current task, history, errors, tool calls, cost and KPI",
        CC_SUITE, "integration", ["SCR-002", "SRS-17", "NFR-009", "NFR-010"],
        ["stage:ACTION", "stage:EVIDENCE"], "baseline", "P0", "critical",
        "Operations cannot see which agents are stuck, what they are doing or what they cost, so a runaway loop or a silent degradation runs unnoticed.",
        [GOV_FX, TENANTS_FX],
        _CC_PRE + ["One completed run and one degraded agent are seeded for T1 with latency and cost telemetry."],
        {"request": {"method": "GET", "path": "/api/v1/agents/operations", "tenant": "T1"},
         "seeded": {"agents": [{"agent_id": "SAL-02", "state": "HEALTHY", "current_task": "recommend_product",
                                "p95_latency_ms": 900, "error_rate": 0.004},
                               {"agent_id": "MKT-05", "state": "DEGRADED", "current_task": None,
                                "p95_latency_ms": 3100, "error_rate": 0.02}],
                    "run_history_size": 1, "tool_calls": 6, "cost_twd": 0.08}},
        [("Fetch the operations payload",
          "Both agents appear with state, current task, p95 latency, error rate, tool-call count and cost."),
         ("Inspect the degraded agent classification",
          "MKT-05 is DEGRADED because p95 3100 ms exceeds 2500 ms; the contributing measurement is shown, not just the label."),
         ("Open the run history entry and its tool-call detail",
          "The run shows its six tool calls, the error-free status, latency and cost recorded from the run row."),
         ("Verify tenant scoping of the listing",
          "Only T1 agents and runs appear; no T2 row is present in the payload.")],
        ["Agent state is derived from the documented thresholds and the derivation is visible to the operator.",
         "Run history, tool-call count, cost and latency come from the run record rather than being recomputed differently on screen.",
         "Zero rows belonging to another tenant appear in the payload.",
         "Cost and latency are displayed with units and are attributable to the specific run."],
        ["Hardcoding a healthy status while the agent is degraded.",
         "Reporting an aggregate cost that cannot be attributed to a run.",
         "Leaking another tenant's run history into the listing."],
        ["Operations payload JSON.",
         "Run detail record with tool calls, latency and cost.",
         "Screenshot of the operations console including the degraded badge."],
        ["Clear the " + NS + " telemetry keys; seeded agents are restored to the fixture state."],
        _CC_AUTO,
        refs=[IMPL07, SRS],
    ),
    case(
        "INT-SCR-002-OFFLINE-RECONNECT", "SCR-002 stream resilience: reconnect resumes without gaps or duplicate rows",
        CC_SUITE, "integration", ["SCR-002", "SRS-17", "NFR-004"],
        ["stage:ACTION"], "extension", "P1", "high",
        "A dropped telemetry stream leaves the console silently frozen, or reconnect replays the whole buffer so run rows duplicate and counters inflate.",
        [GOV_FX],
        _CC_PRE + ["SSE stream subscribed at /api/v1/telemetry/stream with a resumable cursor; the window is frozen so ordering is deterministic."],
        {"subscription": {"channel": "run_updates", "tenant": "T1", "cursor": "cur-1000"},
         "script": [{"phase": "connect", "events": ["run-gov-201", "run-gov-202"]},
                    {"phase": "drop", "drop_after": "run-gov-202"},
                    {"phase": "server_side_events_while_down", "events": ["run-gov-203", "run-gov-204"]},
                    {"phase": "reconnect", "resume_from": "run-gov-202"},
                    {"phase": "duplicate_delivery", "replay": ["run-gov-202"]}]},
        [("Subscribe and receive the first two run updates",
          "Both rows appear, ordered by event time, and the client stores the latest cursor."),
         ("Drop the connection and let two more events occur server-side",
          "The console shows a disconnected/stale indicator rather than pretending to be live."),
         ("Reconnect using the stored cursor",
          "The two missed events (203, 204) are delivered and the console catches up; the connection indicator returns to live."),
         ("Deliver one already-seen event again (replay of run-gov-202)",
          "The duplicate is ignored by identity; the visible row count stays at four.")],
        ["After reconnect the console contains exactly the four distinct runs once each: 201, 202, 203, 204.",
         "The disconnected state was visible while the stream was down, so the operator never mistook stale data for live data.",
         "Duplicate delivery does not create a second visible row and does not increment any counter.",
         "Resumption uses the stored cursor rather than replaying from the beginning of the stream."],
        ["Showing live data while disconnected.",
         "Appending replayed events a second time.",
         "Resetting the cursor on reconnect so either gaps or duplicates appear."],
        ["Event delivery log including the gap and the replay.",
         "Cursor values before drop and after resume.",
         "Visible row identity list proving four unique rows."],
        ["Close the stream subscription and clear the " + NS + " cursor and buffer keys."],
        _CC_AUTO + " The drop and replay are scripted deterministically at the mock stream boundary; the client state machine is real code.",
        refs=[IMPL07, SRS],
    ),
    case(
        "INT-SCR-002-RUN-ERROR", "SCR-002 run inspection: error code and sanitized stack without PII leakage",
        CC_SUITE, "integration", ["SCR-002", "SRS-17", "NFR-002", "NFR-006"],
        ["stage:EVIDENCE"], "extension", "P1", "high",
        "The run drawer exposes raw context containing customer identifiers, or hides the error so a failing connector looks idle.",
        [GOV_FX, CUST_FX],
        _CC_PRE + ["One failed run is seeded with an upstream 504 and a sanitized context snapshot."],
        {"run": {"run_id": "run-gov-301", "agent_id": "CS-01", "status": "failed",
                 "error": {"code": "UPSTREAM_504", "message": "ERP lookup timed out", "stack": "WmsAdapter.fetchStockStatus(line 142)"},
                 "context_snapshot": {"customer_ref": "psn:9f2a...", "sku": "SKU-OK", "warehouse": "TW-01"}}},
        [("Open the failed run in the inspection drawer",
          "The displayed error code is UPSTREAM_504 with the sanitized stack line; the run status is failed, not idle."),
         ("Inspect the context snapshot field",
          "The customer reference is pseudonymized; no plaintext phone, name, address or session token appears."),
         ("Trigger the retry control from the drawer",
          "A retry is dispatched with the original effect_key and the drawer shows the new attempt linked to the same run group.")],
        ["The failed run is visibly failed with its upstream code, never presented as pending or idle.",
         "Zero plaintext PII tokens appear in the rendered drawer payload (asserted by scanning the serialized payload for the fixture phone digits).",
         "The retry reuses the original effect_key rather than minting a new one.",
         "The new attempt is linked to the original run so the history stays one chain."],
        ["Swallowing the error and showing a blank run.",
         "Rendering the raw context snapshot with plaintext identifiers.",
         "Retrying with a fresh key and creating a second external effect."],
        ["Drawer payload with the error object.",
         "Rendered text scan result for PII tokens.",
         "Retry request record showing the reused effect_key."],
        ["Delete the " + NS + " run and retry rows after exporting evidence."],
        _CC_AUTO,
        refs=[IMPL07, SRS],
    ),
    case(
        "INT-SCR-003-APPROVE", "SCR-003 APPROVE: signed ticket releases the prepared payload exactly once",
        CC_SUITE, "integration", ["SCR-003", "AUTH-4", "BR-007", "NFR-007", "TC-E2E-002"],
        ["entity:Approval", "stage:APPROVAL", "stage:EXECUTION"], "baseline", "P0", "critical",
        "Approval releases an unsigned or stale payload, or releases it twice, producing an unauthorized broadcast or a double execution.",
        [GOV_FX],
        _CC_PRE + ["APV-CAMP-15 is AWAITING_HUMAN for MKT-05 with payload_hash recorded; the mock EMAIL adapter counts sends."],
        {"request": {"method": "POST", "path": "/api/v1/approvals/APV-CAMP-15/decision",
                     "body": {"decision": "APPROVE", "operator_id": "OP-APPROVER-T1",
                              "reason": "Budget and margin checked against the attached evidence."}}},
        [("Submit the APPROVE decision as an authorized T1 approver",
          "HTTP 200 with status APPROVED, a decided_at timestamp and a correlation id; the task leaves awaiting_human and is queued for execution."),
         ("Wait for the execution attempt and read the adapter log",
          "Exactly one send occurs, carrying the same payload (campaign CMP-FLASH-15, discount 15 percent, audience 12000)."),
         ("Read the approval and audit records",
          "The approval record carries approver_id OP-APPROVER-T1, action APPROVE and signed_at; the audit row references the approver and the effect_key."),
         ("Submit the same APPROVE decision a second time",
          "The repeat is rejected as already decided and no second send occurs.")],
        ["Exactly one external send results from the approval, with the effect_key recorded once.",
         "The released payload is byte-identical to the reviewed payload; its payload_hash still matches the reviewed hash.",
         "The signature fields approver_id, action and signed_at are all populated - an unsigned release is impossible.",
         "A second identical decision does not execute again."],
        ["Releasing the task without a signed approval record.",
         "Sending a payload modified after review while claiming it was approved.",
         "Executing on both the first and the repeated decision."],
        ["ApprovalDecisionResponse body and the approval record with signature fields.",
         "EMAIL adapter send log with payload copy and effect_key.",
         "Audit row referencing the approver."],
        ["Cancel any residual task, delete " + NS + " approval and execution rows; the mock send is recorded as simulated, not recalled."],
        _CC_AUTO,
        refs=[IMPL07, API06],
    ),
    case(
        "INT-SCR-003-REJECT", "SCR-003 REJECT: standardized reason code terminates the task with no side effect",
        CC_SUITE, "integration", ["SCR-003", "AUTH-4", "NFR-007"],
        ["entity:Approval", "stage:APPROVAL"], "baseline", "P0", "critical",
        "A rejected campaign still executes because rejection only changed a UI label, or the rejection reason is free text that cannot be aggregated for brand and margin analysis.",
        [GOV_FX],
        _CC_PRE + ["APV-CAMP-15 is AWAITING_HUMAN with a mock EMAIL adapter counting sends."],
        {"requests": [
             {"label": "missing code", "body": {"decision": "REJECT", "operator_id": "OP-APPROVER-T1", "reason": "not now"}},
             {"label": "valid code", "body": {"decision": "REJECT", "operator_id": "OP-APPROVER-T1",
                                              "reason_code": "BUDGET_EXCEEDED", "reason": "Estimated budget above the approved monthly envelope."}}]},
        [("Submit REJECT without a standardized reason code",
          "HTTP 400 with a validation error naming reason_code; the approval state is unchanged (still AWAITING_HUMAN)."),
         ("Submit REJECT with reason_code BUDGET_EXCEEDED",
          "HTTP 200 with status REJECTED and decided_at; the task is terminated."),
         ("Wait beyond the decision and read the adapter log and audit rows",
          "Zero sends occurred; the audit row records the rejection with the standardized code and the operator identity.")],
        ["A REJECT without a standardized code never mutates state.",
         "After a valid rejection the adapter call count is 0 and the task is terminal.",
         "The audit row carries reason_code BUDGET_EXCEEDED so rejections are aggregable.",
         "The rejected payload is retained for review rather than deleted."],
        ["Treating a missing reason code as an empty string and rejecting anyway.",
         "Executing the task after rejection.",
         "Losing the rejection code on the audit row."],
        ["400 validation body and the unchanged approval state.",
         "Audit row with the rejection code and operator id.",
         "Adapter counter log showing zero sends."],
        ["Delete " + NS + " approval rows; the rejected payload copy is retained in the evidence export."],
        _CC_AUTO,
        refs=[IMPL07, API06],
    ),
    case(
        "INT-SCR-003-MODIFY", "SCR-003 MODIFY: the edited payload is re-validated before release",
        CC_SUITE, "integration", ["SCR-003", "AUTH-4", "BR-002", "ASM-003", "NFR-008"],
        ["entity:Approval", "stage:APPROVAL", "stage:EXECUTION"], "baseline", "P0", "critical",
        "A modified payload goes straight to execution, so an operator edit that breaches the floor price or exceeds the audience cap is never caught by the rules engine.",
        [GOV_FX, CATALOG_FX],
        _CC_PRE + ["APV-CAMP-15 pending with the original 15 percent discount and 12000 audience; synthetic floor inputs loaded for the arithmetic only."],
        {"requests": [
             {"label": "safe modification", "body": {"decision": "MODIFY", "operator_id": "OP-APPROVER-T1",
                                                     "reason": "Reduce discount and audience.",
                                                     "modified_payload": {"campaign_id": "CMP-FLASH-15", "discount_rate": 0.10, "audience_size": 4000}}},
             {"label": "floor breach", "body": {"decision": "MODIFY", "operator_id": "OP-APPROVER-T1",
                                                "reason": "Aggressive push.",
                                                "modified_payload": {"campaign_id": "CMP-FLASH-15", "discount_rate": 0.45, "audience_size": 4000}}}]},
        [("Submit the safe modification",
          "HTTP 200 with status MODIFIED; the payload is re-validated successfully and released for execution with the reduced values."),
         ("Observe the released action",
          "The adapter receives one send with discount 0.10 and audience 4000 - the modified payload, not the original."),
         ("Submit the floor-breaching modification on a fresh pending item",
          "The re-validation fails with a floor or policy violation; the item is not released and its state records the failed re-validation.")],
        ["A MODIFY always re-runs the deterministic rules before release; approval cannot substitute for policy.",
         "The released payload equals the re-validated modified payload (discount 0.10, audience 4000) and the original 0.15 was not used.",
         "The breaching modification produces zero adapter calls.",
         "The original and modified payloads are both retained so the change is auditable."],
        ["Releasing the modified payload without re-validation.",
         "Silently reverting to the original payload when validation fails.",
         "Applying the modification to the wrong approval item."],
        ["ApprovalDecisionResponse and the released payload copy.",
         "Re-validation record for both modifications with the failure code.",
         "Adapter send log with the modified values."],
        ["Cancel residual tasks and delete " + NS + " rows; simulated sends are reported as such."],
        _CC_AUTO,
        prereq=["The floor arithmetic uses labelled synthetic policy inputs; a real owner-approved floor (ASM-003) does not yet exist."],
        refs=[IMPL07, API06],
    ),
    case(
        "INT-SCR-003-PAUSE", "SCR-003 PAUSE: workflow freezes durably and can be resumed, with zero side effects",
        CC_SUITE, "integration", ["SCR-003", "AUTH-4", "NFR-007"],
        ["entity:Approval", "stage:APPROVAL"], "baseline", "P0", "critical",
        "Pause is implemented as a cancellation or as an in-memory flag, so work is either destroyed or silently resumes and executes behind the operator's back.",
        [GOV_FX],
        _CC_PRE + ["APV-CAMP-15 pending; the workflow has a step timer observed through the run state."],
        {"pause": {"decision": "PAUSE", "operator_id": "OP-APPROVER-T1", "reason": "Inventory count in progress at the warehouse."},
         "resume": {"decision": "APPROVE", "operator_id": "OP-APPROVER-T1", "reason": "Inventory confirmed."}},
        [("Submit PAUSE",
          "HTTP 200 with status PAUSED; the task holds a durable paused state and its timer is frozen."),
         ("Advance the frozen clock beyond the original step deadline and inspect the task",
          "The task is still PAUSED (not expired, not executed) and the timer did not advance while paused."),
         ("Submit APPROVE on the paused item",
          "The item resumes and then executes once, proving pause-freeze is resumable rather than terminal.")],
        ["PAUSE never terminates the run and never releases the prepared payload.",
         "While paused, zero adapter calls occur even after the original deadline passes.",
         "The pause is durable across a worker restart (state read from persistence, not process memory).",
         "Resuming from PAUSE produces exactly one execution."],
        ["Implementing pause as cancellation so the work is lost.",
         "Letting the step timer keep running so the pause silently expires.",
         "Executing once on pause and once again on resume."],
        ["Task state snapshots before pause, during pause past the deadline, and after resume.",
         "Adapter counter log showing zero calls during the pause and one after resume."],
        ["Delete " + NS + " approval and execution rows after exporting the state snapshots."],
        _CC_AUTO + " The deadline advance uses the injected clock, not a wall-clock sleep.",
        refs=[IMPL07, API06],
    ),
    case(
        "INT-SCR-003-CANCEL", "SCR-003 CANCEL: irreversible abort releases reservations and audits the abort",
        CC_SUITE, "integration", ["SCR-003", "AUTH-4", "BR-005", "NFR-002"],
        ["entity:Approval", "entity:Action", "stage:APPROVAL"], "baseline", "P0", "critical",
        "Cancelling a campaign leaves budget or inventory reservations held, so the tenant pays for capacity it will never use, and the abort is unlogged.",
        [GOV_FX],
        _CC_PRE + ["APV-CAMP-15 pending with a budget reservation of 186750 TWD held in the synthetic budget ledger."],
        {"cancel": {"decision": "CANCEL", "operator_id": "OP-APPROVER-T1", "reason": "Campaign postponed; budget released for the next quarter."},
         "reservations_before": {"budget_twd": 186750, "audience_hold": 12000}},
        [("Read the reservation ledger before the decision",
          "The ledger shows budget 186750 TWD and audience hold 12000 held by the run."),
         ("Submit CANCEL",
          "HTTP 200 with status CANCELLED; the task is terminal and cannot be resumed by any later decision."),
         ("Read the reservation ledger and audit rows after the decision",
          "Both reservations are released to 0 and an immutable audit row records the cancellation with the operator and reason."),
         ("Attempt an APPROVE on the cancelled item",
          "The decision is rejected; the cancelled state is terminal and no execution occurs.")],
        ["CANCEL releases every held reservation atomically; the ledger shows 0 for both reservation types.",
         "The cancelled state is terminal: no later decision can execute the payload.",
         "An immutable audit row records the abort with operator identity, timestamp and reason.",
         "Zero adapter sends occur before, during and after cancellation."],
        ["Releasing only the budget and leaking the audience hold.",
         "Allowing a later approval to revive a cancelled run.",
         "Logging the cancellation as a rejection or losing the reason."],
        ["Reservation ledger before/after snapshots.",
         "Cancellation audit row and the rejected late-decision response."],
        ["Delete " + NS + " approval rows; released reservations are restored to the fixture ledger state."],
        _CC_AUTO,
        refs=[IMPL07, API06],
    ),
    case(
        "INT-SCR-004", "SCR-004 Customer 360: unified timeline with evidence-class separation",
        CC_SUITE, "integration", ["SCR-004", "FR-C360-002", "FR-C360-003", "NFR-006"],
        ["entity:Customer", "entity:Evidence", "memory:Customer Context", "stage:EVIDENCE"], "baseline", "P0", "critical",
        "The timeline collapses facts, signals, hypotheses, decisions and actions into one undifferentiated feed, so an operator treats a churn hypothesis as an established fact about the customer.",
        [EVENTS_FX, CUST_FX],
        _CC_PRE + ["cust-a timeline seeded with one entry of each class and a hypothesis whose confidence is 0.68."],
        {"request": {"method": "GET", "path": "/api/v1/customers/cust-a/360", "tenant": "T1"},
         "seeded_classes": ["FACT", "SIGNAL", "HYPOTHESIS", "DECISION", "ACTION"]},
        [("Fetch the Customer 360 payload for cust-a",
          "Timeline entries are ordered by event time and each carries exactly one evidence class from the five baseline classes."),
         ("Inspect the hypothesis entry",
          "It is labelled HYPOTHESIS with a confidence value and its supporting evidence references; it is never rendered as FACT."),
         ("Follow the evidence references on one ACTION entry",
          "The referenced receipts resolve to the same run and effect_key that produced the action.")],
        ["All five classes are represented and mutually exclusive per entry.",
         "A hypothesis retains its class and confidence after a page refresh and is not upgraded to fact by the UI.",
         "Every action entry links to at least one evidence reference that resolves to a real record.",
         "Timeline ordering is by business event time, not by ingestion time."],
        ["Flattening the timeline into FACT and HYPOTHESIS only.",
         "Rendering a hypothesis with fact wording.",
         "Showing an action without its evidence reference."],
        ["Customer 360 payload with classes and evidence references.",
         "Screenshot plus accessibility tree of the timeline.",
         "Resolved evidence record for one action entry."],
        ["Remove the " + NS + " timeline and evidence rows for cust-a."],
        _CC_AUTO,
        refs=[IMPL07, SRS],
    ),
    case(
        "INT-SCR-004-KEYBOARD", "SCR-004 accessibility: timeline and evidence reachable by keyboard with announced classes",
        CC_SUITE, "integration", ["SCR-004", "SCR-005", "NFR-007"],
        ["entity:Evidence"], "extension", "P1", "high",
        "Operators who cannot use a mouse cannot review a customer timeline, so escalation decisions stall and accessibility compliance fails.",
        [GOV_FX, CUST_FX],
        _CC_PRE + ["The Customer 360 view is rendered with cust-a data; pointer input is disabled for the duration of the case."],
        {"keyboard_script": ["Tab to the timeline region", "Arrow down through entries", "Enter to open evidence detail",
                             "Escape to close the detail", "Tab to the filter control and apply the ACTION filter"]},
        [("Tab into the page and navigate to the timeline region",
          "Focus reaches the timeline without a pointer; the focused element has a visible focus indicator and an accessible name that includes the customer."),
         ("Move through the timeline entries with the arrow keys",
          "Each entry is announced with its evidence class, timestamp and summary; the current position is exposed to assistive technology."),
         ("Open one evidence detail with Enter and close it with Escape",
          "The detail opens, focus moves into it, and Escape returns focus to the originating entry."),
         ("Apply the ACTION filter using the keyboard only",
          "The list narrows to ACTION entries and the result count is announced.")],
        ["Every interactive control on the timeline is reachable and operable with the keyboard alone.",
         "Each entry exposes role, name and the evidence class to the accessibility tree.",
         "Focus is never lost after opening or closing the detail panel.",
         "The filtered count is exposed as text and matches the number of ACTION entries in the payload."],
        ["Using a div with a click handler as the only affordance for evidence detail.",
         "Moving focus to the document body on close.",
         "Conveying class only through colour."],
        ["Accessibility tree snapshot with roles and names.",
         "Focus sequence log (element identities in order).",
         "Screen recording or screenshot of the focus indicator."],
        ["Reset the filter and release the keyboard-only session namespace."],
        _CC_AUTO + " Uses accessibility-tree queries and element-identity assertions rather than CSS selectors, so class names cannot make the case pass.",
        refs=[IMPL07, SRS],
    ),
    case(
        "INT-SCR-004-FOREIGN-DATA", "SCR-004 isolation: a session for one customer renders no other customer's data",
        CC_SUITE, "integration", ["SCR-004", "NFR-006", "FR-C360-001"],
        ["entity:Customer", "memory:Customer Context"], "baseline", "P0", "critical",
        "A cache key mistake or an unbounded query shows customer B's orders inside customer A's profile, which is a reportable privacy breach.",
        [CUST_FX, ORDERS_FX],
        _CC_PRE + ["Two sessions exist: session A verified as cust-a, session B verified as cust-b; ORD-A-1 and ORD-B-1 belong to each respectively."],
        {"session_a_request": {"method": "GET", "path": "/api/v1/customers/cust-a/360", "session": "sess-a-1"},
         "session_b_request": {"method": "GET", "path": "/api/v1/customers/cust-b/360", "session": "sess-b-1"},
         "cross_request": {"method": "GET", "path": "/api/v1/customers/cust-b/360", "session": "sess-a-1"}},
        [("Load the profile in session A",
          "The payload contains cust-a identifiers and ORD-A-1; it contains no cust-b identifier or ORD-B-1."),
         ("Load the profile in session B in a separate browser context",
          "The payload contains cust-b identifiers and ORD-B-1 only."),
         ("In session A, request cust-b profile explicitly",
          "The request is refused (authorization or not-found) and no cust-b data appears in the response body."),
         ("Scan both successful payloads for the other customer's identifiers, orders and phone digits",
          "Zero cross-customer occurrences in both payloads.")],
        ["Each session returns exactly one customer context; cross-request returns no foreign fields.",
         "Zero occurrences of the other customer's order id, phone digits or session token in either payload.",
         "Any shared cache key includes the verified customer or session identity, demonstrable by the distinct payloads.",
         "The refusal is audited rather than being a silent 404 with no trace."],
        ["Serving a cached profile without keying on the session identity.",
         "Returning a generic 403 while the body still contains the foreign profile.",
         "Falling back to a wildcard tenant query when the customer binding is missing."],
        ["Both 360 payloads and the refusal response body (redacted).",
         "Cache key inspection output showing per-session keying.",
         "Audit row for the refused cross-request."],
        ["Clear both " + NS + " session namespaces and any customer context cache entries."],
        _CC_AUTO,
        refs=[IMPL07, SRS],
    ),
    case(
        "INT-SCR-005", "SCR-005 Conversation Console: takeover locks the bot out and resume returns control",
        CC_SUITE, "integration", ["SCR-005", "NFR-007", "NFR-006"],
        ["entity:Conversation", "stage:ACTION"], "baseline", "P1", "critical",
        "The bot keeps answering while a human is handling the conversation, so the customer receives contradictory replies and loses trust.",
        [GOV_FX, CUST_FX],
        _CC_PRE + ["Conversation conv-gov-1 is ACTIVE with cust-a; the mock chat adapter counts outbound messages and exposes the lease key."],
        {"takeover": {"method": "POST", "path": "/api/v1/conversations/conv-gov-1/takeover",
                      "body": {"operator_id": "OP-SUPERVISOR-T1", "reason": "Complaint escalation", "takeover_mode": "HUMAN_ACTIVE"}},
         "resume": {"method": "POST", "path": "/api/v1/conversations/conv-gov-1/resume",
                    "body": {"operator_id": "OP-SUPERVISOR-T1", "reason": "Issue resolved"}}},
        [("Submit the takeover request",
          "HTTP 200; conversation status becomes HUMAN_TAKEOVER and the lease key tenant:T1:session:conv-gov-1:takeover_lock exists with the operator id and an expiry."),
         ("Dispatch an agent message-generation task for the same conversation",
          "The task is denied with HTTP 409 Conversation Locked by Human Operator and no outbound message is produced."),
         ("Send an operator reply through the console",
          "The operator message is delivered once and is attributed to the human sender."),
         ("Submit the resume request",
          "HTTP 200; status returns to ACTIVE, the lease key is gone, and a subsequent agent task is permitted.")],
        ["The takeover lease exists during the takeover with a bounded TTL, and the AI outbound path is denied with 409.",
         "Agent message attempts during takeover produce zero outbound messages at the adapter.",
         "Resume is the only release path and it returns the conversation to ACTIVE with the agent able to reply again.",
         "The bot continues only in AUTH-2 draft mode during takeover (draft stored internally, never sent)."],
        ["Letting the agent reply during takeover.",
         "Releasing the lease with an ad-hoc delete route instead of resume.",
         "Applying the takeover flag as an agent authority grant (AUTH-5 confusion)."],
        ["Lease key value and TTL at takeover, plus its absence after resume.",
         "409 response body for the blocked agent task.",
         "Adapter message log with senders and count.",
         "Conversation status history."],
        ["Call resume if the case aborted mid-way, then delete the " + NS + " conversation rows and lease keys."],
        _CC_AUTO + " The Redis lease and the console state machine run as real code; the chat adapter is the substituted boundary and its message log is the oracle.",
        refs=[IMPL07, API06],
    ),
    case(
        "INT-SCR-005-CONCURRENT-SEND", "SCR-005 mutex race: concurrent agent sends during takeover are all denied",
        CC_SUITE, "integration", ["SCR-005", "NFR-007", "NFR-003"],
        ["entity:Conversation", "stage:EXECUTION"], "extension", "P1", "critical",
        "A race between takeover and an in-flight agent send lets one bot message slip out after the human took over, contradicting the operator to the customer.",
        [GOV_FX],
        _CC_PRE + ["Conversation conv-gov-2 is ACTIVE; five agent message tasks are queued in the same worker pool."],
        {"race": {"takeover_at": "after_task_2_dispatched",
                  "tasks": [{"id": "t1"}, {"id": "t2"}, {"id": "t3"}, {"id": "t4"}, {"id": "t5"}],
                  "operator": "OP-SUPERVISOR-T1"}},
        [("Dispatch tasks t1 and t2 and confirm both are permitted",
          "Two outbound bot messages are delivered and the adapter counter reads 2."),
         ("Acquire the takeover lease, then let t3, t4 and t5 attempt dispatch",
          "All three are denied with 409; the adapter counter stays at 2."),
         ("Release the lease with resume and dispatch t6",
          "t6 is permitted and the counter advances to 3.")],
        ["No bot message is delivered after the lease is acquired: counter is exactly 2 at that point.",
         "Every post-takeover task returns 409 with the locked reason, not a generic failure.",
         "The mutex is checked at dispatch time, so an already-queued task cannot bypass it.",
         "After resume exactly one further message is delivered, proving the lock was released cleanly."],
        ["Checking the lease only at enqueue time so queued tasks slip through.",
         "Dropping the denied tasks silently with no audit row.",
         "Double-releasing the lock so two senders proceed concurrently."],
        ["Adapter message log with timestamps and the counter at each phase.",
         "409 responses for t3 to t5.",
         "Lease lifecycle log."],
        ["Resume and delete the " + NS + " conversation, task and lease keys."],
        _CC_AUTO + " Task dispatch is ordered deterministically by the harness (each task awaited), and the lease is manipulated only through the supported takeover/resume routes.",
        refs=[IMPL07, SRS],
    ),
    case(
        "INT-SCR-005-SECOND-OPERATOR", "SCR-005 second operator: a competing takeover is refused with 409",
        CC_SUITE, "integration", ["SCR-005", "NFR-007"],
        ["entity:Conversation"], "extension", "P1", "high",
        "Two operators both believe they are handling the conversation and both reply, producing duplicate and contradictory answers to the customer.",
        [GOV_FX],
        _CC_PRE + ["OP-SUPERVISOR-T1 holds no lease; OP-SECOND-T1 is an equally authorized supervisor on tenant T1."],
        {"first": {"operator_id": "OP-SUPERVISOR-T1"}, "second": {"operator_id": "OP-SECOND-T1"}},
        [("Operator 1 acquires the takeover lease",
          "HTTP 200 and the lease value names OP-SUPERVISOR-T1."),
         ("Operator 2 attempts takeover",
          "HTTP 409; the lease value still names OP-SUPERVISOR-T1 and no new lease is created."),
         ("Operator 2 sends a message anyway through the console",
          "The message is refused because the session is not bound to that operator, and the adapter counter does not advance."),
         ("Operator 1 resumes, then operator 2 takes over",
          "The second takeover now succeeds, proving the refusal was contention and not a permanent authorization error.")],
        ["Exactly one lease holder exists at any time; the second attempt returns 409 and does not overwrite the holder.",
         "A non-holder cannot send on the conversation; adapter counter unchanged.",
         "The refused attempt is recorded so the collision is observable.",
         "Contention refusal is distinct from an authorization failure (409 versus 403)."],
        ["Overwriting the lease so both operators believe they hold it.",
         "Allowing the non-holder to reply because the UI still shows the composer.",
         "Returning 403 for contention so operators raise a permissions ticket."],
        ["Lease values after each attempt.",
         "409 body for the second takeover and the refusal record for the non-holder send.",
         "Adapter counter log."],
        ["Resume with operator 1, then delete " + NS + " conversation and lease keys."],
        _CC_AUTO,
        refs=[IMPL07, SRS],
    ),
    case(
        "INT-SCR-005-LEASE-EXPIRY", "SCR-005 crashed operator tab: the 60 second lease expires and the agent recovers",
        CC_SUITE, "integration", ["SCR-005", "NFR-007", "NFR-004"],
        ["entity:Conversation", "stage:EXECUTION"], "extension", "P1", "critical",
        "An operator closes their laptop mid-conversation and the customer is locked out permanently, or the lease expires while the operator is still typing and the bot interrupts them.",
        [GOV_FX],
        _CC_PRE + ["Lease TTL 60 s and heartbeat interval 30 s from the fixture; the clock is injected so expiry is deterministic."],
        {"phases": [{"t": 0, "action": "takeover"}, {"t": 30, "action": "heartbeat"},
                    {"t": 60, "action": "no heartbeat (tab crashed)"}, {"t": 125, "action": "expect lease gone"},
                    {"t": 200, "action": "operator returns and attempts takeover again"}]},
        [("Take over and heartbeat once at t=30",
          "The lease expiry advances past t=60 and the conversation stays HUMAN_TAKEOVER."),
         ("Stop heartbeating and advance the injected clock past the TTL",
          "At t=125 the lease key is absent, the conversation returns to ACTIVE and agent tasks are permitted again."),
         ("Attempt an operator message at t=130 with no valid lease",
          "The message is refused because the operator no longer holds the lease, and the refusal is recorded."),
         ("Take over again at t=200",
          "Takeover succeeds with a fresh lease, proving recovery rather than permanent lockout.")],
        ["The lease always carries a bounded TTL; there is no unbounded takeover.",
         "After TTL expiry with no heartbeat the conversation returns to agent control without manual intervention.",
         "A stale operator cannot send after losing the lease.",
         "Death of the operator tab does not require an administrative unlock to restore service."],
        ["An unbounded lease that permanently locks the customer conversation.",
         "Expiry that silently changes the operator identity or drops the conversation state.",
         "Allowing the stale operator to keep sending because the client still holds local state."],
        ["Lease key lifecycle log with expiry timestamps under the injected clock.",
         "Conversation status at each phase.",
         "Refusal record for the stale operator send."],
        ["Ensure no lease remains for the namespace and delete " + NS + " conversation rows."],
        _CC_AUTO + " Clock advancement is injected; the case never sleeps 125 real seconds.",
        refs=[IMPL07, SRS],
    ),
    case(
        "INT-SCR-005-EDIT-EVALUATION", "SCR-005 edit and evaluate: an operator-edited reply is attributed and evaluated",
        CC_SUITE, "integration", ["SCR-005", "NFR-005", "NFR-002"],
        ["entity:Conversation", "entity:Outcome", "stage:OUTCOME"], "extension", "P1", "high",
        "Operator edits are sent as if they were the AI reply, so KPIs credit the AI for human work and the learning loop trains on text nobody reviewed.",
        [GOV_FX],
        _CC_PRE + ["An AUTH-2 copilot draft exists for conv-gov-3; the operator edits it before sending."],
        {"draft": {"text": "Your parcel is delayed by two days; a replacement ships today."},
         "edited": {"text": "Your parcel is delayed by two days; a replacement ships today and we waive the shipping fee."},
         "evaluation": {"rating": "PARTIAL", "note": "Draft missed the goodwill gesture."}},
        [("Open the copilot draft during takeover",
          "The draft is labelled as an AI suggestion in AUTH-2 mode and is not yet sent."),
         ("Edit the draft and send it",
          "The outbound message is attributed to the operator, and the AI-generated flag is cleared on the conversation turn."),
         ("Record an evaluation of the original draft",
          "The evaluation record links the draft, the operator edit and the rating, and it stores the reason text."),
         ("Check the human override accounting",
          "The session is counted as a human override so Autonomous Completion Rate and AI Resolution Rate exclude it.")],
        ["The sent message is attributed to the human, and the AI-generated flag is false on that turn.",
         "The evaluation record references both the original draft and the edit, with the rating and note.",
         "The override counter increments by exactly one for this session, so AI-resolved metrics exclude it.",
         "The original unedited draft remains retrievable for learning rather than being overwritten."],
        ["Attributing the edited message to the AI.",
         "Discarding the original draft so no comparison is possible.",
         "Counting the session as autonomous because the draft came from the AI."],
        ["Conversation turns with sender attribution and the AI-generated flag.",
         "Evaluation record plus the retained original draft.",
         "Override counter value before and after."],
        ["Delete " + NS + " conversation, draft and evaluation rows after exporting evidence."],
        _CC_AUTO,
        refs=[IMPL07, ANALYTICS],
    ),
    case(
        "INT-SCR-005-RESUME-REVALIDATION", "SCR-005 resume re-validates consent, context and pending orders before the agent replies",
        CC_SUITE, "integration", ["SCR-005", "BR-004", "NFR-008", "NFR-007"],
        ["entity:Consent", "entity:Conversation", "stage:APPROVAL"], "extension", "P1", "critical",
        "The agent resumes with a stale plan and delivers a message or an offer the customer has since revoked consent for, or that references an order already refunded.",
        [GOV_FX, CONSENT_FX, ORDERS_FX],
        _CC_PRE + ["Conv-gov-4 is under human takeover with a queued draft that offers a marketing discount; cust-a revokes EMAIL marketing consent and ORD-A-1 is refunded while the operator holds the lease."],
        {"revocations": [{"type": "CONSENT_REVOKED", "customer_id": "cust-a", "channel": "EMAIL", "purpose": "marketing"},
                         {"type": "ORDER_REFUNDED", "order_id": "ORD-A-1"}],
         "queued_draft": {"text": "Here is your 10 percent win-back code.", "channel": "EMAIL", "purpose": "marketing"}},
        [("Change the underlying state while the conversation is under takeover",
          "Consent becomes revoked and ORD-A-1 becomes REFUNDED in the mock SoR."),
         ("Submit the resume request",
          "Resume returns 200 and the console reports a re-validation step (RESUME_AUDIT) whose result is recorded."),
         ("Attempt to dispatch the queued marketing draft after resume",
          "The draft is suppressed by the consent check; the adapter counter for EMAIL marketing stays at 0."),
         ("Ask for the order status after resume",
          "The reply reflects the refunded status of ORD-A-1 rather than the previously cached SHIPPED status.")],
        ["Resume re-validates consent and context; a stale draft cannot be sent after a revocation.",
         "The marketing draft produces zero adapter calls, while the transactional order-status reply is still allowed.",
         "The re-validation outcome is persisted so the operator can see why the draft was dropped.",
         "The agent context is refreshed: the refunded order state is visible after resume, not the stale one."],
        ["Resuming without re-checking consent because the draft was written before takeover.",
         "Blocking all replies after a marketing revocation, including transactional ones.",
         "Serving cached order state after resume."],
        ["Re-validation record produced during resume with its outcome.",
         "Adapter counter for the marketing channel and the order-status reply payload.",
         "Consent and order state snapshots used by the check."],
        ["Restore the consent fixture state and delete the " + NS + " conversation and draft rows."],
        _CC_AUTO,
        refs=[IMPL07, SRS],
    ),
    case(
        "INT-SCR-005-KEYBOARD", "SCR-005 accessibility: takeover, compose, send and resume are keyboard operable",
        CC_SUITE, "integration", ["SCR-005", "NFR-007"],
        ["entity:Conversation"], "extension", "P1", "high",
        "An operator without a pointing device cannot take over an escalated conversation, so urgent complaints wait or get mishandled.",
        [GOV_FX],
        _CC_PRE + ["Conversation conv-gov-5 is ACTIVE; pointer input is disabled for the whole case."],
        {"keyboard_script": ["Tab to the conversation list and select the conversation",
                             "Tab to the Takeover control and activate it",
                             "Tab into the composer and type a reply",
                             "Activate Send", "Tab to Resume AI control and activate it"]},
        [("Take over using the keyboard only",
          "Takeover succeeds; the status change to HUMAN_TAKEOVER is announced and focus remains in the console."),
         ("Compose and send a reply using the keyboard only",
          "The message is delivered once and the composer clears; the send control has a discernible name."),
         ("Resume using the keyboard only",
          "The conversation returns to ACTIVE and the resumed state is announced."),
         ("Traverse the console and enumerate focusable controls",
          "Every interactive control exposes role, name and enabled state; no control is reachable only by pointer.")],
        ["Takeover, send and resume are all achievable with the keyboard alone.",
         "Each control exposes role, name and state to the accessibility tree.",
         "Status transitions are announced, not conveyed by colour alone.",
         "Exactly one message is delivered during the keyboard-only session."],
        ["Making the takeover control a non-focusable element.",
         "Trapping focus inside the composer after send.",
         "Conveying the takeover state only through a colour change."],
        ["Accessibility tree snapshot of the console with roles and names.",
         "Adapter message log showing the single delivered reply.",
         "Status history with the announced transitions."],
        ["Resume and delete the " + NS + " conversation rows."],
        _CC_AUTO,
        refs=[IMPL07, SRS],
    ),
)
