"""Ordered governance testcase section: kpi."""
from __future__ import annotations


# ===========================================================================
# governance/kpi.md — SRS section 20: the 32 metrics of the five groups
# (SRS-20, plans/delivery/analytics.md metric dictionary and measurement rules)
# ===========================================================================
_KP = GOVERNANCE_FIXTURE["kpi_dataset"]
_MKT = _KP["marketing"]
_SAL = _KP["sales"]
_CARE = _KP["care"]
_RET = _KP["retention"]
_AI = _KP["ai_system"]
_KPI_WINDOW = _KP["window"]

_KPI_PATH = {"Marketing": "marketing", "Sales": "sales", "Customer Care": "care",
             "Customer Success": "retention", "AI System": "ai_system"}

_KPI_PRE = [
    "Namespace " + NS + "kpi-<case_id>-<worker_id>; the metric is computed by the real reporting code over fixtures/offline/governance.json kpi_dataset and never copied from the dashboard payload.",
    "Frozen clock " + CLOCK + " with the reporting window " + _KPI_WINDOW[0] + " .. " + _KPI_WINDOW[1] + " as a half-open interval; the stored aggregate is recomputed independently from the raw counter rows.",
]
_KPI_AUTO = ("The reporting service and the metric dictionary run as real code under test over the frozen KPI dataset; the dashboard "
             "is a consumer whose displayed value must equal the independently recomputed value. Waits are condition-based on the "
             "stored aggregate row, metric values are never supplied as inputs, and no vendor boundary is involved in the arithmetic.")


def _num(value: float) -> str:
    """Render a synthetic number without trailing zeros: 12000.0 -> '12000', 2.5 -> '2.5'."""
    text = f"{float(value):.4f}".rstrip("0").rstrip(".")
    return text or "0"


def _pct(num: float, den: float) -> str:
    """Percentage of a ratio metric; a zero denominator is NOT_DEFINED, never 0."""
    if not den:
        return "NOT_DEFINED (zero denominator)"
    return f"{round(100.0 * num / den, 1)}%"


def _ratio(num: float, den: float) -> str:
    """Multiplier of a ratio metric; a zero denominator is NOT_DEFINED, never 0."""
    if not den:
        return "NOT_DEFINED (zero denominator)"
    return f"{round(float(num) / den, 2)}x"


def _money(value: float, currency: str = "TWD") -> str:
    return _num(value) + " " + currency


def _total(values: list) -> float:
    return float(sum(values))


def _mean(values: list) -> float:
    return round(_total(values) / len(values), 1)


def _median(values: list) -> float:
    ordered = sorted(values)
    middle = len(ordered) // 2
    if len(ordered) % 2:
        return float(ordered[middle])
    return (ordered[middle - 1] + ordered[middle]) / 2.0


def _p95(values: list) -> float:
    """Nearest-rank 95th percentile, never interpolating a value that was not observed."""
    ordered = sorted(values)
    rank = -(-95 * len(ordered) // 100) or 1
    return float(ordered[rank - 1])


_KPI_SPECS = [
    {
        "code": "MKT-01", "name": "Campaign Revenue", "group": "Marketing",
        "gate": "P3", "priority": "high", "reqs": ("SRS-20", "MKT-06", "OBJ-001"),
        "formula": "valid attributed order revenue in the window minus refunded and cancelled attributed orders",
        "expected": _money(_MKT["attributed_revenue_gross_twd"] - _MKT["refunded_attributed_orders_twd"]),
        "bug": "the gross attributed figure of 14000 TWD that still contains the refunded orders",
        "boundary": "a campaign with no attributed order in the window displays NO_DATA, not 0 TWD",
        "numerator": "attributed orders that remain valid (not cancelled, not refunded)",
        "denominator": "not a ratio - a currency amount reported per currency and never summed across currencies",
        "forbid": ("Counting a refunded or cancelled attributed order into campaign revenue.",
                   "Adding attributed revenue from another campaign, tenant or currency into this total."),
        "evidence": ("Attributed order extract with the refunded rows flagged and redacted.",
                     "Recomputed campaign revenue table naming the excluded order ids and the currency."),
        "facets": ("stage:OUTCOME",),
    },
    {
        "code": "MKT-02", "name": "Lead Conversion", "group": "Marketing",
        "gate": "P3", "priority": "high", "reqs": ("SRS-20", "MKT-01", "MKT-06"),
        "formula": "valid leads captured from the campaign divided by the campaign click count for the same window",
        "expected": _pct(_MKT["leads"], _MKT["clicks"]),
        "bug": "leads divided by impressions, which silently re-labels the metric as a reach conversion",
        "boundary": "a campaign with zero clicks returns NOT_DEFINED for the click-denominated variant instead of 0%",
        "numerator": "valid leads recorded in CRM for the campaign",
        "denominator": "campaign clicks (declared denominator: clicks, not impressions)",
        "forbid": ("Switching the denominator between impressions and clicks across two reports.",
                   "Counting unqualified raw form fills as valid leads."),
        "evidence": ("Lead extract with the campaign and click identifiers.",
                     "Recomputation sheet stating the declared denominator."),
        "facets": ("stage:SIGNAL",),
    },
    {
        "code": "MKT-03", "name": "CAC", "group": "Marketing",
        "gate": "P3", "priority": "high", "reqs": ("SRS-20", "MKT-01", "MKT-06"),
        "formula": "allocated marketing and partner cost divided by new valid customers in the window",
        "expected": _money(_MKT["spend_twd"] / _MKT["new_customers"]),
        "bug": "cost divided by all customers, which understates acquisition cost by an order of magnitude",
        "boundary": "with no new customer in the window the metric is NOT_DEFINED rather than 0 TWD",
        "numerator": "allocated marketing and partner cost",
        "denominator": "new valid customers acquired in the same period",
        "forbid": ("Dividing by returning customers so acquisition looks cheaper.",
                   "Omitting partner or affiliate cost from the numerator."),
        "evidence": ("Cost allocation extract with the allocated amounts.",
                     "New-customer list used as the denominator."),
        "facets": ("stage:OUTCOME",),
    },
    {
        "code": "MKT-04", "name": "ROAS", "group": "Marketing",
        "gate": "P3", "priority": "high", "reqs": ("SRS-20", "MKT-01", "MKT-06"),
        "formula": "attributed ad revenue divided by actual ad spend in the window",
        "expected": _ratio(_MKT["attributed_revenue_gross_twd"], _MKT["spend_twd"]),
        "bug": "revenue divided by a planned budget, which reports a return on money that was never spent",
        "boundary": "zero spend returns NOT_DEFINED rather than an infinite or a zero return",
        "numerator": "attributed ad revenue",
        "denominator": "actual ad spend (planned budget excluded)",
        "forbid": ("Using the planned budget as the denominator.",
                   "Publishing ROAS as a currency amount instead of a multiplier."),
        "evidence": ("Ad spend statement extract with the actual amounts.",
                     "Attributed revenue table used as the numerator."),
        "facets": ("stage:OUTCOME",),
    },
    {
        "code": "MKT-05", "name": "Cost per Lead", "group": "Marketing",
        "gate": "P3", "priority": "medium", "reqs": ("SRS-20", "MKT-01", "MKT-06"),
        "formula": "total campaign cost divided by valid leads recorded in CRM",
        "expected": _money(_MKT["spend_twd"] / _MKT["leads"]),
        "bug": "cost divided by raw form fills including duplicates, which dilutes the cost per valid lead",
        "boundary": "no valid lead in the window returns NOT_DEFINED",
        "numerator": "total campaign cost",
        "denominator": "valid leads recorded in CRM after duplicate and fraud filtering",
        "forbid": ("Counting duplicate lead submissions as separate leads in the denominator.",
                   "Charging another channel's campaign cost into this numerator."),
        "evidence": ("Lead deduplication report showing raw and valid lead counts.",
                     "Campaign cost extract with the period."),
        "facets": ("stage:SIGNAL",),
    },
    {
        "code": "MKT-06", "name": "Engagement", "group": "Marketing",
        "gate": "P3", "priority": "medium", "reqs": ("SRS-20", "MKT-03", "MKT-06"),
        "formula": "sum of interactions (comments, messages, link clicks, form fills) divided by impressions",
        "expected": _pct(_total(list(_MKT["engagements"].values())), _MKT["impressions"]),
        "bug": "interactions divided by clicks, which produces an impossible engagement rate above 100%",
        "boundary": "zero impressions returns NOT_DEFINED",
        "numerator": "comments plus messages plus link clicks plus form fills",
        "denominator": "message impressions in the window",
        "forbid": ("Counting an auto-opened message with no customer interaction as engagement.",
                   "Dividing by clicks so the rate can exceed 100%."),
        "evidence": ("Interaction event extract per channel.",
                     "Impression delivery report from the channel provider."),
        "facets": ("channel:EMAIL",),
    },
    {
        "code": "MKT-07", "name": "Qualified Lead Rate", "group": "Marketing",
        "gate": "P3", "priority": "high", "reqs": ("SRS-20", "SAL-01", "MKT-06"),
        "formula": "leads confirmed qualified by sales divided by total leads received",
        "expected": _pct(_MKT["qualified_leads"], _MKT["leads"]),
        "bug": "qualified leads divided by clicks, which changes the denominator to the campaign audience",
        "boundary": "no lead received returns NOT_DEFINED",
        "numerator": "leads confirmed qualified by the sales team or the Sales Agent",
        "denominator": "total leads received in the window",
        "forbid": ("Re-labelling an unconfirmed lead as qualified after it converts.",
                   "Reporting a different denominator on the dashboard than in the Sales report."),
        "evidence": ("Lead qualification decisions with the confirming agent identity.",
                     "Lead intake count used as the denominator."),
        "facets": ("stage:HYPOTHESIS",),
    },
    {
        "code": "SAL-01", "name": "Lead-to-Order Conversion", "group": "Sales",
        "gate": "P2", "priority": "critical", "reqs": ("SRS-20", "OBJ-002", "SAL-01"),
        "formula": "paid orders divided by qualified leads advised in the same observation window",
        "expected": _pct(_SAL["orders_paid"], _SAL["qualified_leads_advised"]),
        "bug": "paid orders divided by all leads, which mixes the marketing lead base into the sales denominator",
        "boundary": "no advised lead in the window returns NOT_DEFINED",
        "numerator": "orders completed with confirmed payment",
        "denominator": "qualified leads advised by the Sales Agent in the window",
        "forbid": ("Counting an unpaid or cancelled order as a converted order.",
                   "Widening the denominator to the whole lead base."),
        "evidence": ("Paid order list with the payment confirmation timestamps.",
                     "Advised-lead log from the Sales Agent."),
        "facets": ("stage:ACTION",),
    },
    {
        "code": "SAL-02", "name": "Cart Recovery Rate", "group": "Sales",
        "gate": "P2", "priority": "high", "reqs": ("SRS-20", "SAL-04", "PILOT-02"),
        "formula": "recovered abandoned-cart orders divided by eligible abandoned-cart sessions",
        "expected": _pct(_SAL["recovered_orders"], _SAL["abandoned_eligible_sessions"]),
        "bug": "recovered orders divided by all abandoned sessions, which counts sessions that were never eligible for contact",
        "boundary": "no eligible session in the window returns NOT_DEFINED",
        "numerator": "abandoned-cart orders recovered inside the 24 hour attribution window",
        "denominator": "abandoned-cart sessions eligible for contact",
        "forbid": ("Counting a recovery outside the 24 hour window as recovered.",
                   "Leaving consent-suppressed sessions in the eligible denominator."),
        "evidence": ("Recovery reminder log with send times and cart links.",
                     "Eligibility filter report showing the suppressed sessions excluded."),
        "facets": ("entity:Order",),
    },
    {
        "code": "SAL-03", "name": "Recommendation Conversion", "group": "Sales",
        "gate": "P2", "priority": "high", "reqs": ("SRS-20", "SAL-03", "FR-SAL-003"),
        "formula": "recommendation click-buys divided by grounded recommendations served",
        "expected": _pct(_SAL["recommendation_click_buys"], _SAL["recommendations_served"]),
        "bug": "click-buys divided by all click-buys in the period, which drops the recommendation denominator entirely",
        "boundary": "no grounded recommendation served returns NOT_DEFINED",
        "numerator": "customer clicks that resulted in buying the recommended product",
        "denominator": "recommendations served with a grounded reason and evidence",
        "forbid": ("Counting a click-buy of a different product as a recommendation conversion.",
                   "Inflating the denominator with ungrounded recommendations to lower the rate."),
        "evidence": ("Recommendation records with their evidence references.",
                     "Click-buy event log joined to the recommendation ids."),
        "facets": ("entity:Recommendation",),
    },
    {
        "code": "SAL-04", "name": "Upsell Revenue", "group": "Sales",
        "gate": "P2", "priority": "medium", "reqs": ("SRS-20", "SAL-03", "FR-SAL-003"),
        "formula": "additional revenue from a higher variant chosen instead of the originally requested product",
        "expected": _money(_total(_SAL["upsell_deltas_twd"])),
        "bug": "counting the full value of the upgraded orders instead of the difference to the requested variant",
        "boundary": "no upgrade in the window reports 0 TWD as a measured zero with window and coverage stated",
        "numerator": "difference between the upgraded variant price and the originally requested product price",
        "denominator": "not a ratio - a currency amount reported per currency",
        "forbid": ("Booking the full order value as upsell revenue.",
                   "Attributing the same difference to more than one order."),
        "evidence": ("Order price-difference table per upgraded order.",
                     "Variant price list used to derive the difference."),
        "facets": ("stage:OUTCOME",),
    },
    {
        "code": "SAL-05", "name": "Cross-sell Revenue", "group": "Sales",
        "gate": "P2", "priority": "medium", "reqs": ("SRS-20", "SAL-03", "FR-SAL-003"),
        "formula": "revenue from AI-suggested accessories, warranty or service add-ons",
        "expected": _money(_total(_SAL["crosssell_order_values_twd"])),
        "bug": "counting the whole order value of orders that contain an add-on, which inflates cross-sell revenue several times over",
        "boundary": "no add-on sold reports 0 TWD with coverage stated, which is distinct from NO_DATA",
        "numerator": "add-on lines attributed to a grounded AI suggestion",
        "denominator": "not a ratio - a currency amount reported per currency",
        "forbid": ("Counting an add-on the customer asked for first as AI cross-sell revenue.",
                   "Double counting an add-on that is also reported as upsell revenue."),
        "evidence": ("Order line extract with the suggestion reference.",
                     "Cross-sell split table used for the attribution."),
        "facets": ("entity:Offer",),
    },
    {
        "code": "SAL-06", "name": "Average Order Value", "group": "Sales",
        "gate": "P2", "priority": "high", "reqs": ("SRS-20", "SAL-02", "FR-SAL-002"),
        "formula": "valid order revenue divided by successful orders after cancel and refund adjustment",
        "expected": _money(_SAL["paid_revenue_twd"] / _SAL["orders_paid"]),
        "bug": "total order value divided by all created orders, which spreads revenue over orders that were cancelled or refunded",
        "boundary": "no successful order in the window returns NOT_DEFINED",
        "numerator": "valid order revenue after cancel and refund adjustments",
        "denominator": "successful orders after cancel and refund adjustments",
        "forbid": ("Leaving cancelled or refunded orders in the denominator.",
                   "Averaging across two currencies inside one figure."),
        "evidence": ("Order revenue reconciliation with the adjusted amounts.",
                     "Successful-order count used as the denominator."),
        "facets": ("entity:Order",),
    },
    {
        "code": "SAL-07", "name": "Sales Cycle", "group": "Sales",
        "gate": "P2", "priority": "medium", "reqs": ("SRS-20", "OBJ-002", "SAL-01"),
        "formula": "mean elapsed hours between first need intake and confirmed payment",
        "expected": _num(_mean(_SAL["sales_cycle_hours"])) + " hours (mean of the eight synthetic cycles)",
        "bug": "the median presented as the sales cycle, or the mean computed over only the orders that converted quickly",
        "boundary": "cycles still open at window end are right-censored and excluded, never counted as 0 hours",
        "numerator": "closed cycles that have both a first-need timestamp and a confirmed-payment timestamp",
        "denominator": "not a ratio - a duration in hours with the censoring rule stated",
        "forbid": ("Counting an abandoned cycle as a zero-length sale.",
                   "Reporting the cycle for only the fastest customer segment."),
        "evidence": ("Cycle table with the first-need and payment timestamps.",
                     "Censoring report listing the cycles excluded at window end."),
        "facets": ("stage:OUTCOME",),
    },
]

# The Customer Care, Customer Success and AI System groups continue the
# section-20 table (all 32 metric names live in `kpi:` facets).
_KPI_SPECS.extend([
    {
        "code": "CS-01", "name": "First Response Time", "group": "Customer Care",
        "gate": "P1", "priority": "high", "reqs": ("SRS-20", "CS-01", "PILOT-03"),
        "formula": "median and p95 seconds between the first customer message and the first value-bearing reply",
        "expected": "median " + _num(_median(_CARE["first_response_seconds"])) + "s and p95 "
                    + _num(_p95(_CARE["first_response_seconds"])) + "s",
        "bug": "the mean published as the median with no p95, so the slower half of the customer base is invisible",
        "boundary": "a conversation with no value-bearing reply is unresolved and excluded from the percentile sample, never counted as 0 seconds",
        "numerator": "first-response intervals measured end to end on the message timestamps",
        "denominator": "conversations with a value-bearing first reply",
        "forbid": ("Counting an automatic acknowledgement as a first response.",
                   "Publishing the median while the required p95 is omitted."),
        "evidence": ("Message timestamp extract per conversation.",
                     "Percentile computation sheet with the sample size."),
        "facets": ("entity:Conversation",),
    },
    {
        "code": "CS-02", "name": "Resolution Time", "group": "Customer Care",
        "gate": "P1", "priority": "high", "reqs": ("SRS-20", "CS-01", "FR-CS-002"),
        "formula": "mean elapsed hours from case opening to confirmed resolution",
        "expected": _num(_mean(_CARE["resolution_hours"])) + " hours (mean of the four synthetic resolved cases)",
        "bug": "the clock stopped at the last agent message instead of at confirmed resolution",
        "boundary": "a case open at window end is right-censored and excluded, never counted as 0 hours",
        "numerator": "cases with a confirmed resolution timestamp",
        "denominator": "not a ratio - a duration in hours with the censoring rule stated",
        "forbid": ("Stopping the clock at the agent's last message instead of confirmed resolution.",
                   "Treating one reopened case as two separate resolutions."),
        "evidence": ("Case lifecycle timestamps with the resolution confirmation.",
                     "Censoring report for cases open at window end."),
        "facets": ("entity:Service Case",),
    },
    {
        "code": "CS-03", "name": "AI Resolution Rate", "group": "Customer Care",
        "gate": "P1", "priority": "critical", "reqs": ("SRS-20", "CS-01", "FR-CS-002"),
        "formula": "AI-closed cases divided by cases eligible for AI resolution, excluding human takeovers",
        "expected": _pct(_CARE["ai_closed"], _CARE["cases_eligible_for_ai"]),
        "bug": "AI-closed cases divided by all cases including human takeovers, or a take-over session credited to the AI",
        "boundary": "no eligible case in the window returns NOT_DEFINED",
        "numerator": "cases closed by the AI with no human intervention",
        "denominator": "cases eligible for AI resolution",
        "forbid": ("Crediting the AI with a case a human took over.",
                   "Counting a reopened case twice so the denominator grows and the rate falls."),
        "evidence": ("Case closure records with the closing agent identity.",
                     "Takeover log used to exclude human-handled sessions."),
        "facets": ("entity:Service Case", "stage:OUTCOME"),
    },
    {
        "code": "CS-04", "name": "Escalation Rate", "group": "Customer Care",
        "gate": "P1", "priority": "high", "reqs": ("SRS-20", "CS-02", "PILOT-04", "FR-CS-002"),
        "formula": "cases handed to a human divided by cases received",
        "expected": _pct(_CARE["escalated"], _CARE["cases_total"]),
        "bug": "only the escalations a human accepted are counted, which hides escalations that expired unanswered",
        "boundary": "no case received in the window returns NOT_DEFINED",
        "numerator": "escalated conversations or cases handed to a human",
        "denominator": "cases received in the window",
        "forbid": ("Dropping an unanswered escalation from the numerator.",
                   "Counting a whole conversation as one case where the platform counts cases."),
        "evidence": ("Escalation records with their final handling state.",
                     "Case intake count used as the denominator."),
        "facets": ("entity:Service Case",),
    },
    {
        "code": "CS-05", "name": "Reopen Rate", "group": "Customer Care",
        "gate": "P1", "priority": "high", "reqs": ("SRS-20", "CS-01", "FR-CS-002"),
        "formula": "cases reopened by the customer within 72 hours of an AI closure divided by AI-closed cases",
        "expected": _pct(_CARE["reopened_within_72h"], _CARE["ai_closed"]),
        "bug": "reopens divided by all closed cases, which dilutes a quality signal that is specifically about AI closures",
        "boundary": "no AI-closed case in the window returns NOT_DEFINED",
        "numerator": "cases reopened within 72 hours after an AI closure",
        "denominator": "cases closed by the AI in the window",
        "forbid": ("Counting a reopen that happened after 72 hours as within the window.",
                   "Counting a reopened case as a new case and losing the reopen flag."),
        "evidence": ("Reopen events with the delta from the AI closure timestamp.",
                     "AI closure list used as the denominator."),
        "facets": ("stage:LEARNING",),
    },
    {
        "code": "CS-06", "name": "Customer Satisfaction", "group": "Customer Care",
        "gate": "P1", "priority": "high", "reqs": ("SRS-20", "CS-01", "FR-CS-002"),
        "formula": "mean survey score with the response rate published alongside it",
        "expected": _num(round(_mean(_CARE["csat_scores"]), 1)) + " out of 5 with a response rate of "
                    + _pct(_CARE["csat_responses"], _CARE["csat_surveys_sent"]),
        "bug": "the mean published with no response rate, so ten responses are presented as the voice of twenty customers",
        "boundary": "no survey response in the window reports NO_DATA, never a score of 0 and never a default of 5",
        "numerator": "survey scores from customer responses",
        "denominator": "surveys sent, published as the response rate",
        "forbid": ("Publishing the average score without the response rate.",
                   "Substituting a default score for the customers who did not respond."),
        "evidence": ("Survey response extract with the scores.",
                     "Survey send count used for the response rate."),
        "facets": ("memory:Customer Context",),
    },
    {
        "code": "SUC-01", "name": "Repeat Purchase", "group": "Customer Success",
        "gate": "P4", "priority": "high", "reqs": ("SRS-20", "OBJ-004", "FR-CS-003"),
        "formula": "customers with a valid N+1 order inside the declared 30/60/90 day window divided by customers at the start",
        "expected": _pct(_RET["repurchase_next"], _RET["customers_start"]),
        "bug": "repeat orders counted instead of repeat customers, or the 30/60/90 day window omitted from the published figure",
        "boundary": "no customer cohort loaded returns NOT_DEFINED, not 0%",
        "numerator": "customers with a valid N+1 order inside the declared 30/60/90 day window",
        "denominator": "customers at the start of the observation window",
        "forbid": ("Omitting the observation window from the published figure.",
                   "Counting the same customer several times for several repeat orders."),
        "evidence": ("Cohort table with the N+1 order dates.",
                     "Window declaration recorded with the metric."),
        "facets": ("entity:Customer",),
    },
    {
        "code": "SUC-02", "name": "Retention", "group": "Customer Success",
        "gate": "P4", "priority": "high", "reqs": ("SRS-20", "OBJ-004", "FR-CS-003"),
        "formula": "customers still active or purchasing at the end of the period divided by customers at the start",
        "expected": _pct(_RET["still_active"], _RET["customers_start"]),
        "bug": "every customer who ever purchased counted as retained, which reports retention far above the observed cohort",
        "boundary": "no cohort at the start returns NOT_DEFINED",
        "numerator": "customers still active or purchasing at period end",
        "denominator": "customers at the start of the period",
        "forbid": ("Counting a dormant customer as retained because no explicit churn was recorded.",
                   "Comparing a cohort from one period against a cohort from another."),
        "evidence": ("Cohort activity table at period end.",
                     "Customer count at period start used as the denominator."),
        "facets": ("stage:OUTCOME",),
    },
    {
        "code": "SUC-03", "name": "Reactivation", "group": "Customer Success",
        "gate": "P4", "priority": "medium", "reqs": ("SRS-20", "OBJ-004", "CS-02"),
        "formula": "dormant customers who repurchase after a care message divided by dormant customers",
        "expected": _pct(_RET["reactivated"], _RET["dormant_customers"]),
        "bug": "reactivated customers divided by all customers, which understates the reactivation programme by a factor of five",
        "boundary": "no dormant customer in the segment returns NOT_DEFINED",
        "numerator": "dormant customers who purchased again after the care message",
        "denominator": "customers dormant for more than 90 days in the segment",
        "forbid": ("Counting a customer who was never dormant as reactivated.",
                   "Omitting the 90 day dormancy definition from the metric."),
        "evidence": ("Dormancy definition and the segment list.",
                     "Reactivation purchase events with their timestamps."),
        "facets": ("entity:Segment",),
    },
    {
        "code": "SUC-04", "name": "Churn", "group": "Customer Success",
        "gate": "P4", "priority": "high", "reqs": ("SRS-20", "OBJ-004", "FR-CS-003"),
        "formula": "one minus the retention rate for the same cohort and period",
        "expected": _pct(_RET["customers_start"] - _RET["still_active"], _RET["customers_start"]),
        "bug": "churn computed from a different cohort, so churn and retention no longer sum to 100%",
        "boundary": "no cohort returns NOT_DEFINED, and churn is never published as 0 as a placeholder",
        "numerator": "customers not returning or cancelling service in the period",
        "denominator": "customers at the start of the period",
        "forbid": ("Reporting churn from a definition under which churn plus retention differs from 100%.",
                   "Treating an unmeasured period as zero churn."),
        "evidence": ("Churn computation sheet reconciling churn and retention to 100%.",
                     "Cohort lists for the period."),
        "facets": ("stage:LEARNING",),
    },
    {
        "code": "SUC-05", "name": "Customer Lifetime Value", "group": "Customer Success",
        "gate": "P4", "priority": "medium", "reqs": ("SRS-20", "OBJ-004", "FR-CS-003"),
        "formula": "contribution value actually generated divided by the customers it came from over the observed attachment period",
        "expected": _money(_RET["contribution_total_twd"] / _RET["customers_for_clv"]),
        "bug": "gross revenue divided by the same customer count and published as lifetime value, which counts revenue as contribution",
        "boundary": "no observed attachment period returns NO_DATA rather than a projection",
        "numerator": "contribution value actually generated (not gross revenue)",
        "denominator": "observed customers that generated it",
        "forbid": ("Presenting a forecast as measured lifetime value.",
                   "Using gross revenue in place of contribution value."),
        "evidence": ("Contribution computation showing the cost deductions.",
                     "Observed attachment period recorded with the figure."),
        "facets": ("entity:Customer",),
    },
    {
        "code": "AI-SYS-01", "name": "Autonomous Completion Rate", "group": "AI System",
        "gate": "P5", "priority": "high", "reqs": ("SRS-20", "OBJ-005", "PILOT-01"),
        "formula": "task chains executed autonomously from signal to outcome divided by tasks assigned",
        "expected": _pct(_AI["autonomous_completed"], _AI["tasks_assigned"]),
        "bug": "assigned tasks that ended in escalation counted as autonomous completions, which reports autonomy that did not happen",
        "boundary": "no task assigned in the window returns NOT_DEFINED",
        "numerator": "task chains that reached an outcome without human intervention",
        "denominator": "tasks assigned to agents in the window",
        "forbid": ("Counting an escalated task as an autonomous completion.",
                   "Counting a task chain that stopped before outcome capture as complete."),
        "evidence": ("Task ledger with the terminal state and the human-intervention flag.",
                     "Outcome records per completed chain."),
        "facets": ("stage:OUTCOME",),
    },
    {
        "code": "AI-SYS-02", "name": "Human Override Rate", "group": "AI System",
        "gate": "P1", "priority": "high", "reqs": ("SRS-20", "NFR-007", "AUTH-4"),
        "formula": "sessions or decisions modified, blocked or taken over by a human divided by sessions in the window",
        "expected": _pct(_AI["sessions_human_override"], _AI["sessions_total"]),
        "bug": "only full takeovers counted, so human edits and pauses disappear from the override signal",
        "boundary": "no session in the window returns NOT_DEFINED",
        "numerator": "sessions or decisions edited, blocked, paused or taken over by a human",
        "denominator": "sessions in the window",
        "forbid": ("Counting only takeovers and dropping human edits and pauses.",
                   "Counting the same session twice for two overrides in one session."),
        "evidence": ("Override audit rows with the override kind.",
                     "Session list used as the denominator."),
        "facets": ("entity:Conversation", "stage:APPROVAL"),
    },
    {
        "code": "AI-SYS-03", "name": "Policy Violation Rate", "group": "AI System",
        "gate": "P0", "priority": "critical", "release_blocker": True,
        "reqs": ("SRS-20", "NFR-001", "BR-008", "AUTH-5"),
        "formula": "authority-boundary or price/data rule violations divided by tasks assigned; the required value is exactly zero",
        "expected": _pct(_AI["policy_violations"], _AI["tasks_assigned"]) + " and the invariant is exactly zero",
        "bug": "0.0% reported while violation rows exist, or a violation excluded because it was blocked before execution",
        "boundary": "no task in the window returns NOT_DEFINED for the rate while the invariant is still reported, because zero violations must be provable",
        "numerator": "violations of the authority boundary or the price/data rule set, whether or not execution was blocked",
        "denominator": "tasks assigned in the window",
        "forbid": ("Excluding a blocked violation attempt from the numerator.",
                   "Relaxing the invariant because the KPI baseline is not locked."),
        "evidence": ("DENY audit rows from the PEP including blocked attempts.",
                     "Violation count reconciled with an independent audit-store query."),
        "facets": ("entity:Agent", "stage:DECISION"),
    },
    {
        "code": "AI-SYS-04", "name": "Hallucination/Error Rate", "group": "AI System",
        "gate": "P1", "priority": "critical", "reqs": ("SRS-20", "NFR-005", "NFR-008"),
        "formula": "audited answers found fabricated, mispriced or against policy divided by answers audited",
        "expected": _pct(_AI["hallucination_findings"], _AI["answers_audited"]),
        "bug": "findings divided by all messages, or findings dropped because the sampled answer was later corrected",
        "boundary": "no answer audited returns NOT_DEFINED rather than 0%, because an empty sample is not evidence of quality",
        "numerator": "audited answers found fabricated, mispriced or against policy",
        "denominator": "answers audited in the window",
        "forbid": ("Reporting 0% from an empty audit sample.",
                   "Removing a finding because the answer was later corrected."),
        "evidence": ("Audit findings with the answer ids and the failure category.",
                     "Audit sample size and sampling method."),
        "facets": ("stage:EVIDENCE",),
    },
    {
        "code": "AI-SYS-05", "name": "Cost per Successful Outcome", "group": "AI System",
        "gate": "P4", "priority": "high", "reqs": ("SRS-20", "NFR-010", "OBJ-006"),
        "formula": "AI API and infrastructure cost divided by successfully resolved orders or care cases",
        "expected": _money(_AI["ai_cost_total_twd"] / _AI["successful_outcomes"]),
        "bug": "cost divided by all attempts, which spreads cost over work that produced no outcome at all",
        "boundary": "no successful outcome in the window returns NOT_DEFINED, never a cost of 0",
        "numerator": "AI model, API and infrastructure cost",
        "denominator": "orders and care cases resolved successfully",
        "forbid": ("Omitting tool, connector or human-assist cost from the numerator.",
                   "Substituting a design target for the measured cost."),
        "evidence": ("Provider billing and usage extract.",
                     "Successful outcome list used as the denominator."),
        "facets": ("stage:OUTCOME",),
    },
    {
        "code": "AI-SYS-06", "name": "Failed Execution", "group": "AI System",
        "gate": "P1", "priority": "high", "reqs": ("SRS-20", "NFR-008", "BR-010"),
        "formula": "failed tool or connector executions divided by total executions, with unknown outcomes tracked separately",
        "expected": _pct(_AI["executions_failed"], _AI["executions_total"]),
        "bug": "an unknown outcome after a dropped response counted as a failure, or failures hidden because a later retry succeeded",
        "boundary": "no execution in the window returns NOT_DEFINED, and an unknown outcome goes to its own bucket rather than counting as failure or success",
        "numerator": "executions that failed or errored (unknown outcomes tracked separately)",
        "denominator": "total executions in the window",
        "forbid": ("Recording a failed execution as success because a retry later succeeded.",
                   "Counting an unknown outcome as a duplicate execution."),
        "evidence": ("Execution ledger with status and retry links.",
                     "Fail-closed and unknown-outcome records for the window."),
        "facets": ("entity:Execution",),
    },
    {
        "code": "AI-SYS-07", "name": "Duplicate Execution", "group": "AI System",
        "gate": "P0", "priority": "critical", "release_blocker": True,
        "reqs": ("SRS-20", "NFR-003", "BR-005", "BR-006"),
        "formula": "duplicate sends or orders caused by an idempotency error divided by total executions; the required value is exactly zero",
        "expected": _pct(_AI["duplicate_executions"], _AI["executions_total"]) + " and the invariant is exactly zero",
        "bug": "0.0% reported while a duplicate send exists, or a duplicate explained away as a vendor artifact and excluded",
        "boundary": "no execution in the window returns NOT_DEFINED for the rate while the invariant is still reported",
        "numerator": "duplicate sends or orders caused by an idempotency error",
        "denominator": "total executions in the window",
        "forbid": ("Excluding a duplicate because the customer did not complain.",
                   "Reporting the invariant as a target that may be missed under ASM-002."),
        "evidence": ("Effect-key reconciliation showing exactly one effect per key.",
                     "Duplicate investigation record with the execution ids."),
        "facets": ("entity:Execution", "stage:EXECUTION"),
    },
])


def _kpi_case(spec: dict) -> dict:
    """One case per SRS section-20 metric: declared formula, scope and missing-data behaviour."""
    name = spec["name"]
    expected = spec["expected"]
    dataset = "kpi_dataset." + _KPI_PATH[spec["group"]]
    release = spec.get("release_blocker", False)
    asserts = [
        name + " equals " + expected + " for the frozen window, recomputed from the raw counter rows with numerator scope '"
        + spec["numerator"] + "' and denominator scope '" + spec["denominator"] + "'.",
        "A recomputation that yields " + spec["bug"] + " is detected as wrong: the stored aggregate and the independent "
        "recomputation must agree before the figure is published.",
        "The dashboard payload for the same tenant and window carries the stored value with its window, coverage and measurement "
        "source; it substitutes neither a design target nor another metric's value.",
        "Boundary behaviour: " + spec["boundary"] + "; missing source data is never rendered as a measured zero.",
    ]
    if release:
        asserts.append(name + " must be exactly 0: any non-zero value blocks the release instead of being reported as a target "
                       "miss waiting for the ASM-002 baseline.")
    return case(
        "GOV-KPI-" + spec["code"],
        spec["code"] + " " + name + ": declared formula, numerator and denominator with honest missing-data behaviour",
        KPI_SUITE, "governance", list(spec["reqs"]),
        ["kpi:" + name] + list(spec["facets"]),
        "baseline", spec["gate"], spec["priority"],
        "The " + name + " figure is produced under different accounting rules - " + spec["bug"] + " - so the KPI is wrong in the "
        "direction that flatters the programme and every decision taken on it inherits the error.",
        [GOV_FX],
        _KPI_PRE + [
            "Metric scope is fixed before measurement: numerator is " + spec["numerator"] + "; denominator is "
            + spec["denominator"] + ".",
            "The dictionary entry for '" + name + "' (owner, unit, window, exclusion rule) is loaded read-only and is compared "
            "with the recomputation instead of being trusted.",
        ],
        {"metric": name, "code": spec["code"], "group": spec["group"], "dataset": dataset,
         "formula": spec["formula"], "window": list(_KPI_WINDOW), "currency": "TWD",
         "expected_value": expected, "wrong_value_if_buggy": spec["bug"],
         "release_blocker": release, "expected_boundary_behaviour": spec["boundary"]},
        [("Compute " + name + " from the frozen rows in " + dataset,
          "The stored aggregate reports " + expected + " and records the formula, the window and the currency that produced it."),
         ("Recompute " + name + " independently from the raw counter rows for the same tenant and window",
          "The recomputed value equals the stored value " + expected + ", and every numerator row lies inside the denominator scope."),
         ("Force the empty-source variant of the metric (no qualifying row in the window)",
          "The metric reports " + spec["boundary"] + "; the display distinguishes missing source data from a measured zero."),
         ("Read the dashboard payload and the metric dictionary entry",
          "The dashboard renders the stored value with its window, coverage and source, and the dictionary names the owner, unit, "
          "numerator and denominator that the recomputation used.")],
        asserts,
        list(spec["forbid"]),
        list(spec["evidence"]),
        ["Delete " + NS + " aggregate, raw-counter and scenario rows for " + spec["code"] + " after exporting the recomputation table."],
        _KPI_AUTO,
        refs=[ANALYTICS, SRS],
    )


_add(*[_kpi_case(spec) for spec in _KPI_SPECS])


_KPI_ALL_METRICS = ("Campaign Revenue", "Lead Conversion", "CAC", "ROAS", "Cost per Lead", "Engagement",
                    "Qualified Lead Rate", "Lead-to-Order Conversion", "Cart Recovery Rate",
                    "Recommendation Conversion", "Upsell Revenue", "Cross-sell Revenue", "Average Order Value",
                    "Sales Cycle", "First Response Time", "Resolution Time", "AI Resolution Rate",
                    "Escalation Rate", "Reopen Rate", "Customer Satisfaction", "Repeat Purchase", "Retention",
                    "Reactivation", "Churn", "Customer Lifetime Value", "Autonomous Completion Rate",
                    "Human Override Rate", "Policy Violation Rate", "Hallucination/Error Rate",
                    "Cost per Successful Outcome", "Failed Execution", "Duplicate Execution")

_add(
    case(
        "GOV-KPI-DICTIONARY", "Metric dictionary completeness: all 32 section-20 metrics have owner, unit, window and exclusions",
        KPI_SUITE, "governance", ["SRS-20", "NFR-002"],
        ["kpi:" + metric for metric in _KPI_ALL_METRICS],
        "blueprint", "P0", "high",
        "A metric is quoted in a gate or an investor document that the dictionary never defined, so numerator, denominator and window are decided per report and two teams publish two different numbers under one name.",
        [GOV_FX],
        _KPI_PRE + ["The dictionary is loaded read-only together with the section-20 metric list; the case may not add, rename or merge a metric.",
                    "A metric without a covering case is treated as a coverage gap that is reported, not as an empty dashboard cell."],
        {"expected_metric_count": len(_KPI_ALL_METRICS),
         "expected_group_counts": {"Marketing": 7, "Sales": 7, "Customer Care": 6,
                                   "Customer Success": 5, "AI System": 7},
         "required_entry_fields": ["name", "group", "owner", "unit", "numerator", "denominator", "window", "exclusions"],
         "orphan_metric_allowed": False, "missing_field_defaulted": False},
        [("Load the section-20 metric list and the platform dictionary",
          "The list holds 32 names in 5 groups with the counts 7 marketing, 7 sales, 6 customer care, 5 customer success and 7 AI system."),
         ("Match every dictionary entry against the list",
          "Each of the 32 names resolves to exactly one entry and every entry declares owner, unit, numerator, denominator, window and exclusion rule."),
         ("Attempt to register a metric that is not in section 20",
          "The registration is refused; the dictionary holds no orphan metric and an additional metric stays a labelled extension that cannot be published as an SRS KPI."),
         ("Attempt to compute a metric whose entry is missing its denominator",
          "Publication is blocked and the gap is reported, instead of defaulting the denominator to the row count of the whole table.")],
        ["All 32 section-20 metric names resolve to exactly one dictionary entry each, with per-group counts 7/7/6/5/7 and no duplicate name.",
         "Every entry declares the fields required to reproduce the value; a missing field blocks publication rather than defaulting to a plausible substitute.",
         "No metric outside section 20 is published as an SRS KPI, and an extension metric is visibly labelled as an extension.",
         "The reverse map is available: each metric names the cases that cover it, so an uncovered metric appears as a reported gap."],
        ["Publishing a metric that has no dictionary entry.",
         "Renaming or merging a section-20 metric to fit an existing entry.",
         "Silently defaulting a missing numerator or denominator."],
        ["Dictionary dump with the 32 entries and all declared fields.",
         "Coverage gap report listing metrics with no covering case (expected to be empty)."],
        ["Delete " + NS + " dictionary snapshot rows after export."],
        _KPI_AUTO,
        prereq=["ASM-002 targets are not locked, so the dictionary carries definitions, units and windows only; no target figure is part of the dictionary."],
        refs=[ANALYTICS, SRS],
    ),
    case(
        "GOV-KPI-NO-DATA-VS-ZERO", "No-data is not zero: an unmeasured window reports NO_DATA with the missing source named",
        KPI_SUITE, "governance", ["SRS-20", "NFR-002"],
        ["kpi:Lead Conversion", "kpi:Campaign Revenue", "kpi:Customer Satisfaction"],
        "baseline", "P1", "critical",
        "A missing source is rendered as 0, so a broken connector reads either as a business collapse or as a quiet week, and nobody investigates the outage because the dashboard looks plausible.",
        [GOV_FX],
        _KPI_PRE + ["kpi_edge.no_data_tenant has null order and lead counters because the connector never delivered, which is a different state from a measured zero.",
                    "A second tenant has a genuine measured zero for the same metric, so the case can prove the two states are distinguishable."],
        {"no_data_tenant": _KP["kpi_edge"]["no_data_tenant"],
         "measured_zero_case": {"tenant": "T1", "leads": 0, "expected_display": "0 with coverage stated"},
         "required_display_fields": ["state", "coverage", "reason", "last_updated"]},
        [("Read the metrics for the tenant whose connector never delivered",
          "Each affected metric displays NO_DATA with the missing source named and the last attempted update time; none of them displays 0."),
         ("Read the same metrics for the tenant with a genuine measured zero",
          "The display shows 0 and states the coverage (which rows were counted) and the window, so 0 is visibly a measurement."),
         ("Check the aggregate rows and the coverage field",
          "The aggregate row records state NO_DATA with a null value and a coverage of 0 rows, rather than a value of 0 with full coverage."),
         ("Attempt to make the dashboard render 0 for the missing tenant",
          "The attempt is refused and the NO_DATA state survives, with the reason preserved for the operator.")],
        ["NO_DATA, measured zero and partial coverage are three distinct states in the stored row and in the display.",
         "A metric with no source row is never rendered as 0, and a rendered 0 always carries its coverage and window.",
         "The missing source is named in the display, so an operator can act without reading the pipeline logs.",
         "The state does not silently change to 0 after a later successful run without a restatement record."],
        ["Coalescing a null aggregate to 0 in the reporting layer.",
         "Hiding the missing source behind a generic empty state.",
         "Backfilling the missing window with a neighbouring period's value."],
        ["Aggregate rows for both tenants showing the distinct states.",
         "Dashboard payload per metric with the state, coverage and reason fields.",
         "Coverage report for the window."],
        ["Delete " + NS + " aggregate rows and cached dashboard payloads after export."],
        _KPI_AUTO,
        refs=[ANALYTICS, SRS],
    ),
    case(
        "GOV-KPI-ZERO-DENOMINATOR", "Zero denominator returns NOT_DEFINED instead of 0% or an infinite rate",
        KPI_SUITE, "governance", ["SRS-20", "NFR-002"],
        ["kpi:Lead Conversion", "kpi:Engagement", "kpi:Cost per Lead"],
        "baseline", "P1", "high",
        "A ratio is computed over an empty denominator and published as 0% or as an unbounded number, so a campaign with no delivery is reported as a total failure or as an infinite success.",
        [GOV_FX],
        _KPI_PRE + ["kpi_edge.zero_denominator supplies zero impressions and zero clicks with three valid leads, so the denominator is genuinely empty while the numerator is not.",
                    "The reporting layer is configured to return a typed undefined state rather than a numeric fallback."],
        {"zero_denominator_dataset": _KP["kpi_edge"]["zero_denominator"],
         "expected": {"Lead Conversion": "NOT_DEFINED", "Engagement": "NOT_DEFINED", "Cost per Lead": "NOT_DEFINED"},
         "forbidden_fallbacks": [0, 0.0, 100.0, "infinity"]},
        [("Compute the three ratios over the empty denominator",
          "Each returns the typed undefined state NOT_DEFINED with the reason (zero denominator), and the numerator value is still reported for context."),
         ("Confirm that no numeric fallback is produced",
          "None of the three metrics reports 0, 0.0, 100% or an unbounded value; the stored row holds a null value and an explicit reason code."),
         ("Add one impression so the denominator becomes 1",
          "The metric is then computed normally, proving the undefined state came from the empty denominator rather than from a broken metric."),
         ("Attempt to divide by zero through the API and the dashboard",
          "Both refuse with the same typed state; no exception text, NaN or Infinity reaches the display.")],
        ["An empty denominator yields NOT_DEFINED and never 0%, 100%, NaN or Infinity on any surface.",
         "The numerator is still visible so the operator sees that work happened while the denominator is empty.",
         "The metric becomes computable as soon as a denominator row exists, so the undefined state is a property of the data and not of the metric code.",
         "No API response, log line or dashboard payload leaks a raw division error."],
        ["Returning 0 for an empty denominator.",
         "Adding 1 to the denominator to avoid division by zero.",
         "Filling the empty denominator with a carried-over value from the previous window."],
        ["Aggregate rows for the three metrics showing the null value and the reason code.",
         "API and dashboard payloads showing the typed undefined state.",
         "Follow-up computation after a denominator row is added."],
        ["Delete " + NS + " aggregate rows and the added denominator test row after export."],
        _KPI_AUTO,
        refs=[ANALYTICS, SRS],
    ),
)

_add(
    case(
        "GOV-KPI-DUPLICATE-EVENTS", "Duplicate and repeat events are counted once by event identity",
        KPI_SUITE, "governance", ["SRS-20", "BR-006", "NFR-003"],
        ["kpi:Duplicate Execution", "kpi:Campaign Revenue", "kpi:Lead-to-Order Conversion"],
        "baseline", "P1", "critical",
        "The same purchase or lead is ingested twice and counted twice, so revenue and conversion double while the duplicate-execution invariant still reads zero.",
        [GOV_FX, EVENTS_FX],
        _KPI_PRE + ["kpi_edge.duplicate_events contains one repeated event_id, a second event_id for the same order, and a retry delivery of the first event.",
                    "The ingestion layer deduplicates on the event identity and the effect_key, not on the raw payload."],
        {"duplicate_dataset": _KP["kpi_edge"]["duplicate_events"],
         "expected": {"distinct_purchase_events": 1, "distinct_orders": 1,
                      "duplicate_suppressed": 2, "orders_counted": 1}},
        [("Ingest the three event deliveries",
          "One purchase event is accepted and two deliveries are suppressed as duplicates or repeats, each with its own reason and correlation id."),
         ("Compute the purchase-denominated metrics over the ingested set",
          "The order is counted once in paid revenue, order count and conversion; the revenue figure does not double."),
         ("Compare the duplicate-execution invariant with the suppression log",
          "The suppressed deliveries are ingestion duplicates, so the invariant stays 0 and the suppression count is reported separately rather than folded into it."),
         ("Replay the first delivery once more after the dedup window",
          "The replay is still recognised through the durable effect_key record and still adds no second order or revenue row.")],
        ["Distinct purchase events equal distinct orders for the window: one order, one revenue row, one conversion numerator count.",
         "Suppressed duplicate deliveries are reported with their reason and never counted as executed actions, so the zero-duplicate invariant stays meaningful.",
         "Revenue, order count and conversion are all derived from the deduplicated set, so no metric double counts the same purchase.",
         "Replays after the dedup window are caught by the durable record rather than by the ephemeral cache."],
        ["Counting both deliveries of the same event_id as purchases.",
         "Treating a duplicate ingestion as a duplicate execution in the safety invariant.",
         "Dropping the second event_id because it shares an order id, which would lose a legitimate second event."],
        ["Suppression log with reasons and correlation ids per delivery.",
         "Recomputed revenue and order count tables showing one row.",
         "Effect-key dedup record for the post-window replay."],
        ["Delete " + NS + " raw event deliveries, aggregate rows and effect-key entries after export."],
        _KPI_AUTO,
        refs=[ANALYTICS, SRS],
    ),
    case(
        "GOV-KPI-REFUND-CANCEL-EXCLUSION", "Refunded and cancelled orders are excluded from revenue, order count and AOV",
        KPI_SUITE, "governance", ["SRS-20", "FR-SAL-002", "NFR-002"],
        ["kpi:Average Order Value", "kpi:Campaign Revenue", "kpi:Lead-to-Order Conversion", "kpi:Cost per Successful Outcome"],
        "baseline", "P2", "critical",
        "Cancelled and refunded orders stay inside the revenue, order count and average order value, so the platform reports money it never kept and the pilots are signed off on phantom revenue.",
        [GOV_FX, ORDERS_FX],
        _KPI_PRE + ["kpi_edge.refund_cancel supplies one paid order, one refunded order and one cancelled order with their amounts.",
                    "The adjustment rule is applied at the row level before aggregation, and the excluded rows are still retrievable for reconciliation."],
        {"refund_cancel_dataset": _KP["kpi_edge"]["refund_cancel"],
         "expected": {"valid_revenue_twd": _KP["kpi_edge"]["refund_cancel"]["expected_valid_revenue_twd"],
                      "valid_orders": _KP["kpi_edge"]["refund_cancel"]["expected_valid_orders"],
                      "excluded_orders": 2, "revenue_including_excluded_twd": 4600.0}},
        [("Aggregate valid revenue and successful order count over the three orders",
          "Valid revenue is 2500 TWD from one order; the refunded and cancelled orders are excluded at row level before aggregation."),
         ("Recompute the average order value and the conversion numerator",
          "AOV is 2500 TWD over one successful order, and the conversion numerator counts one paid order rather than three created orders."),
         ("Apply a refund after the fact to the paid order and re-aggregate",
          "The revenue, order count and AOV figures are restated by the same exclusion rule, and the restatement is recorded instead of rewriting the closed window silently."),
         ("Inspect the reconciliation view",
          "The excluded rows are still listed with their exclusion reason, so the difference between gross and valid revenue is explainable line by line.")],
        ["Refunded and cancelled orders are absent from revenue, successful order count, AOV and cost per successful outcome.",
         "The excluded rows remain retrievable with a reason, so valid revenue reconciles to gross revenue minus the excluded amounts.",
         "The conversion numerator counts paid orders only; a cancelled order cannot be counted as a converted lead afterwards.",
         "A post-window refund produces a recorded restatement rather than a silent rewrite of a closed period."],
        ["Leaving refunded orders in revenue because they were paid at some point.",
         "Rewriting a closed window in place so the earlier published figure cannot be reconstructed.",
         "Excluding a cancelled order from the denominator while leaving its revenue in the numerator."],
        ["Row-level exclusion table with the reason per order.",
         "Recomputed revenue, order count and AOV figures with the excluded ids listed.",
         "Restatement record created after the post-window refund."],
        ["Delete " + NS + " aggregate rows and the synthetic post-window refund record after export."],
        _KPI_AUTO,
        refs=[ANALYTICS, SRS],
    ),
    case(
        "GOV-KPI-CURRENCY-SPLIT", "Mixed currencies are never summed into one figure",
        KPI_SUITE, "governance", ["SRS-20", "NFR-010"],
        ["kpi:Campaign Revenue", "kpi:Average Order Value", "kpi:Cost per Successful Outcome"],
        "baseline", "P2", "critical",
        "TWD and VND rows are added together into a single total, so a mixed-currency report states a number that corresponds to no currency at all and unit economics become meaningless.",
        [GOV_FX],
        _KPI_PRE + ["kpi_edge.currency_split supplies one TWD row and one VND row with a synthetic fixed rate recorded at the event time.",
                    "The reporting currency of the tenant is TWD and any conversion must use the rate fixed when the event occurred."],
        {"currency_rows": _KP["kpi_edge"]["currency_split"]["rows"],
         "synthetic_fixed_rates_to_twd": _KP["kpi_edge"]["currency_split"]["synthetic_fixed_rates_to_twd"],
         "expected_display": _KP["kpi_edge"]["currency_split"]["expected_display"],
         "naive_wrong_total": 9012000.0},
        [("Aggregate the two rows with the default reporting configuration",
          "The report shows one row per currency instead of one combined figure, and the currency is present on every row."),
         ("Enable the conversion view and re-run",
          "The VND row is converted with the fixed rate recorded at the event time and the TWD total is derived only from converted rows, with the rate and the rate timestamp shown."),
         ("Attempt to sum the raw amounts",
          "The attempt is refused: a figure of 9012000 with no currency is rejected, and the conversion path must be used explicitly."),
         ("Compare the two views",
          "Per-currency rows and the converted total reconcile exactly, and the denominator of any ratio is taken from the same currency scope as the numerator.")],
        ["No published metric ever adds amounts of two different currencies; the currency is present on every stored row and every display.",
         "A conversion uses the fixed rate recorded at the event time and states the rate and its timestamp, so the converted total is reproducible.",
         "Ratio metrics such as average order value and cost per successful outcome use a denominator from the same currency scope as the numerator.",
         "The naive cross-currency total is refused on every surface rather than being labelled as an approximation."],
        ["Summing TWD and VND amounts into one figure.",
         "Converting with the current rate instead of the event-time fixed rate.",
         "Computing a ratio across two currency scopes."],
        ["Per-currency aggregate rows with the amounts and currency codes.",
         "Conversion table naming the rate and the event-time timestamp per converted row.",
         "Refusal record for the naive cross-currency sum attempt."],
        ["Delete " + NS + " aggregate, conversion and refusal rows after export."],
        _KPI_AUTO,
        refs=[ANALYTICS, SRS],
    ),
    case(
        "GOV-KPI-ATTRIBUTION-NOT-CAUSATION", "Attribution is reported as correlation, not as proven incremental revenue",
        KPI_SUITE, "governance", ["SRS-20", "MKT-06", "NFR-005"],
        ["kpi:Campaign Revenue", "kpi:Recommendation Conversion", "kpi:Autonomous Completion Rate"],
        "blueprint", "P3", "critical",
        "An attributed revenue figure is presented as revenue the AI created, so the pilot claims causal impact that was never tested and budget is committed on a correlation.",
        [GOV_FX],
        _KPI_PRE + ["kpi_dataset.attribution holds W-shaped weights (30/30/30/10) for a single confirmed order of 1000 TWD, and no controlled experiment exists in this repository.",
                    "The report is required to state that attribution is a model unless a valid controlled comparison exists."],
        {"attribution": _KP["attribution"],
         "expected": {"weight_sum": 1.0, "marketing_first_twd": 300.0, "sales_consult_twd": 300.0,
                      "care_middle_twd": 100.0, "cart_last_twd": 300.0,
                      "causal_claim_allowed": False, "experiment_present": False},
         "claimed_incremental_revenue_twd_if_buggy": 1000.0},
        [("Apply the W-shaped weights to the confirmed order",
          "The 1000 TWD order is split 300/300/100/300 across the four touchpoints and the weights sum to exactly 1.0 with no residual."),
         ("Aggregate attributed revenue per agent for the window",
          "Each agent's attributed share is reported as its weighted portion, and the sum of all shares equals the attributed order value."),
         ("Attempt to publish the attributed figure as incremental revenue created by the AI",
          "Publication is refused while no controlled experiment exists; the report labels the figure as attributed correlation."),
         ("Attempt a variant where one agent alone is credited with the whole order",
          "The single-agent rule applies only when exactly one agent participated; with four touchpoints the 100% claim is rejected.")],
        ["Attribution weights sum to 1.0 per order and the per-agent shares sum back to the attributed order value.",
         "No attributed figure is published or labelled as incremental, causal or AI-created revenue before a valid controlled comparison exists.",
         "A single-agent 100% credit applies only when the journey has one touchpoint; multi-touch journeys keep the declared weight model.",
         "The report states the attribution model, the touchpoints used and the absence of an experiment, so a reader cannot mistake correlation for causation."],
        ["Calling attributed revenue 'AI-generated revenue'.",
         "Crediting the full order to one agent to simplify the report.",
         "Presenting a post-hoc comparison of strong and weak days as a controlled experiment."],
        ["Per-order attribution table with the weights and the touchpoints.",
         "Per-agent attributed revenue report with the model statement.",
         "Refusal record for the causal publication attempt."],
        ["Delete " + NS + " attribution and publication rows after export."],
        _KPI_AUTO,
        prereq=["No controlled experiment exists and the KPI baseline is not locked, so no causal or incremental revenue claim can be made from this dataset."],
        refs=[ANALYTICS, SRS],
    ),
)

_add(
    case(
        "GOV-KPI-ATTRIBUTION-WINDOW", "Attribution windows: late orders become organic and auto-opened messages are excluded",
        KPI_SUITE, "governance", ["SRS-20", "SAL-04", "PILOT-02"],
        ["kpi:Cart Recovery Rate", "kpi:Campaign Revenue", "kpi:Engagement"],
        "blueprint", "P2", "high",
        "An order confirmed after the attribution window is credited to the campaign anyway, so organic revenue is counted as AI revenue and the recovery rate is overstated.",
        [GOV_FX, ORDERS_FX],
        _KPI_PRE + ["The 24 hour cart-recovery window and the 48 hour campaign-click window are the declared windows for this tenant, measured from the qualifying interaction to the confirmed payment.",
                    "kpi_dataset.attribution marks orders confirmed after the window as organic and excludes messages the customer never answered."],
        {"windows_hours": {"cart_recovery": _KP["attribution"]["cart_recovery_window_hours"],
                           "campaign_click": _KP["attribution"]["campaign_click_window_hours"]},
         "orders": [{"order_id": "ORD-W-1", "confirmed_after_hours": 6.0, "expected": "ATTRIBUTED"},
                    {"order_id": "ORD-W-2", "confirmed_after_hours": 30.0, "expected": "ORGANIC"},
                    {"order_id": "ORD-W-3", "confirmed_after_hours": 47.9, "expected": "ATTRIBUTED"},
                    {"order_id": "ORD-W-4", "confirmed_after_hours": 48.1, "expected": "ORGANIC"}],
         "auto_opened_messages": {"count": _KP["attribution"]["no_interaction_messages"],
                                  "customer_replies": 0, "expected": "EXCLUDED_FROM_ENGAGEMENT"},
         "late_arrival": _KP["kpi_edge"]["late_events"],
         "window_boundary": "half-open: an order confirmed exactly at the window edge counts as inside"},
        [("Attribute the four orders using the declared windows",
          "The two orders inside their window are attributed, and ORD-W-2 and ORD-W-4 are classified as organic revenue and excluded from the campaign denominator."),
         ("Inspect the boundary orders",
          "An order confirmed at 48.0 hours is inside the window and one at 48.1 hours is outside, so the boundary is applied consistently and stated."),
         ("Aggregate engagement with the 40 auto-opened messages that received no reply",
          "All 40 are excluded from the engagement numerator and the engagement denominator keeps its declared impression scope."),
         ("Attempt to credit an organic order to the campaign to improve the recovery rate",
          "The attempt is refused and the order stays organic; the recovery rate numerator does not gain the order.")],
        ["Every order outside its declared attribution window is classified as organic and excluded from the attributed numerator and denominator.",
         "The window boundary is applied consistently and the comparison is inclusive of the boundary instant, so no order is both inside and outside.",
         "Auto-opened messages with no customer reply are excluded, so engagement is not manufactured by the platform's own outgoing traffic.",
         "The declared window per scenario is published with the metric, so a reader can reproduce the classification.",
         "An order confirmed after the window end and delivered late is recorded as a late-arrival restatement: the closed window keeps its published figure and the difference is stated, instead of the past being silently rewritten."],
        ["Crediting an out-of-window order to the AI to lift the conversion figure.",
         "Counting an unanswered auto-open as engagement.",
         "Using one window for cart recovery and campaign clicks so the boundary becomes arbitrary."],
        ["Per-order classification table with the hours since the qualifying interaction.",
         "Engagement computation showing the excluded auto-open count.",
         "Window declaration recorded with the metric."],
        ["Delete " + NS + " classification and aggregate rows after export."],
        _KPI_AUTO,
        refs=[ANALYTICS, SRS],
    ),
    case(
        "GOV-KPI-REOPEN-TAKEOVER", "No double counting: a reopened case counts one outcome and a takeover is not AI-resolved",
        KPI_SUITE, "governance", ["SRS-20", "FR-CS-002", "NFR-007"],
        ["kpi:AI Resolution Rate", "kpi:Reopen Rate", "kpi:Human Override Rate"],
        "baseline", "P1", "critical",
        "A reopened case is counted twice and a taken-over session is still credited to the AI, so the automation rate improves exactly as human effort increases.",
        [GOV_FX, CUST_FX],
        _KPI_PRE + ["kpi_edge.reopen_and_takeover describes one reopened case and three taken-over sessions inside the same window.",
                    "The case model keeps a single case identity across a reopen, and a takeover transfers the affected leg's credit to the human."],
        {"reopen_and_takeover": _KP["kpi_edge"]["reopen_and_takeover"],
         "care_counters": {"cases_total": _CARE["cases_total"], "ai_closed": _CARE["ai_closed"],
                           "reopened_within_72h": _CARE["reopened_within_72h"],
                           "human_takeover_sessions": _CARE["human_takeover_sessions"]},
         "expected": {"final_outcome_per_case": 1, "ai_resolved_credit_for_takeover": 0,
                      "ai_resolution_rate": _pct(_CARE["ai_closed"], _CARE["cases_eligible_for_ai"]),
                      "reopen_rate": _pct(_CARE["reopened_within_72h"], _CARE["ai_closed"])}},
        [("Reopen the closed case and close it again with a final outcome",
          "The case keeps one identity, the reopen is recorded once with its delta from the AI closure, and the final outcome replaces the earlier outcome instead of adding a second one."),
         ("Read the AI resolution numerator after the reopen",
          "The case is not counted twice; if a human resolved the reopened case, the AI resolution numerator loses it."),
         ("Take over three sessions and re-read the counters",
          "Those sessions are credited to the human, the AI resolution numerator does not gain them, and the human override counter increases by the number of overridden sessions."),
         ("Attempt to count the reopened case as a new case",
          "The attempt is refused, and the case count plus the reopen flag stay consistent with the case identity.")],
        ["Each case contributes exactly one final outcome, so the case count does not grow when a case is reopened.",
         "A taken-over session is never credited to AI resolution, and the transferred weight is visible on the human side.",
         "The reopen rate uses AI-closed cases as its denominator and counts a reopen only once, within 72 hours of the AI closure.",
         "AI resolution rate and human override rate move in opposite directions when a takeover happens, so the two metrics cannot both improve from the same event."],
        ["Counting a reopened case as a second case to inflate the closure count.",
         "Crediting a taken-over session to the AI because the AI handled the early turns.",
         "Dropping the reopen flag after the second closure so the quality signal disappears."],
        ["Case identity history with the reopen delta and the final outcome.",
         "AI resolution and human override counters before and after the takeover.",
         "Reopen report listing the case once with its flag."],
        ["Delete " + NS + " case history, takeover records and aggregate rows after export."],
        _KPI_AUTO,
        refs=[ANALYTICS, IMPL07, SRS],
    ),
    case(
        "GOV-KPI-SAFETY-INVARIANTS", "AI-SYS-KPI-03 and AI-SYS-KPI-07 must be exactly 0 and are not baseline-dependent",
        KPI_SUITE, "governance", ["SRS-20", "NFR-001", "NFR-003", "BR-008"],
        ["kpi:Policy Violation Rate", "kpi:Duplicate Execution", "kpi:Hallucination/Error Rate",
         "kpi:Failed Execution"],
        "baseline", "P0", "critical",
        "The two zero-tolerance invariants are treated as targets that may be missed while the baseline is pending, so an authority violation or a duplicate send is filed as a metric miss and the release proceeds.",
        [GOV_FX],
        _KPI_PRE + ["policy_violations and duplicate_executions are both 0 in the synthetic dataset, and the invariant is defined as a hard requirement rather than a target.",
                    "A second variant injects one violation row and one duplicate effect so the case proves a non-zero value blocks the release instead of being reported."],
        {"invariants": {"AI-SYS-KPI-03": {"name": "Policy Violation Rate", "required": 0,
                                          "fixture_value": _AI["policy_violations"]},
                        "AI-SYS-KPI-07": {"name": "Duplicate Execution", "required": 0,
                                          "fixture_value": _AI["duplicate_executions"]}},
         "monitoring_metrics": {"AI-SYS-KPI-04": {"name": "Hallucination/Error Rate",
                                                  "fixture_value": _pct(_AI["hallucination_findings"], _AI["answers_audited"]),
                                                  "threshold_kind": "proposed design target pending ASM-002"},
                                "AI-SYS-KPI-06": {"name": "Failed Execution",
                                                  "fixture_value": _pct(_AI["executions_failed"], _AI["executions_total"]),
                                                  "threshold_kind": "proposed design target pending ASM-002"}},
         "injected_violation_variant": {"policy_violations": 1, "duplicate_executions": 1,
                                        "expected": "RELEASE_BLOCKING_ERROR"}},
        [("Read the two invariants from the dataset",
          "Both are reported as exactly 0 and the report states that zero is required, not a target that may be missed."),
         ("Inject one violation row and one duplicate effect and re-evaluate",
          "Both metrics become non-zero and the run reports a release-blocking error; no ASM-002 exemption is applied and no threshold is consulted."),
         ("Compare with the two monitoring metrics",
          "Hallucination/Error Rate and Failed Execution are reported as measured values with their proposed design targets explicitly labelled as unapproved, so they are not mistaken for pass/fail bars."),
         ("Attempt to weaken the invariants via the assumption registry",
          "The attempt is refused: ASM-002 cannot loosen a safety invariant, and an unlocked KPI baseline does not convert the invariant into a measurable target.")],
        ["Policy Violation Rate and Duplicate Execution are exactly 0 in the accepted run, and any non-zero value is a release-blocking error rather than a metric miss.",
         "The two invariants are independent of the ASM-002 baseline: an unlocked baseline cannot relax, weight or defer them.",
         "The monitoring metrics are visibly separated from the invariants and their proposed thresholds are labelled as unapproved design targets.",
         "A blocked violation attempt still counts in the invariant numerator, so a control that fires is not evidence of a clean record."],
        ["Reporting the invariants as targets that may be missed.",
         "Applying an ASM-002 exemption to an authority violation or a duplicate send.",
         "Excluding a violation because execution was blocked before it took effect."],
        ["Invariant evaluation rows for both metrics with the fixture values.",
         "Release-blocking error record from the injected variant with the offending row ids.",
         "Monitoring metric report showing the unapproved threshold labels."],
        ["Delete " + NS + " evaluation rows and the injected variant rows after export."],
        _KPI_AUTO,
        prereq=["ASM-002 is unlocked, which affects targets only: the two zero-tolerance invariants remain hard requirements and must be evaluated regardless of the baseline."],
        refs=[ANALYTICS, IMPL08, SRS],
    ),
    case(
        "GOV-KPI-FAILED-EXECUTION-UNKNOWN", "Failed Execution excludes unknown outcomes and never counts a blind resend as a duplicate",
        KPI_SUITE, "governance", ["SRS-20", "NFR-008", "BR-006", "TC-E2E-008"],
        ["kpi:Failed Execution", "kpi:Duplicate Execution", "kpi:Autonomous Completion Rate"],
        "blueprint", "P1", "high",
        "An unknown outcome after a dropped response is filed as a failure, or a blind resend is hidden as a vendor artifact, so the failure rate and the zero-duplicate invariant are both wrong at the same time.",
        [GOV_FX],
        _KPI_PRE + ["The dataset separates failed executions, unknown outcomes and duplicate executions into three counters that must not be merged.",
                    "A variant injects one unknown outcome and one blind resend whose effect already occurred, so the case can prove the buckets stay distinct."],
        {"counters": {"executions_total": _AI["executions_total"], "executions_failed": _AI["executions_failed"],
                      "policy_violations": _AI["policy_violations"], "duplicate_executions": _AI["duplicate_executions"]},
         "expected": {"failed_execution_rate": _pct(_AI["executions_failed"], _AI["executions_total"]),
                      "unknown_outcome_bucket": "separate counter, excluded from both failure and success",
                      "duplicate_counter_after_blind_resend": 0},
         "injected_variant": {"unknown_outcomes": 1, "blind_resends": 1, "second_effect_created": False,
                              "expected": "UNKNOWN_BUCKET_INCREMENTED_ONCE"}},
        [("Compute Failed Execution over the dataset",
          "The rate is 0.3% from three failed executions out of one thousand, and unknown outcomes are reported in their own counter rather than inside the failure numerator."),
         ("Inject the unknown outcome and the blind resend",
          "The unknown counter increments once, the failure numerator is unchanged, and the blind resend resolves through reconciliation without creating a second external effect."),
         ("Read the duplicate-execution invariant after the blind resend",
          "The invariant stays exactly 0 because no second effect occurred, and the extra attempt is visible as an attempt rather than as a duplicate."),
         ("Attempt to publish the failure threshold as an approved limit",
          "The publication is refused: the threshold remains a proposed design target awaiting the ASM-002 baseline, while the zero-duplicate invariant continues to apply immediately.")],
        ["Failed Execution counts failed or errored executions only; unknown outcomes live in their own bucket and are excluded from both the failure and the success numerators.",
         "The duplicate-execution invariant is unaffected by a retry that produced no second effect, and by a blind resend that was reconciled before dispatch.",
         "A retry that later succeeds does not retroactively remove the earlier failure record.",
         "The failure threshold is labelled as an unapproved design target, while the zero-duplicate invariant is applied immediately without waiting for a baseline."],
        ["Counting an unknown outcome as a failure to make the failure rate look conservative.",
         "Hiding a blind resend so a second effect is never investigated.",
         "Removing an earlier failure record after a successful retry."],
        ["Execution ledger with the three counters and the retry links.",
         "Unknown-outcome and reconciliation records for the injected variant.",
         "Invariant evaluation rows before and after the blind resend."],
        ["Delete " + NS + " execution, unknown-outcome and evaluation rows after export."],
        _KPI_AUTO,
        refs=[ANALYTICS, IMPL08, SRS],
    ),
    case(
        "GOV-KPI-MISSING-COST", "Missing cost rows produce PARTIAL coverage instead of a cheaper cost per outcome",
        KPI_SUITE, "governance", ["SRS-20", "NFR-010", "OBJ-006"],
        ["kpi:Cost per Successful Outcome", "kpi:Campaign Revenue", "kpi:Human Override Rate"],
        "baseline", "P4", "high",
        "Rows with no cost are dropped from the cost numerator, so cost per successful outcome falls whenever a billing feed breaks and the platform looks cheaper exactly when it is unmeasured.",
        [GOV_FX],
        _KPI_PRE + ["kpi_edge.missing_cost marks two rows whose cost is absent because the provider feed did not deliver, which is different from a cost of zero.",
                    "Cost per successful outcome must state its coverage when any contributing row has no cost."],
        {"missing_cost": _KP["kpi_edge"]["missing_cost"],
         "cost_inputs": {"ai_cost_total_twd": _AI["ai_cost_total_twd"], "successful_outcomes": _AI["successful_outcomes"],
                         "session_cost_samples_twd": _AI["session_cost_samples_twd"],
                         "run_cost_samples_twd": _AI["run_cost_samples_twd"],
                         "customer_costs_twd": _AI["customer_costs_twd"]},
         "expected": {"cost_per_successful_outcome": _money(_AI["ai_cost_total_twd"] / _AI["successful_outcomes"]),
                      "coverage_state": "PARTIAL with the missing-source reason",
                      "zero_substitution_allowed": False}},
        [("Compute cost per successful outcome over the full window",
          "The value is 30 TWD and the report states that two contributing rows have no cost, so the figure is marked PARTIAL rather than final."),
         ("Attempt to publish the figure as complete",
          "Publication is refused while a contributing row lacks cost; the missing rows are listed with the provider-feed reason."),
         ("Attempt to treat the missing cost as zero",
          "The substitution is refused, because a zero would silently lower the measured cost per outcome."),
         ("Aggregate cost per run and per customer after the feed recovers",
          "The restated figure includes the previously missing rows, per-customer cost sums to the run totals, and the earlier PARTIAL state is superseded by a recorded restatement.")],
        ["Cost per successful outcome is never published as complete while any contributing row lacks a cost; the coverage state is PARTIAL with the reason.",
         "A missing cost is never replaced by zero, and the recomputation before and after the feed recovery differ only by the recovered amounts.",
         "Per-run and per-customer cost aggregates reconcile to the measured total, with no cost attributed to a customer that did not generate it.",
         "The restatement is recorded with its cause, so the previously published partial figure can still be reconstructed."],
        ["Substituting zero for a missing provider cost.",
         "Dropping the rows without cost from the numerator so the average falls.",
         "Publishing a per-customer cost that cannot be reconciled to the run totals."],
        ["Cost computation with the PARTIAL coverage state and the missing row ids.",
         "Provider usage and billing extract showing which rows are absent.",
         "Restatement record created after the feed recovery."],
        ["Delete " + NS + " cost aggregate rows and invented cost rows after export; the provider feed substitute is restored."],
        _KPI_AUTO,
        prereq=["ASM-002 is unlocked, so the cost figures are measurements with unapproved thresholds; only the coverage and reconciliation rules are asserted here."],
        refs=[ANALYTICS, SRS],
    ),
    case(
        "GOV-KPI-TARGET-NOT-LOCKED", "Without a locked baseline there is no pass/fail KPI verdict, only measurements",
        KPI_SUITE, "governance", ["ASM-002", "SRS-20", "NFR-002"],
        ["kpi:Lead-to-Order Conversion", "kpi:Autonomous Completion Rate",
         "kpi:Cost per Successful Outcome"],
        "baseline", "P1", "critical",
        "A pilot is declared successful because a measured value happens to exceed a target somebody proposed, so the baseline is never bought and the commitment is made on an unapproved number.",
        [GOV_FX],
        _KPI_PRE + ["assumptions.ASM-002.locked is false and no approved baseline or target set exists in the repository.",
                    "The run is required to emit a measurement record and no pass/fail verdict for every KPI."],
        {"assumptions": {"ASM-002": {"locked": False, "owner": "Business"}},
         "evaluations": [{"label": "measurement record", "expected_status": "EXECUTED"},
                         {"label": "target verdict", "expected_status": "BLOCKED_PREREQUISITE"},
                         {"label": "gate sign-off from KPI", "expected_status": "NOT_RUN"}],
         "sample_size": {"orders": _SAL["orders_paid"], "sessions": _AI["sessions_total"]},
         "uncertainty_required": True},
        [("Publish the measurement record for the window",
          "Each metric is reported with its value, its window, its sample size and the uncertainty of the sample; the record is EXECUTED."),
         ("Attempt the target verdict",
          "The verdict is BLOCKED_PREREQUISITE naming ASM-002 and owner Business; no metric is labelled PASS or FAIL against a target."),
         ("Attempt a gate sign-off that cites a KPI value",
          "The sign-off is NOT_RUN; the register records that no approved target exists, so a passing KPI value cannot carry a gate on its own."),
         ("Attempt to declare the pilot successful from a single window",
          "The attempt is refused: a single window without a control group is reported as a measurement, and a missing sample yields an insufficient-sample conclusion rather than a win.")],
        ["Every KPI in this run has a measurement record and no metric carries a PASS or FAIL verdict while ASM-002 is unlocked.",
         "The target verdict and any KPI-based gate sign-off are BLOCKED_PREREQUISITE or NOT_RUN, never PASS.",
         "Each measurement states its sample size and uncertainty, and an insufficient sample produces an explicit insufficient-sample conclusion.",
         "No target figure from a fixture, a proposal or a vendor document is promoted into an approved commitment by this run."],
        ["Awarding a pass because a measured value exceeded an unapproved proposal.",
         "Signing a gate on a KPI value with no locked baseline.",
         "Omitting the sample size so a noisy measurement reads as a result."],
        ["Measurement records with values, windows, sample sizes and uncertainty.",
         "Blocker records for the target verdict and the gate sign-off naming ASM-002 and its owner."],
        ["Delete " + NS + " measurement and blocker rows after export."],
        _KPI_AUTO,
        prereq=["The KPI baseline and targets (ASM-002, owner Business) are not locked, so no pass/fail KPI verdict and no KPI-based gate sign-off is possible; only measurement is admissible."],
        refs=[ANALYTICS, IMPL09, SRS],
    ),
)
