"""Ordered governance testcase section: nfr."""
from __future__ import annotations


# ===========================================================================
# governance/nfr.md — NFR-001..NFR-010 verification (SRS 19, implement/08 5)
# ===========================================================================
_NFR_PRE = [
    "Namespace " + NS + "nfr-<case_id>-<worker_id>; NFR verification runs against the offline gateway with mock SoR and channel boundaries.",
    "Frozen clock " + CLOCK + "; failure, outage and crash injections are scripted at the substituted boundary, never faked inside the assertion.",
]
_NFR_AUTO = ("Core PEP, rules engine, audit writer, idempotency store and worker lease logic run as real code under test; only "
             "ERP/WMS, channel gateways, Redis and the model provider are substituted. Faults are injected at those boundaries "
             "and waits are condition-based on persisted state.")

_add(
    case(
        "GOV-NFR-001", "NFR-001 Least privilege: no tool outside the assigned allowlist can be called",
        NFR_SUITE, "governance", ["NFR-001", "BR-008", "AUTH-3", "TC-E2E-006"],
        ["entity:Agent", "entity:Skill"], "baseline", "P0", "critical",
        "An agent reaches a tool that was never granted, for example a raw database writer or an invoice API, and performs an action outside any authority model.",
        [GOV_FX],
        _NFR_PRE + ["SAL-02 is granted the read and message skills only; the allowlist is resolved server-side per agent."],
        {"granted": ["skill.sales.check_price", "skill.sales.search_product", "skill.sales.send_message"],
         "attempts": [{"tool": "db.write", "payload": {"table": "orders", "row": {"status": "PAID"}}},
                      {"tool": "API-001.InvoiceConnector", "payload": {"order_id": "ORD-A-1", "action": "issue"}},
                      {"tool": "skill.governance.raw_dataset_export", "payload": {"tables": ["customers"]}}]},
        [("Call each of the three ungranted tools through the agent runtime",
          "Every call is refused before dispatch with a typed denial; no adapter is invoked."),
         ("Inspect the refusal records",
          "Each names the tool and the reason (not on allowlist or prohibited), and records the agent identity."),
         ("Call a granted tool for contrast",
          "The granted read succeeds, proving the allowlist does not simply block everything.")],
        ["Zero of the three ungranted tools reach their adapter; the adapters expose call counters that all read 0.",
         "Refusals are typed and audited, not generic 500s.",
         "The granted tool still works, so the control is a boundary and not a blanket outage.",
         "No test exists that passes by circumventing the boundary: the case itself asserts the bypass fails."],
        ["Widening the allowlist at runtime from agent-provided input.",
         "Treating an unknown tool as allowed.",
         "Suppressing the denial so the caller sees success."],
        ["Denial records for all three attempts with tool names and reasons.",
         "Adapter call counters showing zero invocation.",
         "Successful granted-tool call as the contrast evidence."],
        ["Delete " + NS + " attempt rows and namespace keys."],
        _NFR_AUTO,
        refs=[IMPL08, SRS],
    ),
    case(
        "GOV-NFR-001-BYPASS", "NFR-001 bypass attempts: direct adapter calls, argument smuggling and token replay all fail",
        NFR_SUITE, "governance", ["NFR-001", "BR-008", "BR-009", "NFR-006"],
        ["entity:Agent", "entity:Action"], "blueprint", "P0", "critical",
        "The allowlist is enforced only in the agent wrapper, so anything that reaches the adapter directly or smuggles a tool name through arguments evades the control.",
        [GOV_FX, CUST_FX],
        _NFR_PRE + ["Adapter endpoints are reachable only through the gateway allowlist; the raw adapter port is network-isolated in the offline harness."],
        {"attempts": [
             {"label": "direct adapter call", "vector": "DIRECT_HTTP", "target": "mock-adapter://email/send"},
             {"label": "argument smuggling", "vector": "TOOL_ARGS", "payload": {"sku_id": "SKU-OK", "options": {"tool": "db.write"}}},
             {"label": "foreign token replay", "vector": "TOKEN", "token_tenant": "T2", "used_in_tenant": "T1"},
             {"label": "nested skill escalation", "vector": "CHAINED_SKILL", "payload": {"steps": ["skill.sales.check_price", "skill.governance.raw_dataset_export"]}}]},
        [("Attempt the direct adapter call",
          "The call is refused at the gateway because the adapter does not accept unmediated clients."),
         ("Send the smuggling payload and the chained-skill payload",
          "The nested tool name is treated as data; the prohibited step is refused and the permitted step still runs."),
         ("Replay the T2 token inside T1",
          "The replay is refused on tenant or signature grounds; no T2 data is returned."),
         ("Inspect all four outcomes",
          "Four refusals with distinct reasons; adapter effect counters are 0 for every attempt.")],
        ["Every one of the four bypass vectors fails, and each failure has a distinct, auditable reason.",
         "The nested-skill attempt does not abort the harmless preceding step, proving the refusal is scoped.",
         "The replayed token yields zero foreign data in the response.",
         "No failure returns a success-shaped payload."],
        ["Relying on the agent wrapper as the only enforcement point.",
         "Parsing a tool name out of free-form arguments.",
         "Accepting a token whose tenant does not match the session."],
        ["Refusal records for the four vectors.",
         "Response bodies (redacted) showing no foreign data.",
         "Adapter effect counters."],
        ["Delete " + NS + " attempt rows and any cached token material."],
        _NFR_AUTO,
        refs=[IMPL08, SRS],
    ),
    case(
        "GOV-NFR-002", "NFR-002 Auditability: every external-change action has an audit record and an evidence record",
        NFR_SUITE, "governance", ["NFR-002", "BR-010", "SRS-17"],
        ["entity:Evidence", "entity:Action", "stage:EVIDENCE"], "baseline", "P0", "critical",
        "An outbound message or order exists with no audit trail, so disputes, chargebacks and regulatory queries cannot be answered from platform records.",
        [GOV_FX, CONSENT_FX],
        _NFR_PRE + ["Two mutating actions will be exercised: one permitted send and one order creation routed to approval."],
        {"actions": [{"skill": "skill.sales.send_message", "customer_id": "cust-a", "channel": "WEB_APP_CHAT",
                      "effect_key": "sha256:" + "5" * 64},
                     {"skill": "skill.sales.create_order", "customer_id": "cust-a", "sku_id": "SKU-OK",
                      "effect_key": "sha256:" + "6" * 64}]},
        [("Execute the permitted send and let the order action route to approval",
          "The send executes once; the order action is held in awaiting_human."),
         ("Query the audit store for the run",
          "Exactly two audit rows exist, one per action, each with the 18 domain fields populated including trigger, context, skill, tool, decision, authority, action and timestamp."),
         ("Query the evidence store",
          "The executed send has an evidence record with the provider receipt; the approval-held action has no execution evidence yet, which is correct."),
         ("Verify the action-to-audit coverage ratio",
          "Every externally observed effect (one message) maps to exactly one audit row and one evidence record; the ratio is 1:1 with no orphan effect.")],
        ["Audit coverage is 100 percent of externally observed effects: one effect, one audit row, one evidence row.",
         "The audit row for the executed send references the evidence record id and the effect_key.",
         "The approval-held action has an audit row with status denied/pending and no fabricated receipt.",
         "Action counts derived from the adapter log equal action counts derived from the audit store."],
        ["Auditing only successful high-value actions.",
         "Writing a receipt into evidence before the provider confirmed.",
         "Losing the effect_key linkage between audit and evidence."],
        ["Audit rows (18 fields) for both actions, redacted.",
         "Evidence record with the provider receipt for the send.",
         "Adapter log used to reconcile the action count."],
        ["Delete " + NS + " rows after exporting the audit and evidence extract."],
        _NFR_AUTO,
        refs=[IMPL08, SRS],
    ),
    case(
        "GOV-NFR-002-DENIED-AUDITED", "NFR-002: denied and aborted actions are audited with the same rigour as successes",
        NFR_SUITE, "governance", ["NFR-002", "AUTH-5", "BR-008", "TC-E2E-006"],
        ["entity:Evidence", "stage:EVIDENCE"], "baseline", "P0", "critical",
        "Only successes are audited, so a series of denied escalation attempts - the strongest signal of an attack or a misconfiguration - leaves no evidence.",
        [GOV_FX],
        _NFR_PRE,
        {"actions": [
             {"label": "denied prohibited", "skill": "skill.governance.raw_dataset_export"},
             {"label": "denied authority", "agent_id": "MKT-02", "skill": "skill.sales.send_message"},
             {"label": "aborted by operator", "skill": "skill.mkt.dispatch_campaign", "abort": "CANCEL"}]},
        [("Trigger the denied prohibited action and the authority-denied action",
          "Both are refused and produce audit rows with execution_status denied and the decision code that caused the refusal."),
         ("Approve then cancel a prepared campaign so the task is aborted",
          "The abort produces an audit row recording the operator cancellation and the released reservations."),
         ("Reconcile the audit store with the observed effects",
          "Three audit rows exist, one per attempt, and the adapter effect counter remains 0 for all three.")],
        ["Denied and aborted attempts each produce exactly one audit row; auditing is not conditional on success.",
         "Each row records the decision code and the acting authority so the attempt is reconstructable.",
         "Zero external effects accompany the three rows, so nothing was 'audited as success'.",
         "The rows participate in the hash chain like any other record."],
        ["Skipping audit writes for denied requests.",
         "Recording a denied attempt as an error telemetry event only, with no audit row.",
         "Dropping the abort reason."],
        ["Three audit rows with decision codes and statuses.",
         "Adapter effect counter and the abort record with released reservations."],
        ["Delete " + NS + " rows after export; retain the chain verification output."],
        _NFR_AUTO,
        refs=[IMPL08, SRS],
    ),
    case(
        "GOV-NFR-002-CHAIN", "NFR-002 tamper detection: modifying a historical audit row breaks the tenant chain",
        NFR_SUITE, "governance", ["NFR-002", "SRS-17", "NFR-006"],
        ["entity:Evidence", "stage:EVIDENCE"], "blueprint", "P0", "critical",
        "Audit rows can be edited or deleted without detection, so the audit trail cannot be trusted in a dispute or an investigation.",
        [GOV_FX],
        _NFR_PRE + ["Five audit rows exist for the tenant with a genesis row whose prev_hash is 64 zeros."],
        {"chain_checks": [
             {"label": "pristine chain", "mutation": None, "expected": "VALID"},
             {"label": "payload edited in row 3", "mutation": "UPDATE payload", "expected": "INVALID_AT_ROW_3"},
             {"label": "row 2 deleted", "mutation": "DELETE row 2", "expected": "INVALID_AT_ROW_2"},
             {"label": "row reordered", "mutation": "SWAP", "expected": "INVALID"},
             {"label": "tenant changed on row 4", "mutation": "CHANGE_TENANT", "expected": "INVALID"}]},
        [("Verify the pristine chain",
          "Verification reports VALID and every row prev_hash equals the previous row chain_hash."),
         ("Edit the payload of row 3 and re-verify",
          "Verification fails and reports the first invalid row index as 3."),
         ("Delete row 2 and re-verify on a restored copy",
          "Verification fails at the deletion point and names row 2."),
         ("Swap two rows and change a tenant on a copy, then verify",
          "Both mutate the chain so verification fails; the tenant-change case is rejected explicitly rather than silently passing.")],
        ["The verifier recomputes SHA-256 over canonical JSON from the 18 domain fields; it does not trust a stored valid flag.",
         "Tampering anywhere invalidates the rest of the chain, and the first invalid row is reported precisely.",
         "Chain partitioning is per tenant: a sequence whose tenant changes is rejected.",
         "Any non-zero exit from verification is a release blocker, not a warning."],
        ["Endorsing a record by trusting a boolean column.",
         "Globally chaining across tenants so one tenant's write breaks another's verification.",
         "Repairing the chain automatically (re-signing) after tampering instead of reporting it."],
        ["Chain verification reports for the five scenarios with the failing row index.",
         "Row hashes before and after each mutation, exported from the tampered copies only."],
        ["Discard the tampered copies; the pristine chain for the namespace is left intact and exported as evidence."],
        "Real chaining writer and verifier under test, including the canonical JSON serialization, so a mismatch between writer and verifier surfaces as a failure rather than a silent pass.",
        refs=[IMPL08, SRS],
    ),
    case(
        "GOV-NFR-002-AUDIT-OUTAGE", "NFR-002 fail-closed: an unavailable audit store blocks the mutation instead of dropping the record",
        NFR_SUITE, "governance", ["NFR-002", "NFR-008", "BR-010"],
        ["entity:Evidence", "stage:EXECUTION"], "extension", "P0", "critical",
        "When the audit store is down the system keeps trading and simply loses the audit rows, so external effects exist that the platform cannot account for.",
        [GOV_FX],
        _NFR_PRE + ["The audit writer is scripted to fail with a connection error for the duration of the outage window."],
        {"script": [{"phase": "audit_available", "action": "send", "expected": "SUCCESS"},
                    {"phase": "audit_down", "action": "send", "expected": "BLOCKED_FAIL_CLOSED"},
                    {"phase": "audit_restored", "action": "send", "expected": "SUCCESS"}]},
        [("Send while the audit store is available",
          "The message is delivered once and the audit row is committed."),
         ("Take the audit store down and attempt a second send",
          "The send is blocked before dispatch with a fail-closed error naming the audit dependency; the adapter counter does not advance."),
         ("Inspect the interim state and then restore the audit store",
          "No effect exists without an audit row; after restoration a retry with the same effect_key delivers once and writes the audit row."),
         ("Reconcile adapter effects against audit rows",
          "Effects and audit rows match exactly (2 effects, 2 rows) with no orphan external action.")],
        ["While auditing is unavailable, zero external effects occur - the mutation is blocked rather than unlogged.",
         "The block is explicit and typed, not a silent drop of the audit write.",
         "After restoration the retry is idempotent: exactly one new effect for the retried action.",
         "Post-run reconciliation shows a 1:1 mapping between external effects and audit rows."],
        ["Buffering audit writes in memory and losing them on failure.",
         "Proceeding with the mutation and logging a warning.",
         "Treating the retry as a duplicate and refusing to deliver anything at all."],
        ["Adapter counter log across the three phases.",
         "Fail-closed error record naming the audit dependency.",
         "Reconciliation table of effects versus audit rows."],
        ["Delete " + NS + " rows after export and restore the audit writer script."],
        _NFR_AUTO + " The outage is injected at the audit client boundary, so the platform's real fail-closed decision is what is measured.",
        refs=[IMPL08, SRS],
    ),
    case(
        "GOV-NFR-003", "NFR-003 Idempotency: replay after cache expiry still yields one external transaction",
        NFR_SUITE, "governance", ["NFR-003", "BR-005", "BR-006", "TC-E2E-005"],
        ["entity:Execution", "stage:EXECUTION"], "baseline", "P0", "critical",
        "Idempotency lives only in a cache with a TTL, so a replay after expiry creates a second order or a second message.",
        [GOV_FX, CONSENT_FX],
        _NFR_PRE + ["The ephemeral idempotency cache TTL is set below the durable store retention so the replay crosses the cache boundary."],
        {"action": {"customer_id": "cust-a", "channel": "WEB_APP_CHAT", "template": "order_shipped",
                    "effect_key": "sha256:" + "7" * 64},
         "timeline": [{"t": 0, "event": "first attempt", "expected": "SUCCESS_ONE_EFFECT"},
                      {"t": 60, "event": "replay while cache warm", "expected": "CACHED_RECEIPT_NO_EFFECT"},
                      {"t": 4000, "event": "replay after cache TTL (durable store only)", "expected": "DEDUPED_NO_EFFECT"},
                      {"t": 4001, "event": "same key, different body", "expected": "409_IDEMPOTENCY_CONFLICT"}]},
        [("Execute the action once and confirm a single effect",
          "One adapter call and one execution receipt keyed by the effect_key."),
         ("Replay the identical request while the cache is warm",
          "The cached receipt is returned; the adapter counter does not advance."),
         ("Advance the injected clock past the cache TTL and replay again",
          "The durable execution record still dedupes the request: no second effect, and the original receipt is returned."),
         ("Replay with the same key but a mutated body",
          "HTTP 409 IDEMPOTENCY_CONFLICT, terminal, with no retry and no effect.")],
        ["Across four attempts the adapter effect count is exactly 1.",
         "Deduplication survives the loss of the ephemeral cache: the durable record is the backstop.",
         "A mutated body with the same key is a terminal conflict, not a silent overwrite.",
         "Each replay response identifies the original execution so callers can proceed without resending."],
        ["Relying solely on a TTL cache for idempotency.",
         "Treating the mutated-body replay as a new action and executing it.",
         "Retrying the conflict automatically."],
        ["Adapter counter log across the timeline.",
         "Execution receipts and the conflict response body.",
         "Cache and durable store lookups recorded per replay."],
        ["Delete " + NS + " execution rows and cache keys; the single simulated send is reported as non-recallable."],
        _NFR_AUTO + " Clock advancement is injected; no case sleeps for the TTL.",
        refs=[IMPL08, SRS],
    ),
    case(
        "GOV-NFR-003-STORE-OUTAGE", "NFR-003 fail-closed: an unavailable idempotency store blocks the mutation rather than risking a duplicate",
        NFR_SUITE, "governance", ["NFR-003", "NFR-008", "BR-006"],
        ["entity:Execution", "stage:EXECUTION"], "extension", "P0", "critical",
        "With the dedup store down the platform cannot tell a retry from a new action, so it either double-sends or refuses all legitimate traffic.",
        [GOV_FX],
        _NFR_PRE + ["The idempotency store is scripted to be unavailable during the middle phase."],
        {"action": {"customer_id": "cust-a", "channel": "EMAIL", "template": "order_shipped",
                    "effect_key": "sha256:" + "8" * 64},
         "phases": [{"store": "up", "expected": "ONE_EFFECT"}, {"store": "down", "expected": "BLOCKED_FAIL_CLOSED"},
                    {"store": "up_again", "replay": True, "expected": "NO_SECOND_EFFECT"}]},
        [("Dispatch with the store available",
          "Exactly one effect and one receipt."),
         ("Take the store down and dispatch a new action",
          "The dispatch is blocked with a typed fail-closed error; the adapter counter does not advance, so no unkeyed action escapes."),
         ("Restore the store and replay the original request",
          "The durable dedup record blocks a second effect and returns the original receipt."),
         ("Reconcile effects and receipts",
          "One effect, one receipt, no orphan delivery.")],
        ["An unavailable dedup store blocks mutating external actions instead of degrading to no protection.",
         "The block is scoped to mutating actions: read-only skills still serve during the outage.",
         "After restoration the replay is deduped by the durable record, not re-executed.",
         "Exactly one external effect exists at the end of the timeline."],
        ["Failing open so retries can proceed while dedup is down.",
         "Blocking reads as well and turning a dedup outage into a total outage.",
         "Discarding the pending action silently so the customer never receives anything and nobody knows."],
        ["Phase-by-phase adapter counter log.",
         "Fail-closed error record and the read-path success during the outage.",
         "Receipt comparison across the replay."],
        ["Delete " + NS + " rows and restore the store script."],
        _NFR_AUTO,
        refs=[IMPL08, SRS],
    ),
    case(
        "GOV-NFR-004", "NFR-004 Recovery: a worker killed mid-workflow resumes from checkpoint without duplicating",
        NFR_SUITE, "governance", ["NFR-004", "NFR-003", "TC-E2E-005", "BR-006"],
        ["entity:Execution", "stage:EXECUTION"], "baseline", "P0", "critical",
        "A crashed worker either loses the in-flight action so the customer never receives it, or restarts from the beginning and duplicates the already-sent message or order.",
        [GOV_FX, CATALOG_FX],
        _NFR_PRE + ["A real worker process is started against the offline gateway so it can be terminated and restarted."],
        {"workflow": {"task_id": "task-nfr-4", "steps": ["qualify", "price", "compose", "send", "record"]},
         "kill_point": "after step 3 (compose) and before step 4 (send)",
         "effect_key": "sha256:" + "9" * 64},
        [("Start the workflow and let it reach the composed step",
          "Steps 1 to 3 are checkpointed with their outputs persisted; no outbound effect exists yet."),
         ("Terminate the worker process (SIGKILL) and confirm the lease expires or is reclaimed",
          "The run is reclaimed by another worker after lease expiry; the interrupted run is marked interrupted rather than completed."),
         ("Restart the worker and let recovery proceed",
          "Recovery resumes at the send step using the checkpointed composition; the adapter receives exactly one send."),
         ("Seed a second failure: kill the worker after the send but before the record step",
          "On restart the persisted receipt for the effect_key prevents a second send, and the record step completes.")],
        ["Work resumes from the last checkpoint instead of restarting the whole workflow.",
         "Exactly one external effect exists in both kill scenarios.",
         "The interrupted run is never reported as completed before its final step succeeded.",
         "Recovery is driven by persisted state, so a second worker can complete the run."],
        ["Re-executing steps that already produced an external effect.",
         "Marking the run completed when the worker died mid-step.",
         "Keeping checkpoints only in the dead process memory."],
        ["Worker logs around each kill with the lease transitions.",
         "Checkpoint records and the single adapter send receipt.",
         "Run state history including the interrupted state."],
        ["Stop any worker started by the case, delete " + NS + " execution and checkpoint rows, and confirm no lease remains."],
        "Real worker process and durable checkpoint/lease logic under test: the crash is an actual process termination, not a simulated exception, so in-memory-only implementations fail.",
        prereq=["Requires the runnable offline harness (worker process + Postgres/Redis substitutes). Without it the case is SKIP_UNIMPLEMENTED, never PASS."],
        refs=[IMPL08, IMPL09],
    ),
    case(
        "GOV-NFR-004-TIMEOUT", "NFR-004 timeout discipline: a hung upstream is abandoned at the deadline and recorded honestly",
        NFR_SUITE, "governance", ["NFR-004", "NFR-008", "TC-E2E-008"],
        ["entity:Execution", "stage:ACTION"], "blueprint", "P0", "high",
        "A hung connector call blocks a worker forever, so queues back up and the customer waits indefinitely with no honest status anywhere.",
        [GOV_FX, ORDERS_FX],
        _NFR_PRE + ["The mock ERP is scripted to accept the connection and never respond."],
        {"call": {"skill": "skill.care.lookup_order", "order_id": "ORD-A-1", "timeout_ms": 2000},
         "clock_advance": "injected to 2001 ms"},
        [("Issue the lookup against the hanging upstream",
          "The call is abandoned at the configured deadline (2001 ms on the injected clock) rather than waiting indefinitely."),
         ("Inspect the failure record",
          "The record shows a timeout error preserving the upstream identity and the elapsed time; it is not marked success."),
         ("Check the worker and queue state",
          "The worker is released and the task moves to a retry or failure state; no worker remains blocked on the call."),
         ("Retry after the upstream recovers",
          "The retry returns ORD-A-1 details and the final record reconciles to one honest successful attempt.")],
        ["The deadline is enforced deterministically using the injected clock: the call does not hang past it.",
         "Timed-out attempts are recorded as failures with elapsed time, never as successes.",
         "The worker is not leaked: the pool returns to its pre-call capacity.",
         "After recovery, exactly one successful attempt and one failure attempt are recorded for the task."],
        ["No timeout at all so the worker hangs.",
         "Reporting a timeout as a success because the connection was accepted.",
         "Leaking the worker slot on timeout."],
        ["Timeout error record with elapsed time and upstream identity.",
         "Worker capacity before and after the call.",
         "Recovery attempt record and the final order payload."],
        ["Restore the mock ERP script and delete " + NS + " task rows."],
        _NFR_AUTO + " Deadline enforcement uses the injected clock so the case cannot pass by finishing early in real time.",
        refs=[IMPL08, SRS],
    ),
    case(
        "GOV-NFR-005", "NFR-005 Explainability: qualification decisions persist reason plus evidence",
        NFR_SUITE, "governance", ["NFR-005", "FR-SAL-001", "NFR-002"],
        ["entity:Decision", "memory:Customer Context", "stage:DECISION"], "baseline", "P0", "critical",
        "A qualification score or routing decision cannot be explained afterwards, so neither the sales team nor an auditor can justify why a customer was treated a certain way.",
        [GOV_FX, CUST_FX, ORDERS_FX],
        _NFR_PRE,
        {"decision": {"skill": "skill.sales.recommend_product", "customer_id": "cust-a", "sku_id": "SKU-OK",
                      "score": 0.72, "expected_reason": "repeat purchase cycle reached",
                      "expected_evidence": ["ORD-A-1"]}},
        [("Run the qualification and recommendation decision for cust-a",
          "A decision record is produced with a numeric score and a status."),
         ("Read the decision record",
          "The record contains a human-readable reason, at least one evidence reference, the inputs used and the agent identity."),
         ("Resolve the evidence references",
          "Each reference resolves to a real record (for example ORD-A-1) and its timestamp precedes the decision timestamp."),
         ("Inspect the audit row for the same run",
          "The audit row decision field carries the reasoning summary and confidence consistent with the decision record.")],
        ["Every persisted decision has a non-empty reason and at least one resolvable evidence reference.",
         "Evidence timestamps precede the decision, so the reason cannot cite the future.",
         "The score in the decision record matches the score in the audit row; the two surfaces do not disagree.",
         "The decision is reproducible from its recorded inputs and rule version."],
        ["Storing a reason string that is the model's own prose with no evidence reference.",
         "Citing an evidence id that does not resolve.",
         "Recording different scores on the decision and audit surfaces."],
        ["Decision record and audit row for the run.",
         "Resolved evidence records with timestamps.",
         "Rule version and input snapshot used for reproducibility."],
        ["Delete " + NS + " decision rows after export; customer context cache entries are cleared."],
        _NFR_AUTO,
        refs=[IMPL08, SRS],
    ),
    case(
        "GOV-NFR-005-ROUTING", "NFR-005: routing and discount decisions also carry reason plus evidence",
        NFR_SUITE, "governance", ["NFR-005", "FR-ORC-001", "BR-002"],
        ["entity:Decision", "stage:DECISION"], "blueprint", "P1", "high",
        "Only qualification is explained, while routing and pricing decisions remain opaque, so nobody can tell why a discount was granted or why a case went to a particular agent.",
        [GOV_FX, CATALOG_FX],
        _NFR_PRE,
        {"decisions": [
             {"kind": "ROUTING", "input": "customer asks about a delayed parcel and stock availability", "expected_fields": ["reason", "evidence"]},
             {"kind": "FLOOR_POLICY", "input": "discount request 0.15 on SKU-OK", "expected_fields": ["reason", "evidence", "floor_value"]}]},
        [("Trigger an ambiguous routing decision",
          "The routing record names the selected agent and skill plus the matched signals, with a reason and evidence references."),
         ("Trigger a floor-policy decision on a discounted quote",
          "The record stores the computed floor, the offered price, the policy inputs used and the verdict."),
         ("Read both decision records and their audit rows",
          "Both carry non-empty reason and evidence fields and agree with the audit row on the verdict.")],
        ["Routing decisions record why the chosen agent and skill were selected, not only which ones.",
         "Floor-policy decisions record the floor value and the policy inputs, so the verdict can be re-derived.",
         "Both decide records agree with their audit rows.",
         "Evidence references resolve, and no decision cites an absent record."],
        ["Recording the verdict without the reasoning.",
         "Storing only a code such as DENY without the inputs used.",
         "Diverging reason text between the decision record and the audit row."],
        ["Both decision records with reason and evidence fields.",
         "Audit rows for the same runs.",
         "Floor computation trace for the discounted quote."],
        ["Delete " + NS + " decision rows after export."],
        _NFR_AUTO,
        refs=[IMPL08, SRS],
    ),
    case(
        "GOV-NFR-007", "NFR-007 Human override: PAUSE and CANCEL both stop an in-flight workflow",
        NFR_SUITE, "governance", ["NFR-007", "SCR-003", "AUTH-4"],
        ["entity:Approval", "stage:APPROVAL"], "baseline", "P0", "critical",
        "Operators cannot stop a live workflow, so a wrong campaign keeps sending while everyone watches and no control exists between approval and completion.",
        [GOV_FX],
        _NFR_PRE + ["Two prepared campaigns are queued in awaiting_human with reservations held."],
        {"pause_case": {"approval_id": "APV-CAMP-15", "decision": "PAUSE"},
         "cancel_case": {"approval_id": "APV-REFUND-450", "decision": "CANCEL"}},
        [("Pause the first workflow",
          "Status becomes PAUSED and the workflow timer freezes; no send occurs and the task can still be resumed."),
         ("Cancel the second workflow",
          "Status becomes CANCELLED, the run is aborted and its reservations are released."),
         ("Advance the clock and confirm both workflows do not progress",
          "Neither paused nor cancelled workflow produces an outbound effect after the deadline passes."),
         ("Resume the paused workflow and confirm control is restored",
          "The paused workflow can be resumed and then executes exactly once, showing pause is reversible and cancel is terminal.")],
        ["Both override actions stop outbound effects: adapter counter is 0 for both while controlled.",
         "Pause is reversible and cancel is terminal, and the two are distinguishable in the persisted state.",
         "Cancellation releases reservations while pause holds them, so the resource position is predictable.",
         "Both overrides are audited with the operator identity."],
        ["Implementing pause as a UI-only freeze so the backend keeps working.",
         "Making cancel reversible so a cancelled run can still be revived.",
         "Releasing reservations on pause and then executing on resume."],
        ["State snapshots for both workflows at each phase.",
         "Adapter counter log and reservation ledger snapshots.",
         "Override audit rows with operator identities."],
        ["Delete " + NS + " approval rows after export and restore the reservation ledger."],
        _NFR_AUTO,
        refs=[IMPL07, IMPL08],
    ),
    case(
        "GOV-NFR-007-TAKEOVER", "NFR-007 takeover: the human mutex blocks the agent in every workflow state",
        NFR_SUITE, "governance", ["NFR-007", "SCR-005", "NFR-006"],
        ["entity:Conversation", "stage:ACTION"], "baseline", "P0", "critical",
        "Takeover works in the chat screen but a background campaign or a cart-recovery workflow keeps messaging the same customer, so the human's answer is contradicted by the platform.",
        [GOV_FX],
        _NFR_PRE + ["Conversation conv-nfr-7 has a cart-recovery reminder scheduled to fire after the takeover."],
        {"takeover": {"operator_id": "OP-SUPERVISOR-T1", "conversation_id": "conv-nfr-7"},
         "background_task": {"kind": "cart_recovery_reminder", "customer_id": "cust-a", "fire_at": "after takeover"}},
        [("Acquire the takeover lease for the customer conversation",
          "Status becomes HUMAN_TAKEOVER and the mutex key exists for the conversation."),
         ("Let the scheduled background reminder fire",
          "The reminder is blocked by the mutex with a 409 and no message is delivered to the customer."),
         ("Send an operator reply and then resume",
          "The operator reply is delivered once; after resume the next agent action is permitted again.")],
        ["The mutex suppresses every agent-originated send for the conversation, including background workflows - not just interactive replies.",
         "Adapter counter shows one operator message and zero agent messages during the takeover.",
         "Resume restores agent messaging without sending an accumulated backlog of blocked reminders.",
         "The blocked reminder is recorded with the mutex reason rather than being silently dropped."],
        ["Applying the takeover only to the interactive reply path.",
         "Delivering the blocked reminders in a burst immediately after resume.",
         "Treating resume as a new authority grant."],
        ["Mutex key lifecycle and conversation status history.",
         "Adapter message log with sender attribution and counts.",
         "Blocked reminder records with the 409 reason."],
        ["Resume if needed and delete " + NS + " conversation and reminder rows."],
        _NFR_AUTO,
        refs=[IMPL07, IMPL08],
    ),
    case(
        "GOV-NFR-008", "NFR-008 Fail closed: unverifiable price, stock, authority or consent halts execution",
        NFR_SUITE, "governance", ["NFR-008", "BR-003", "BR-004", "BR-008", "NFR-001"],
        ["entity:Price", "entity:Inventory", "entity:Consent"], "baseline", "P0", "critical",
        "The system guesses when verification is impossible, quoting a price it cannot confirm or claiming stock it never checked, and the customer pays for that guess.",
        [GOV_FX, CATALOG_FX, CONSENT_FX],
        _NFR_PRE + ["SKU-NOPRICE has a null list price; the inventory connector is made unreachable; a consent lookup is made to return an unknown state."],
        {"probes": [
             {"label": "unverifiable price", "input": {"sku_id": "SKU-NOPRICE"}, "expected": "HALT_PRICE_UNVERIFIED"},
             {"label": "unreachable inventory", "input": {"sku_id": "SKU-OK"}, "expected": "HALT_STOCK_UNVERIFIED"},
             {"label": "indeterminate consent", "input": {"customer_id": "cust-a", "channel": "EMAIL"}, "expected": "HALT_CONSENT_UNVERIFIED"},
             {"label": "unknown authority", "input": {"skill": "skill.sales.experimental_bundle"}, "expected": "HALT_AUTHORITY_UNVERIFIED"}]},
        [("Trigger each of the four unverifiable conditions in isolation",
          "Each halts before any external dispatch, with a typed reason distinguishing the four causes."),
         ("Confirm no customer-facing assertion was produced",
          "No price, stock or availability claim reaches the channel; the adapter counters remain 0."),
         ("Confirm each halt routes to a human or terminates cleanly",
          "Each halt produces a durable state (human queue item or terminal failure) rather than an error thrown into the void."),
         ("Confirm unrelated healthy paths still work",
          "A price read for SKU-OK and a transactional send for a verified consent still succeed, so fail-closed is scoped.")],
        ["All four unverifiable conditions halt execution; none produces a guessed value.",
         "Each halt carries a distinct typed reason so the cause is actionable.",
         "Fail-closed is scoped: healthy operations in the same tenant continue to work.",
         "Zero customer-facing assertions and zero adapter calls during the four halts."],
        ["Substituting a default price or a cached stock value.",
         "Treating an indeterminate consent as granted.",
         "Halting the entire tenant because one dependency is unverifiable."],
        ["Typed halt records for all four probes.",
         "Adapter counters and the contrast evidence for the healthy paths.",
         "Durable queue or terminal states created by each halt."],
        ["Delete " + NS + " rows and restore the mock connector scripts."],
        _NFR_AUTO,
        refs=[IMPL08, SRS],
    ),
    case(
        "GOV-NFR-008-UNKNOWN", "NFR-008 unknown outcome: no blind resend, reconciliation is mandatory",
        NFR_SUITE, "governance", ["NFR-008", "NFR-003", "TC-E2E-008", "BR-006"],
        ["entity:Execution", "stage:EXECUTION"], "extension", "P0", "critical",
        "A timeout with an unknown external outcome triggers an immediate resend, so the customer receives two orders or two messages and finance sees one of them.",
        [GOV_FX],
        _NFR_PRE + ["The mock adapter is scripted to accept the request, drop the response, and record that the effect actually happened."],
        {"action": {"effect_key": "sha256:" + "a1" * 32, "channel": "EMAIL", "template": "order_shipped"},
         "adapter_script": [{"attempt": 1, "http": "CONNECTION_DROPPED_AFTER_ACCEPT", "actual_effect": "OCCURRED"},
                            {"attempt": 2, "provider_state": "RECEIPT_AVAILABLE", "expected": "NO_NEW_EFFECT"}]},
        [("Dispatch the action and observe the dropped response",
          "The execution is recorded as unknown or failed with the transport error preserved; the caller is not told it succeeded."),
         ("Attempt an immediate blind retry",
          "The retry is gated on reconciliation: the platform queries the provider receipt for the effect_key before sending anything."),
         ("Complete reconciliation with the provider receipt",
          "The provider confirms the effect occurred; the execution resolves to success with exactly one external effect."),
         ("Reconcile the totals",
          "One effect, one receipt, two attempts; no second message is created.")],
        ["An unknown outcome never results in a second external effect: exactly one effect across both attempts.",
         "The interim record does not claim success before reconciliation completes.",
         "The transport error is preserved so the incident is diagnosable.",
         "Reconciliation resolves the execution to a terminal state with a receipt reference."],
        ["Resending immediately without checking the provider.",
         "Declaring failure and giving up, leaving the customer with no confirmation either way.",
         "Counting the unknown attempt as a duplicate execution in the KPI."],
        ["Both attempt records with transport errors and the reconciliation result.",
         "Provider receipt for the single effect.",
         "Final execution state and reconciliation log."],
        ["Delete " + NS + " execution rows; the single simulated send is reported as non-recallable."],
        _NFR_AUTO,
        refs=[IMPL08, IMPL09],
    ),
    case(
        "GOV-NFR-009", "NFR-009 Performance: turn latency is recorded per run with no fabricated SLA",
        NFR_SUITE, "governance", ["NFR-009", "SRS-17", "NFR-002", "ASM-002"],
        ["stage:EVIDENCE"], "baseline", "P0", "high",
        "Latency numbers on dashboards are estimates or are pre-filled with target values, so a performance regression is invisible and an SLA is claimed that was never measured.",
        [GOV_FX],
        _NFR_PRE + ["No official SLA exists: NFR-009 states the SLA is locked only after benchmark, and ASM-002 KPI targets are unapproved."],
        {"turn": {"conversation_id": "conv-nfr-9", "customer_id": "cust-a", "injected_work_ms": 850},
         "expected": {"latency_ms_min": 850, "latency_ms_source": "measured_monotonic_clock", "sla_asserted": False}},
        [("Run one complete turn with a known injected workload duration",
          "The run record contains latency_ms at least 850 and the audit row field 16 is populated."),
         ("Inspect where the latency value comes from",
          "The value is measured between real start and end timestamps using the monotonic clock, not copied from a target or a constant."),
         ("Compare the displayed dashboard value with the stored run value",
          "They agree; the dashboard does not substitute a target or a rounded placeholder."),
         ("Attempt to assert an SLA from the measurement",
          "No SLA assertion is possible because no benchmark has been run; the case records the measurement as NOT_RUN for SLA conformance rather than PASS.")],
        ["Latency is recorded per run from measured timestamps and the recorded value is at least the injected workload duration.",
         "The value is never a constant, a target or a default: two runs with different injected durations produce different values.",
         "No SLA or percentile target is asserted as a pass bar; the absence of a benchmark is reported explicitly.",
         "Dashboard and stored values agree exactly."],
        ["Hardcoding a target latency as the measurement.",
         "Recording zero when the timer cannot be read.",
         "Claiming SLA compliance from a single synthetic measurement."],
        ["Run record with latency_ms, plus the audit row field 16.",
         "Measurement source trace showing the timestamp pair used.",
         "Dashboard payload for comparison."],
        ["Delete " + NS + " run rows after export."],
        _NFR_AUTO,
        prereq=["The formal latency SLA does not exist (locked only after the NFR-009 benchmark and ASM-002 baseline); this case must not be reported as SLA acceptance."],
        refs=[IMPL08, IMPL09],
    ),
    case(
        "GOV-NFR-009-BENCHMARK", "NFR-009 benchmark harness: percentiles come from a real measurement, or the gate is NOT_RUN",
        NFR_SUITE, "governance", ["NFR-009", "SRS-24", "SRS-27", "ASM-002"],
        ["stage:EVIDENCE", "stage:OUTCOME"], "extension", "P1", "high",
        "A benchmark number is quoted in a gate sign-off or an investor statement although no harness ever ran, so the platform commits to a latency it cannot hold.",
        [GOV_FX],
        _NFR_PRE + ["The service under measurement is the offline gateway with mocked SoR; the harness records raw samples."],
        {"benchmark": {"samples": 200, "workload": "conversation turn with mocked SoR",
                       "percentiles": ["p50", "p95"],
                       "raw_samples_required": True,
                       "sla_claim_allowed": False},
         "no_runtime_variant": {"harness_available": False, "expected_status": "NOT_RUN"}},
        [("Run the harness against the offline gateway and collect raw samples",
          "200 raw samples are stored with their timestamps; p50 and p95 are derived from the samples rather than supplied as inputs."),
         ("Recompute the percentiles independently from the raw samples",
          "The recomputed p50 and p95 match the reported values within the documented rounding rule."),
         ("Attempt the variant where the harness cannot run",
          "The result is reported as NOT_RUN with the reason, never as PASS and never with a substituted number."),
         ("Attempt to publish an SLA from the mock-environment benchmark",
          "Publication is blocked: a mocked-boundary benchmark cannot set an official SLA, and the report is labelled as a design-target measurement.")],
        ["Reported percentiles are reproducible from the stored raw samples; recomputation matches.",
         "With no harness, the status is NOT_RUN - never PASS and never a placeholder figure.",
         "The benchmark record states that vendor boundaries were mocked, so it cannot be quoted as production performance.",
         "No percentile target appears as a pass/fail criterion; the run reports measurements only."],
        ["Supplying percentile values as harness configuration.",
         "Filling a missing benchmark with a design target.",
         "Labelling a mocked-environment measurement as an SLA.",
         "Dropping the slowest samples so the percentile looks better."],
        ["Raw sample file and the derived percentile table.",
         "Recomputation output for both percentiles.",
         "NOT_RUN record for the harness-unavailable variant with its reason."],
        ["Delete " + NS + " benchmark artifacts after exporting the report; no production data is involved."],
        _NFR_AUTO + " The harness measures real code paths with substituted vendor boundaries; the raw-sample recomputation is the oracle.",
        prereq=["An official SLA cannot be established here: the NFR-009 benchmark against real infrastructure and the ASM-002 baseline are outstanding, so any SLA statement is BLOCKED_PREREQUISITE."],
        refs=[IMPL08, IMPL09],
    ),
    case(
        "GOV-NFR-010", "NFR-010 Cost observability: token, model, tool and cost/run are measured and attributable",
        NFR_SUITE, "governance", ["NFR-010", "SRS-17", "ASM-002"],
        ["stage:EVIDENCE"], "baseline", "P0", "high",
        "AI spend is invisible until the invoice arrives, and no one can attribute cost to a run, a customer or a conversion, so unit economics cannot be managed.",
        [GOV_FX],
        _NFR_PRE + ["The mock model provider returns canned token usage so cost arithmetic is deterministic."],
        {"run": {"run_id": "run-nfr-10", "customer_id": "cust-a",
                 "provider_usage": {"prompt_tokens": 1200, "completion_tokens": 400, "model": "mock-llm-1"},
                 "pricing_config": {"per_1k_prompt_twd": 0.01, "per_1k_completion_twd": 0.02},
                 "tool_calls": 4, "tool_cost_twd": 0.002}},
        [("Execute one run and read the cost record",
          "The record contains prompt tokens, completion tokens, model identity and a cost_twd value per the audit schema field 17."),
         ("Recompute the cost from the recorded usage and the pricing configuration",
          "Recomputed cost equals 1200/1000*0.01 + 400/1000*0.02 + 0.002 = 0.022 TWD, matching the stored value."),
         ("Aggregate cost by run and by customer",
          "Cost per run and cost per customer are both derivable, and the per-customer total equals the sum of that customer's runs."),
         ("Check the dashboard display",
          "The displayed figures come from the stored records and are labelled with the measurement source; no target value is substituted.")],
        ["Cost is computed from recorded token usage and tool cost, and the arithmetic is reproducible to the stored value.",
         "Cost is attributable at run, customer and tenant level, with sums that reconcile.",
         "No displayed cost is a target, default or estimate presented as measured.",
         "Token counts are the provider-reported values, not local estimates, when the provider reports them."],
        ["Recording a flat estimated cost per run.",
         "Omitting tool or connector cost so only tokens are counted.",
         "Attributing a customer's cost to a shared pool that cannot be reconciled."],
        ["Cost record for the run with usage and split cost fields.",
         "Aggregation report by run and by customer.",
         "Provider usage payload used as the input."],
        ["Delete " + NS + " cost rows after export."],
        _NFR_AUTO,
        refs=[IMPL08, SRS],
    ),
    case(
        "GOV-NFR-010-BUDGET", "NFR-010 budget breach: exceeding the session budget throttles instead of silently overspending",
        NFR_SUITE, "governance", ["NFR-010", "NFR-008", "ASM-002"],
        ["stage:EXECUTION"], "extension", "P1", "high",
        "A runaway conversation with an unbounded tool loop burns cost with no limit, and the overrun is discovered only after the month closes.",
        [GOV_FX],
        _NFR_PRE + ["A tenant session budget is configured as a labelled synthetic design target of 1.00 TWD per session (ECN-003 provisional)."],
        {"session": {"conversation_id": "conv-nfr-10b", "budget_twd": 1.00,
                     "accumulating_turns": [0.20, 0.25, 0.30, 0.28, 0.15]}},
        [("Run turns until accumulated cost approaches the budget",
          "Cost is accumulated per turn and the session total is visible after each turn."),
         ("Exceed the budget on the next turn",
          "The session is throttled or degraded with a typed budget-breach state; the turn is not silently completed at full cost."),
         ("Inspect the customer-facing behaviour",
          "The customer receives a bounded fallback response (for example escalation to a human) rather than an endless loop."),
         ("Read the records",
          "The breach is recorded with the accumulated cost and the budget used, and the cost rows still sum to the measured total.")],
        ["The budget breach produces a typed state and a behaviour change, not an unbounded continuation.",
         "Accumulated cost never exceeds the budget by more than one turn's cost, and the overrun is recorded.",
         "The customer experience degrades gracefully (escalation or bounded reply) instead of hanging.",
         "Cost records reconcile to the measured total even across the breach."],
        ["Ignoring the budget and logging a warning.",
         "Cutting the session off with no customer-facing handling.",
         "Resetting the counter so the session can overspend repeatedly."],
        ["Session cost accumulation log across turns.",
         "Budget-breach state record with accumulated and limit values.",
         "Customer-facing fallback response payload."],
        ["Delete " + NS + " session and cost rows."],
        _NFR_AUTO,
        prereq=["The 0.5-1 TWD per-session budget is a provisional design target pending the ASM-002 baseline; the case exercises the control, not an approved cap."],
        refs=[IMPL08, ANALYTICS],
    ),
    case(
        "GOV-NFR-006", "NFR-006 data isolation: audit and context stores partition strictly by tenant and customer",
        NFR_SUITE, "governance", ["NFR-006", "NFR-002", "TC-E2E-004", "SRS-17"],
        ["entity:Customer", "entity:Evidence", "memory:Customer Context"], "baseline", "P0", "critical",
        "A shared cache key, a missing tenant predicate or a global audit chain lets one tenant's activity be read or attributed to another, which is a reportable breach.",
        [GOV_FX, CUST_FX, TENANTS_FX],
        _NFR_PRE + ["Two tenants T1 and T2 each have one pinned customer and one run; the harness can enumerate keys and query both schemas."],
        {"cross_checks": [
             {"label": "context cache", "action": "read T1 key from a T2 session", "expected": "MISS_OR_DENIED"},
             {"label": "audit chain", "action": "verify a mixed-tenant chain", "expected": "REJECTED"},
             {"label": "vector search", "action": "T2 query for a T1 document", "expected": "ZERO_HITS"},
             {"label": "customer context", "action": "cust-a session requesting cust-t2", "expected": "DENIED"}]},
        [("Attempt each of the four cross-boundary reads",
          "Every attempt is denied or returns an empty result; no foreign record appears in any response."),
         ("Inspect the storage partitioning evidence",
          "Cache keys include the tenant, RLS is enabled on the tenant-scoped tables, and the audit chain is partitioned per tenant."),
         ("Verify a deliberately mixed-tenant chain",
          "Chain verification rejects the sequence rather than passing it."),
         ("Scan every response body produced during the case",
          "Zero foreign identifiers, order ids or phone digits appear in any body.")],
        ["All four cross-boundary reads fail closed with no foreign data returned.",
         "Tenant isolation is enforced at the storage layer (keying and RLS), not only in application filters, which the partitioning evidence shows.",
         "A mixed-tenant audit chain is rejected by the verifier.",
         "Zero foreign identifiers appear in any serialized response."],
        ["Relying on application-level filters only.",
         "Sharing one audit chain across tenants.",
         "Returning a generic error while still serializing the foreign record."],
        ["Four refusal/empty responses with correlation ids.",
         "Partitioning evidence: cache key samples, RLS configuration readout, chain partition check.",
         "Serialized response scan results."],
        ["Delete " + NS + " cache keys and run rows for both tenants."],
        _NFR_AUTO,
        refs=[IMPL08, SRS],
    ),
)
